,
"Further Mathematics": [
 ["Polynomials & Remainder Theorem", ["polynomial","remainder","factor theorem","division","root","synthetic"],
  "A polynomial is an expression of the form aₙxⁿ + … + a₁x + a₀. The remainder theorem: when f(x) is divided by (x − a), the remainder is f(a). The factor theorem: (x − a) is a factor of f(x) if and only if f(a) = 0. These theorems factorise cubics and higher polynomials and solve equations without long division.",
  [{"q":"When f(x) = x³ − 2x + 1 is divided by (x − 1), the remainder is…","o":["0","1","2","−1"],"a":0,"e":"f(1) = 1 − 2 + 1 = 0, so (x−1) is a factor and the remainder is 0."},
   {"q":"Which of the following is a factor of x³ − 4x?","o":["x + 2","x + 4","x − 3","x + 1"],"a":0,"e":"x³ − 4x = x(x² − 4) = x(x−2)(x+2), so (x+2) is a factor."}]],
 ["Partial Fractions", ["partial fraction","denominator","numerator","proper","decomposition","linear"],
  "Partial fractions split a complicated rational expression into simpler fractions. For distinct linear factors, A/(x−a) + B/(x−b); for repeated factors, A/(x−a) + B/(x−a)². Solve for A and B by clearing denominators and substituting the roots. The decomposition is possible when the fraction is proper (degree of numerator less than degree of denominator).",
  [{"q":"Express 5/((x−1)(x−4)) as partial fractions: A/(x−1) + B/(x−4). Find A.","o":["−5/3","5/3","3/5","−3/5"],"a":0,"e":"5 = A(x−4) + B(x−1); putting x=1 gives 5 = A(−3), so A = −5/3."}]],
 ["Binomial Expansion", ["binomial","coefficient","expansion","Pascal","term","nCr"],
  "The binomial theorem expands (a + b)ⁿ: the terms follow aⁿ, aⁿ⁻¹b, … with coefficients from Pascal's triangle or nCr. The general term is nCr × aⁿ⁻ʳ × bʳ. For n a positive integer the expansion has n+1 terms. Common exam tasks are finding a particular term or coefficient, or using the expansion with small values for approximations.",
  [{"q":"In the expansion of (1 + x)⁶, the coefficient of x³ is…","o":["6","15","20","10"],"a":2,"e":"6C3 = 20."},
   {"q":"The number of terms in the expansion of (a + b)⁸ is…","o":["8","9","7","10"],"a":1,"e":"A binomial to power n has n + 1 = 9 terms."}]],
 ["Permutations & Combinations", ["permutation","combination","arrangement","selection","nPr","nCr"],
  "Permutations count arrangements where order matters: nPr = n!/(n−r)!. Combinations count selections where order does not matter: nCr = n!/(r!(n−r)!). Distinct or repeated objects and restrictions (e.g., vowels together) change the count. Key question: does order matter? If yes, permute; if no, combine.",
  [{"q":"How many ways can 3 students be arranged in a row from 5?","o":["10","60","20","125"],"a":1,"e":"5P3 = 5×4×3 = 60 arrangements."},
   {"q":"How many committees of 2 can be chosen from 5 people?","o":["20","10","25","5"],"a":1,"e":"Order does not matter: 5C2 = 10."}]],
 ["Complex Numbers", ["complex","imaginary","i squared","real part","conjugate","modulus"],
  "A complex number is z = a + bi, where i² = −1; a is the real part and b the imaginary part. Operations follow normal algebra with i² replaced by −1. The conjugate of a + bi is a − bi, used to divide complex numbers by multiplying numerator and denominator by the conjugate. The modulus is |z| = √(a² + b²).",
  [{"q":"If z = 3 + 4i, then |z| = …","o":["7","5","25","12"],"a":1,"e":"|z| = √(9 + 16) = 5."},
   {"q":"The conjugate of 2 − 5i is…","o":["2 + 5i","−2 + 5i","−2 − 5i","5 − 2i"],"a":0,"e":"The conjugate changes the sign of the imaginary part."}]],
 ["Differentiation & Its Applications", ["derivative","gradient","tangent","stationary","maximum","rate of change"],
  "Differentiation finds the rate of change: if y = xⁿ, dy/dx = nxⁿ⁻¹. The derivative is the gradient of the tangent at a point; setting dy/dx = 0 locates stationary points, classified as maxima, minima or points of inflection by the sign of the derivative (or the second derivative). Rates of change in physics (velocity = ds/dt) and marginal cost use the same idea.",
  [{"q":"If y = 3x² − 4x + 7, then dy/dx at x = 2 is…","o":["4","8","12","6"],"a":1,"e":"dy/dx = 6x − 4; at x = 2 this is 8."},
   {"q":"A curve has dy/dx = 2x − 6. Its minimum point is at x = …","o":["−6","3","6","−3"],"a":1,"e":"2x − 6 = 0 gives x = 3, where the gradient changes from negative to positive."}]]
],
"Christian Religious Studies": [
 ["The Life of Moses", ["Moses","Exodus","Passover","Red Sea","Sinai","covenant"],
  "God called Moses at the burning bush and sent him to free Israel from Egypt. After ten plagues, the Passover (the angel passing over homes marked with lamb's blood) preceded the Exodus; the Red Sea divided and Israel crossed dry. At Sinai God made a covenant and gave the Ten Commandments, and Israel became God's people under the Law.",
  [{"q":"At the burning bush, God revealed His name to Moses as…","o":["El Shaddai","I AM WHO I AM","Adonai","The Almighty"],"a":1,"e":"God said 'I AM WHO I AM' (Yahweh) — His covenant name."},
   {"q":"The event that marked Israel's deliverance from Egypt was…","o":["the flood","the Passover and exodus","the tower of Babel","the exile"],"a":1,"e":"The Passover angel and the crossing of the Red Sea delivered Israel from slavery."}]],
 ["Kingship in Israel: Saul, David & Solomon", ["Saul","David","Solomon","kingdom","anointed","wisdom"],
  "Israel demanded a king, and Samuel anointed Saul, who was rejected for disobedience. David, chosen for his faithfulness, killed Goliath, became king and received God's covenant of an everlasting dynasty. Solomon, his son, asked for wisdom and built the Temple, but his many wives and idolatry divided the kingdom after his death.",
  [{"q":"Who was the first king of Israel?","o":["David","Saul","Solomon","Samuel"],"a":1,"e":"Saul was anointed first, then rejected and replaced by David."},
   {"q":"Solomon asked God for…","o":["riches","long life","wisdom","victory in war"],"a":2,"e":"His request for wisdom pleased God, who also granted riches and honour."}]],
 ["The Prophets: Elijah & Amos", ["Elijah","prophet","Baal","Carmel","Amos","social justice"],
  "Elijah confronted Ahab and the prophets of Baal on Mount Carmel, proving the Lord is God, then fled to Horeb where God spoke in a still small voice. Amos, a shepherd from Tekoa, condemned social injustice — the rich selling the poor for silver, dishonest courts and empty religion — and called Israel to 'let justice roll down like waters'.",
  [{"q":"On Mount Carmel, Elijah challenged the prophets of…","o":["Asherah","Baal","Dagon","Molech"],"a":1,"e":"The confrontation with Baal's prophets proved Yahweh is the true God."},
   {"q":"Amos condemned the Israelites mainly for…","o":["cooking food","cheating the poor and unjust courts","worshipping in the temple","celebrating festivals"],"a":1,"e":"Amos preached justice: bribery, oppression of the poor and hollow religion."}]],
 ["The Ministry of Jesus: Miracles", ["miracle","healing","nature","faith","compassion","sign"],
  "Jesus' miracles are signs of the kingdom: healing the sick (the leper, the paralytic), casting out demons, and controlling nature (stilling the storm, feeding the five thousand, raising Lazarus). They show His divine authority and compassion, and call for faith. Each miracle teaches: faith over fear, compassion over ritual, and God's power in human need.",
  [{"q":"Jesus fed five thousand with…","o":["seven loaves","five loaves and two fish","bread from heaven","one loaf"],"a":1,"e":"Five loaves and two fish fed the crowd, with twelve baskets left over."},
   {"q":"The raising of Lazarus shows mainly Jesus' power over…","o":["the sea","death","disease only","sin only"],"a":1,"e":"The sign points to Jesus as the resurrection and the life."}]],
 ["The Parables of Jesus", ["parable","kingdom","sower","good samaritan","prodigal","lesson"],
  "A parable is an earthly story with a heavenly meaning. The Sower teaches hearing the word and the responses to it; the Good Samaritan defines the neighbour as anyone in need and love as practical; the Prodigal Son reveals God's forgiving love; the Lost Sheep shows joy over repentance; and the Talents teach faithful stewardship.",
  [{"q":"The Good Samaritan parable was told to answer the question…","o":["who is the Messiah?","who is my neighbour?","how to pray?","how to be rich?"],"a":1,"e":"Jesus answered the lawyer's question with the story of practical love."},
   {"q":"In the parable of the Sower, the seed on rocky ground represents…","o":["wealthy hearers","hearers who fall away when trouble comes","faithful hearers","non-believers only"],"a":1,"e":"Shallow soil = hearers who receive the word gladly but fall away in persecution."}]],
 ["The Early Church & Paul's Mission", ["Pentecost","Holy Spirit","Peter","Paul","mission","persecution"],
  "At Pentecost the Holy Spirit filled the apostles and Peter preached, and about three thousand were baptised: the church was born. The church shared possessions, worshipped and grew despite persecution — Stephen became the first martyr. Saul met the risen Christ on the Damascus road, became Paul, and took the gospel through Asia Minor and Europe, writing letters that became part of the New Testament.",
  [{"q":"The church was born at…","o":["the crucifixion","Pentecost","the ascension","the transfiguration"],"a":1,"e":"The Holy Spirit descended at Pentecost and Peter preached the first sermon."},
   {"q":"On the Damascus road, Saul…","o":["was arrested","met the risen Christ","baptised Peter","preached in Rome"],"a":1,"e":"The encounter with Christ converted Saul into Paul, apostle to the Gentiles."}]]
],
"Islamic Religious Studies": [
 ["The Prophet Muhammad (SAW): Makkah & Madinah", ["Muhammad","Makkah","Madinah","Hijrah","prophethood","Da'wah"],
  "The Prophet (SAW) was born in Makkah, his prophethood began at 40 with the first revelation at Cave Hira, and he called people to Tawhid despite persecution. In 622 CE he migrated (Hijrah) to Madinah, where he founded the first Muslim community and the Constitution of Madinah. His patience in Makkah and leadership in Madinah model both patience and community building.",
  [{"q":"The first revelation came to the Prophet (SAW) at…","o":["Mount Arafat","Cave Hira","the Ka'bah","the garden of Madinah"],"a":1,"e":"Angel Jibril brought the first verses of the Qur'an in Cave Hira."},
   {"q":"The migration of the Prophet to Madinah is called…","o":["Hajj","Hijrah","Ijtihad","Tawakkul"],"a":1,"e":"The Hijrah in 622 CE marked the start of the Islamic calendar."}]],
 ["Hadith & Sunnah", ["Hadith","Sunnah","isnad","authentic","example","source of law"],
  "Hadith records the sayings, actions and approvals of the Prophet (SAW); his practice is the Sunnah. A hadith has a chain of narrators (isnad) and a text (matn); scholars rank them authentic (sahih), good (hasan) or weak (da'if). The Sunnah is the second source of Islamic law after the Qur'an, explaining and applying it in daily life.",
  [{"q":"The chain of narrators of a hadith is called the…","o":["matn","isnad","tajwid","sunnah"],"a":1,"e":"Isnad is the chain; matn is the text."},
   {"q":"The second primary source of Islamic law is…","o":["consensus only","the Sunnah","ijtihad","custom"],"a":1,"e":"The Sunnah explains the Qur'an and is the second source of Shariah."}]],
 ["Worship: Salat & Zakat", ["salat","zakat","prayer","purification","obligation","wudu"],
  "Salat is the five daily prayers — Fajr, Zuhr, Asr, Maghrib and Isha — preceded by wudu (ablution); it keeps the believer mindful of Allah. Zakat is the obligatory annual alms of 2.5% of qualifying wealth given to the poor and eight categories named in the Qur'an; it purifies wealth and reduces inequality. Both are pillars of Islam: the second (salat) and the third (zakat).",
  [{"q":"How many obligatory prayers are there in a day?","o":["three","five","seven","four"],"a":1,"e":"Fajr, Zuhr, Asr, Maghrib and Isha are the five daily prayers."},
   {"q":"Zakat is paid on qualifying wealth at a rate of about…","o":["1%","2.5%","5%","10%"],"a":1,"e":"2.5% (1/40) of savings, gold, silver and livestock held for a year."}]],
 ["Fasting (Sawm) & Hajj", ["sawm","Ramadan","hajj","ihram","Ka'bah","Eid"],
  "Sawm is fasting from dawn (Fajr) to sunset (Maghrib) in the month of Ramadan: no food, drink or marital relations, with extra restraint in speech and conduct; it teaches taqwa (God-consciousness) and empathy for the poor. Hajj is the pilgrimage to Makkah in Dhul-Hijjah, in ihram, circling the Ka'bah and standing at Arafat — required once in a lifetime for those able.",
  [{"q":"Fasting in Ramadan is from…","o":["sunrise to sunset","dawn (Fajr) to sunset (Maghrib)","midday to midnight","sunset to dawn"],"a":1,"e":"The fast begins at dawn and ends with Maghrib."},
   {"q":"The central ritual of Hajj, standing at the plain of…","o":["Mina","Arafat","Muzdalifah","Safa"],"a":1,"e":"Wuquf at Arafat is the essence of Hajj."}]],
 ["Islamic Law: Shariah & Ethics", ["shariah","halal","haram","ibadah","mu'amalat","justice"],
  "Shariah is the Islamic way of life drawn from the Qur'an and Sunnah: acts of worship (ibadah) and social dealings (mu'amalat). Halal is lawful, haram unlawful; justice, honesty and mercy are central. Islamic ethics teach truthfulness, trustworthiness, kindness to parents, good neighbourhood and cleanliness, and forbid lying, cheating, gambling and usury.",
  [{"q":"In Islamic law, an act that is forbidden is…","o":["halal","haram","mustahab","mubah"],"a":1,"e":"Haram is prohibited; halal is permissible."}]],
 ["Islamic History: The Caliphate & Civilization", ["caliph","Abu Bakr","Umar","scholars","trade","civilization"],
  "After the Prophet, the Rightly-Guided Caliphs (Abu Bakr, Umar, Uthman and Ali) led the community; Abu Bakr fought the wars of apostasy and collected the Qur'an, Umar established the treasury and the calendar, Uthman standardised the mushaf and Ali upheld justice. Islamic civilization then flourished: Baghdad and Cordoba became centres of the translation movement, mathematics (al-Khwarizmi), medicine and trade across three continents.",
  [{"q":"The first caliph after the Prophet was…","o":["Umar","Abu Bakr","Uthman","Ali"],"a":1,"e":"Abu Bakr (RA) was chosen at Saqifah and served as first caliph."},
   {"q":"The compilation of the Qur'an into one mushaf was standardised under…","o":["Abu Bakr","Umar","Uthman","Ali"],"a":2,"e":"Uthman (RA) sent the standard copies of the mushaf to the provinces."}]]
],
"Data Processing": [
 ["Word Processing & Documents", ["word","format","document","template","heading","print"],
  "Word processors create letters, reports and brochures. Skills: typing and editing; formatting fonts, paragraphs and pages; headings and styles; tables and images; headers, footers and page numbers; spell-check and grammar tools; and mail merge for bulk letters. Save work in the right format and use print preview before printing.",
  [{"q":"Which feature sends one letter to many addresses with personal details?","o":["spell check","mail merge","page break","table of contents"],"a":1,"e":"Mail merge combines a template with a data source for personalised bulk letters."}]],
 ["Spreadsheets & Charts", ["spreadsheet","cell","formula","SUM","chart","filter"],
  "Spreadsheets organise numbers in a grid of cells referenced by column and row (A1). Formulas begin with = and use functions (SUM, AVERAGE, IF); absolute references ($) keep a cell fixed; sorting and filtering reorder data; charts (column, line, pie) and conditional formatting reveal patterns. Spreadsheets are used for marks, budgets, inventories and simple payrolls.",
  [{"q":"Given marks in B2:B10, the formula to find the average is…","o":["=TOTAL(B2:B10)","=AVERAGE(B2:B10)","=MEAN(B2;B10)","AVG(B2:B10)"],"a":1,"e":"AVERAGE returns the mean of the range."}]],
 ["Database Design", ["database","design","entity","key","normalisation","relationship"],
  "Database design starts with identifying entities and attributes, then building tables with a primary key and relationships (one-to-many) between them. Normalisation removes redundant data and update anomalies (1NF, 2NF, 3NF). A good design is consistent, avoids repeated data and is easy to query."
  ,[{"q":"The attribute that uniquely identifies each record in a table is the…","o":["foreign key","primary key","data type","index"],"a":1,"e":"A primary key uniquely identifies each row."}]],
 ["Presentation & Multimedia", ["presentation","slide","design","animation","multimedia","audience"],
  "Presentation software (PowerPoint, Google Slides) builds slide shows with text, images, audio and video. Good slides: one idea per slide, short bullets, high-contrast text, consistent design, and smooth transitions without distracting animation. Always rehearse and save in the right format (PPTX) and prepare a PDF backup for incompatible machines.",
  [{"q":"How many ideas should a good slide carry?","o":["as many as possible","one main idea","only pictures","ten bullet points"],"a":1,"e":"One clear idea per slide keeps the audience focused."}]],
 ["Internet & Web Technologies", ["internet","web","browser","search","URL","social media"],
  "The Internet is a global network; the Web is the document service on it. Browsers fetch pages via URLs over HTTP/HTTPS; search engines index the web, and advanced search (quotes, site:) improves results. Other services: email, file transfer, video calls and social media. Web safety includes passwords, privacy settings and verifying information before sharing.",
  [{"q":"A search engine works by…","o":["storing all pages locally","indexing web pages and matching queries","scanning your emails","downloading the web"],"a":1,"e":"Search engines crawl and index pages, then rank matches to queries."}]],
 ["Data Security & Cyber Ethics", ["security","cyber","password","phishing","privacy","law"],
  "Data security guards confidentiality, integrity and availability: strong unique passwords, two-factor authentication, encryption, firewalls, antivirus and backups. Cyber threats include phishing, malware, identity theft and ransomware. Cyber ethics: do not plagiarise, hack, spread false information or bully; respect copyright and privacy, and report abuse. Nigerian law (Cybercrime Act) punishes cyber offences.",
  [{"q":"A fake email that tricks you into revealing your password is…","o":["spam","phishing","firewall","cookie"],"a":1,"e":"Phishing impersonates trusted organisations to steal credentials."}]]
],
"Food & Nutrition": [
 ["Meal Planning & Menu Design", ["meal","menu","planning","budget","balance","family"],
  "Meal planning arranges the week's meals to meet nutritional needs, the family budget and available time. Good menus: variety of foods, all six nutrient groups, seasonal and cheap foods, and appeal through colour, texture and flavour. Plan around a food budget, use a shopping list, and rotate menus to avoid monotony while staying within the family income.",
  [{"q":"The first consideration when planning a family menu is…","o":["colour of dishes","nutritional needs and budget","imported foods","popularity only"],"a":1,"e":"The menu must meet nutrient needs within the family's money and time."}]],
 ["Methods of Cooking", ["boiling","frying","steaming","roasting","baking","grilling"],
  "Cooking makes food digestible, safe and attractive. Methods: boiling (in water, moist heat), steaming (vapour), stewing (slow in liquid), frying (in oil — shallow or deep), roasting and grilling (dry heat), and baking (oven). Each affects nutrients: boiling loses water-soluble vitamins, frying adds fat, steaming preserves the most nutrients.",
  [{"q":"Which cooking method conserves the most water-soluble vitamins?","o":["deep frying","steaming","boiling in much water","roasting"],"a":1,"e":"Steaming exposes food to vapour, minimising vitamin loss."}]],
 ["Food Preservation", ["preservation","drying","freezing","salting","canning","spoilage"],
  "Food preservation prevents spoilage by micro-organisms and enzymes. Methods: sun/air drying (removes moisture), salting and curing, smoking, refrigeration and freezing (slow microbe growth), boiling and canning (sterilisation), pickling in acid, and chemical preservatives. Choose a method by food type: grains by drying, meat by smoking/freezing, vegetables by freezing or canning.",
  [{"q":"Grains and legumes are best preserved by…","o":["canning","drying","freezing","pickling"],"a":1,"e":"Drying removes moisture so micro-organisms cannot grow."}]],
 ["Kitchen Hygiene & Safety", ["hygiene","sanitisation","safety","accident","contamination","storage"],
  "Kitchen hygiene prevents food poisoning: wash hands before cooking, keep raw and cooked foods apart, clean surfaces and utensils, store food at correct temperatures and check expiry dates. Safety: knife and fire care, pot handles turned inward, no trailing cables, fire extinguisher at hand, and correct use of gas and electrical equipment.",
  [{"q":"To prevent cross-contamination, raw meat and cooked food should be…","o":["stored together","kept separate","frozen together","cooked together longer"],"a":1,"e":"Separate boards, containers and shelves keep raw and cooked foods apart."}]],
 ["Nutritional Needs of the Family", ["nutrition","pregnancy","childhood","adolescent","elderly","balanced"],
  "Nutrient needs change through life: infants need breast milk then weaning foods; children need protein, calcium and iron for growth; adolescents need more energy, protein and iron; pregnant and lactating women need extra iron, calcium, folic acid and energy; the elderly need fewer calories but more calcium, protein and fibre. Balanced meals adapt to each stage and to activity.",
  [{"q":"Which nutrient do pregnant women need in extra amounts to prevent anaemia?","o":["iron","sugar","salt","starch"],"a":0,"e":"Extra iron and folic acid prevent anaemia in pregnancy."}]],
 ["Food Service & Entertaining", ["table","service","etiquette","placesetting","guest","host"],
  "Table service styles: table service (waiter), self-service (buffet) and family service. Correct table setting: fork left, knife and spoon right, glass above the knife, napkin at the side. Etiquette covers seating the guest of honour, serving from the right, clearing from the left, and polite conversation. A good host plans the menu, table and timing in advance.",
  [{"q":"In a formal table setting, the fork is placed…","o":["on the right","on the left","above the plate","behind the glass"],"a":1,"e":"Fork on the left (four letters, left) — knife and spoon on the right."}]]
],
"French": [
 ["Le Présent: Verbes Réguliers & Irréguliers", ["présent","conjugaison","-er","-ir","être","avoir"],
  "Au présent, les verbes en -er prennent -e, -es, -e, -ons, -ez, -ent (parler: je parle, nous parlons). Les verbes en -ir prennent -is, -is, -it, -issons, -issez, -issent (finir: je finis). Être (je suis), avoir (j'ai), aller (je vais) et faire (je fais) sont irréguliers et doivent être appris par cœur pour construire toutes les phrases du niveau SS1.",
  [{"q":"Choisissez la bonne forme: Nous ____ à l'école.","o":["va","allons","allez","vont"],"a":1,"e":"Avec nous, le verbe aller prend -ons: nous allons."},
   {"q":"Conjuguez: Vous (finir) vos devoirs.","o":["finissez","finis","finissons","finissent"],"a":0,"e":"Avec vous, les verbes en -ir prennent -issez: vous finissez."}]],
 ["Le Passé Composé", ["passé composé","auxiliaire","participe passé","avoir","être","accord"],
  "Le passé composé exprime une action terminée: auxiliaire avoir ou être + participe passé. Avec avoir, le participe ne s'accorde pas avec le sujet (j'ai parlé). Avec être (je suis allé), le participe s'accorde en genre et en nombre (elle est allée, ils sont allés). Les participes passés irréguliers: prendre→pris, voir→vu, faire→fait, écrire→écrit.",
  [{"q":"Choisissez: Elle ____ au marché hier.","o":["a allé","est allée","est allé","a allée"],"a":1,"e":"Aller se conjugue avec être et s'accorde: elle est allée."},
   {"q":"Le participe passé de 'avoir' est…","o":["eu","avé","euvoir","avait"],"a":0,"e":"J'ai eu: le participe passé d'avoir est eu."}]],
 ["Le Futur Simple", ["futur","infinitif","terminaisons","dema","prochain","verbe"],
  "Le futur simple se forme avec l'infinitif + -ai, -as, -a, -ons, -ez, -ont: je parlerai, tu parleras, il parlera, nous parlerons. Les verbes irréguliers changent de radical: être→ser-, avoir→aur-, aller→ir-, faire→fer-, venir→viendr-. Il exprime une action à venir: demain, je finirai mes devoirs.",
  [{"q":"Choisissez: Demain, nous ____ au match.","o":["irons","allons","ira","iront"],"a":0,"e":"Le futur d'aller avec nous: nous irons."},
   {"q":"La terminaison du futur avec 'je' est…","o":["-e","-ai","-ais","-a"],"a":1,"e":"Je parlerai: la terminaison est -ai."}]],
 ["Les Adjectifs & Pronoms Possessifs", ["possessif","mon","ma","mes","sa","accord"],
  "Les possessifs s'accordent avec le nom: mon livre, ma maison, mes amis; son/sa/ses, notre/nos, leur/leurs. Pour la possession, on utilise aussi 'de' (le livre de Paul). Devant une voyelle, ma devient mon (mon amie). Les pronoms possessifs (le mien, la tienne, les nôtres) remplacent le nom déjà mentionné.",
  [{"q":"Choisissez: Voici ____ école.","o":["mon","ma","mes","mien"],"a":1,"e":"École est féminin: ma école devient mon école devant voyelle."}]],
 ["L'Interrogation & La Négation", ["interrogation","négation","est-ce que","ne...pas","question","intonation"],
  "Trois façons de poser une question: l'intonation (Tu viens ?), est-ce que (Est-ce que tu viens ?), et l'inversion (Viens-tu ?). Avec inversion, les verbes en -er prennent un -t: Parle-t-il ? La négation s'écrit ne…pas / ne…jamais / ne…rien autour du verbe: je ne sais pas, il ne travaille jamais. 'Ne' s'élide devant une voyelle: je n'aime pas.",
  [{"q":"Choisissez la forme correcte: Il ____ regarde la télévision.","o":["n'","ne","pas","non"],"a":1,"e":"Devant une voyelle, ne devient n': il ne regarde pas."}]],
 ["La Compréhension & L'Expression Écrite", ["compréhension","lecture","dialogue","expression","lettre","résumé"],
  "Pour la compréhension: lire le texte deux fois, repérer les mots-clés, identifier qui/quoi/où/quand et répondre avec des phrases complètes. Pour l'expression écrite: suivre la consigne (longueur et type de texte), soigner les accords, les temps et la ponctuation, et présenter proprement (salutation, corps, formule de politesse pour une lettre). Relire avant de rendre.",
  [{"q":"Avant de répondre à une question de compréhension, il faut…","o":["écrire vite","lire le texte attentivement","copier le texte","ignorer la consigne"],"a":1,"e":"Lire deux fois et repérer les mots-clés donne des réponses exactes."}]
]
};
