/* v15.0 — Complete Curriculum Library · lesson notes expansion (part A: core 1–5).
   Each entry: [topic, keywords, key-facts, authored-questions(2-3)] */
var CURR = {
"Mathematics": [
 ["Sets & Venn Diagrams", ["set","venn","union","intersection","subset","element"],
  "A set is a well-defined collection of objects called elements. The union (A∪B) contains every element in A or B; the intersection (A∩B) contains only elements in both. Two sets are disjoint when their intersection is empty. Venn diagrams show these relationships as overlapping circles and are used to solve real counting problems.",
  [{"q":"If A = {2,4,6} and B = {4,5,6}, find A∩B.","o":["{2,4}","{4,6}","{2,4,5,6}","{5,6}"],"a":1,"e":"The intersection contains elements present in both sets: 4 and 6."},
   {"q":"In a class of 30, 18 play football and 14 play basketball, while 6 play both. How many play neither?","o":["2","4","6","8"],"a":1,"e":"18+14−6=26 play at least one; 30−26=4 play neither."}]],
 ["Logarithms & Indices", ["logarithm","indices","base","exponent","law","equation"],
  "Indices express repeated multiplication: a^m × a^n = a^(m+n) and a^m ÷ a^n = a^(m−n), with a^0 = 1. Logarithms are the inverse of indices: if a^x = N then log_a N = x. The three log laws are log(xy) = log x + log y, log(x÷y) = log x − log y and log x^n = n log x. Common logarithms use base 10.",
  [{"q":"Simplify 2^3 × 2^4.","o":["2^7","2^12","4^7","2^1"],"a":0,"e":"Add the indices: 2^(3+4) = 2^7."},
   {"q":"Given log 2 = 0.301, find log 8.","o":["0.602","0.903","1.204","0.753"],"a":1,"e":"log 8 = log 2^3 = 3 × 0.301 = 0.903."}]],
 ["Matrices", ["matrix","determinant","inverse","identity","row","column","order"],
  "A matrix is a rectangular array of numbers arranged in rows and columns; its order is rows × columns. Matrices of the same order can be added or subtracted element by element. Two matrices multiply when the columns of the first equal the rows of the second. For a 2×2 matrix, the determinant is ad − bc, and the matrix has an inverse only when the determinant is not zero.",
  [{"q":"Find the determinant of the matrix [[2,3],[1,4]].","o":["5","11","8","−5"],"a":0,"e":"det = (2×4) − (3×1) = 8 − 3 = 5."},
   {"q":"For a 2×2 matrix to have an inverse, its determinant must be…","o":["zero","one","non-zero","negative"],"a":2,"e":"A matrix whose determinant is zero is singular and has no inverse."}]],
 ["Bearings & Distances", ["bearing","orientation","compass","sine rule","cosine rule","direction"],
  "A bearing is the clockwise angle from north, written as three figures (040°, 135°). North and south bearings are opposite directions: the bearing of the point south is 180°. Distances between points are found with the sine and cosine rules when the triangle is not right-angled: a/sinA = b/sinB = c/sinC and a² = b² + c² − 2bc cosA.",
  [{"q":"The bearing of Q from P is 060°. What is the bearing of P from Q?","o":["120°","240°","300°","60°"],"a":1,"e":"Add 180° to the back bearing: 60° + 180° = 240°."},
   {"q":"In triangle PQR, PQ = 8 km, PR = 10 km and angle P = 60°. Find QR using the cosine rule.","o":["≈9.2 km","≈12.8 km","≈10.5 km","≈15.2 km"],"a":0,"e":"QR² = 8²+10²−2(8)(10)cos60° = 84, so QR ≈ 9.2 km."}]],
 ["Sequences & Series (AP/GP)", ["arithmetic","geometric","common difference","common ratio","nth term","sum"],
  "An arithmetic progression (AP) changes by a constant common difference d: Tn = a + (n−1)d. A geometric progression (GP) multiplies by a constant common ratio r: Tn = ar^(n−1). The sum of n terms of an AP is Sn = n/2 × (2a + (n−1)d); the sum of a GP is Sn = a(r^n − 1)/(r − 1) when r ≠ 1.",
  [{"q":"Find the 10th term of the AP 3, 7, 11, 15,…","o":["39","43","35","47"],"a":0,"e":"a=3, d=4; T10 = 3 + (10−1)(4) = 39."},
   {"q":"Find the sum of the first 5 terms of the GP 2, 6, 18,…","o":["242","360","121","182"],"a":0,"e":"a=2, r=3; S5 = 2(3^5−1)/(3−1) = 242."}]],
 ["Trigonometry: Sine & Cosine Rules", ["sine rule","cosine rule","trigonometry","triangle","angle","side"],
  "The sine rule relates sides to opposite angles in any triangle: a/sinA = b/sinB = c/sinC. The cosine rule finds a side from two sides and the included angle: a² = b² + c² − 2bc cosA. The area of any triangle is ½ab sinC. These rules work in non-right-angled triangles, which appear frequently in bearings and height-and-distance problems.",
  [{"q":"In triangle ABC, a = 10, b = 12 and angle B = 50°. Using the sine rule, sinA = ?","o":["(10 sin50°)/12","(12 sin50°)/10","(10 sin40°)/12","5/6"],"a":0,"e":"sinA/a = sinB/b gives sinA = a sinB / b = (10 sin50°)/12."},
   {"q":"The area of a triangle with sides 6 and 8 enclosing an angle of 30° is…","o":["12","24","48","10"],"a":0,"e":"Area = ½ × 6 × 8 × sin30° = 24 × 0.5 = 12."}]]
],
"English Language": [
 ["Letter Writing (Formal & Informal)", ["letter","formal","informal","salutation","address","signature"],
  "Letters have three fixed parts: the writer's address and date, the salutation, and the body, closing with a signature. Formal letters begin Dear Sir/Madam and end Yours faithfully; informal letters use the recipient's first name and end Yours sincerely or With love. Formal letters must state the purpose clearly in the first paragraph and keep a polite, businesslike tone throughout.",
  [{"q":"Which ending matches a letter that opens Dear Sir?","o":["Yours sincerely","Yours faithfully","With love","Best wishes"],"a":1,"e":"Dear Sir/Dear Madam pairs with Yours faithfully."},
   {"q":"The address of the writer in a formal letter appears…","o":["at the end","only in the body","at the top right","after the signature"],"a":2,"e":"The writer's address and date go at the top, before the salutation."}]],
 ["Essay Writing (Narrative & Argumentative)", ["essay","narrative","argumentative","introduction","conclusion","paragraph"],
  "A good essay has an introduction that states the topic, a body of two or more developed paragraphs, and a conclusion that rounds off the argument. Narrative essays tell a story in clear chronological order with vivid details. Argumentative essays take a clear stand, give three or more supporting points with examples, and answer the opposing side politely.",
  [{"q":"Which sentence best begins an argumentative essay on examination malpractice?","o":["Once upon a time there was a school","Examination malpractice destroys the worth of every certificate it touches","I woke up and went to school","There are many students in Nigeria"],"a":1,"e":"An argumentative essay opens with the writer's stand, not a story or a general description."}]],
 ["Summary Writing", ["summary","main point","concise","topic sentence","own words","key idea"],
  "A summary restates the main ideas of a passage in your own words and in a fixed number of sentences or words. Read the passage twice, identify the topic of each paragraph, then write one sentence per main idea, dropping examples, repetitions and minor details. Marks go to content, conciseness and the use of your own words — never copy whole sentences.",
  [{"q":"The first step in summary writing is to…","o":["copy the first sentence","read the passage and find the main ideas","count the words","rewrite the passage in full"],"a":1,"e":"Identify the main ideas of each paragraph before writing your own version."}]],
 ["Idioms & Phrasal Verbs", ["idiom","phrasal verb","figurative","meaning","expression"],
  "An idiom is a fixed expression whose meaning is figurative, not literal: to let the cat out of the bag means to reveal a secret. A phrasal verb is a verb plus a particle: give up (surrender), look after (care for), put off (postpone). The same verb takes different meanings with different particles, so learn them in context, not in isolation.",
  [{"q":"To hit the nail on the head means to…","o":["fail badly","say exactly the right thing","work very hard","be very angry"],"a":1,"e":"The idiom means to describe a situation precisely."},
   {"q":"She has decided to give up smoking. Give up here means…","o":["to begin","to stop","to sell","to forget"],"a":1,"e":"Give up = stop doing something."}]],
 ["Tenses & Concord", ["tense","present","past","future","concord","agreement","subject"],
  "Tense marks the time of an action: present (works), past (worked), future (will work), with progressive (is working) and perfect (has worked) forms. Concord means the subject and verb agree: singular subjects take singular verbs (The boy runs) and plural subjects take plural verbs (The boys run). Intervening phrases do not change the agreement.",
  [{"q":"Choose the correct sentence.","o":["The list of books are on the table","The list of books is on the table","The lists of books is on the table","The list of book are on table"],"a":1,"e":"The subject is the singular noun list, so the verb must be singular (is)."}]],
 ["Figures of Speech", ["simile","metaphor","personification","hyperbole","alliteration","imagery"],
  "Figures of speech give language force and colour. A simile compares using like or as (brave as a lion); a metaphor compares directly (time is money); personification gives human qualities to things (the wind whispered); hyperbole is deliberate exaggeration; alliteration repeats initial sounds; and imagery appeals to the senses. Identifying them is a regular WAEC/NECO objective.",
  [{"q":"The wind whispered through the trees is an example of…","o":["simile","personification","hyperbole","alliteration"],"a":1,"e":"The wind is given the human action of whispering."},
   {"q":"His smile is a ray of sunshine is an example of…","o":["metaphor","simile","personification","onomatopoeia"],"a":0,"e":"It compares directly without like or as, so it is a metaphor."}]]
],
"Biology": [
 ["Cell Division: Mitosis & Meiosis", ["mitosis","meiosis","chromosome","cell division","daughter cell","nucleus"],
  "Cell division produces new cells. Mitosis produces two daughter cells identical to the parent (same chromosome number) and drives growth and repair. Meiosis produces four cells with half the chromosome number and is the basis of gamete formation and variation. Both begin with chromosome duplication, but meiosis involves two divisions and crossing-over.",
  [{"q":"How many daughter cells are formed from one cell by meiosis?","o":["2","4","8","3"],"a":1,"e":"Meiosis produces four cells, each with half the chromosome number."},
   {"q":"Mitosis is mainly responsible for…","o":["gamete formation","growth and repair","crossing-over","halving chromosome number"],"a":1,"e":"Mitosis produces identical cells for growth and repair."}]],
 ["Nutrition in Plants & Animals", ["photosynthesis","respiration","nutrition","chlorophyll","digestion","glucose"],
  "Photosynthesis makes glucose from carbon dioxide and water using light energy trapped by chlorophyll, releasing oxygen. Animal nutrition is heterotrophic: food is ingested, digested, absorbed and assimilated. Enzymes speed up digestion — amylase breaks starch to maltose, protease breaks protein to amino acids, and lipase breaks fats to fatty acids and glycerol.",
  [{"q":"The site of photosynthesis in a plant cell is the…","o":["nucleus","chloroplast","vacuole","cell wall"],"a":1,"e":"Chloroplasts contain chlorophyll and carry out photosynthesis."},
   {"q":"Amylase digests starch into…","o":["amino acids","fatty acids","maltose","glucose only"],"a":2,"e":"Amylase breaks starch down into maltose, which maltase then turns to glucose."}]],
 ["The Respiratory System", ["respiration","lungs","gaseous exchange","alveoli","diaphragm","oxygen"],
  "Respiration releases energy from food, and can be aerobic (with oxygen) or anaerobic (without). In humans, air passes through the trachea and bronchi to the alveoli, where gaseous exchange occurs: oxygen diffuses into the blood and carbon dioxide out. The alveoli are adapted by being moist, thin-walled and richly supplied with capillaries.",
  [{"q":"Gaseous exchange in the lungs takes place in the…","o":["bronchi","trachea","alveoli","diaphragm"],"a":2,"e":"Alveoli are the tiny air sacs where oxygen and carbon dioxide are exchanged."}]],
 ["Coordination: The Nervous System", ["neurone","reflex","brain","spinal cord","impulse","synapse"],
  "Coordination is carried out by the nervous and endocrine systems. A neurone carries electrical impulses; the CNS (brain and spinal cord) receives and processes them; a reflex action is a fast, automatic response that does not involve conscious thought, such as withdrawing a hand from a flame. Impulses cross the synapse between neurones by chemicals called neurotransmitters.",
  [{"q":"A reflex action is best described as a response that is…","o":["conscious and slow","automatic and fast","learned and deliberate","voluntary and slow"],"a":1,"e":"Reflexes are automatic, rapid responses that protect the body."}]],
 ["Reproduction in Humans", ["gamete","fertilisation","ovulation","menstrual","placenta","pregnancy"],
  "The male gamete is the sperm, produced in the testes; the female gamete is the ovum, released at ovulation. Fertilisation (union of sperm and ovum) occurs in the oviduct. The zygote implants in the uterus, where the placenta supplies nutrients and oxygen and removes waste. The menstrual cycle is governed by hormones and rarely lasts exactly 28 days for every woman.",
  [{"q":"Fertilisation in humans normally occurs in the…","o":["uterus","vagina","oviduct","ovary"],"a":2,"e":"The sperm meets the ovum in the oviduct (fallopian tube)."}]],
 ["Genetics & Evolution", ["gene","allele","dominant","recessive","variation","natural selection"],
  "Genes on chromosomes carry hereditary information; alleles are alternative forms of a gene. In a monohybrid cross, the dominant allele masks the recessive one, giving the classic 3:1 ratio of offspring. Variation within a species comes from mutation and sexual reproduction; natural selection favours useful variations so that over time populations evolve.",
  [{"q":"In a monohybrid cross of two heterozygotes (Tt × Tt), the phenotypic ratio is…","o":["1:1","3:1","1:2:1","9:3:3:1"],"a":1,"e":"Three show the dominant trait, one shows the recessive: 3:1."}]]
],
"Chemistry": [
 ["Electrolysis & Electricity", ["electrolysis","electrolyte","anode","cathode","ions","current"],
  "Electrolysis breaks down an electrolyte (molten or dissolved ionic compound) using electricity. The cathode (negative electrode) attracts cations, which gain electrons; the anode (positive electrode) attracts anions, which lose electrons. For example, electrolysis of molten NaCl gives sodium at the cathode and chlorine at the anode. The amount of product depends on the quantity of charge passed.",
  [{"q":"During electrolysis, cations migrate to the…","o":["anode","cathode","both electrodes","neither electrode"],"a":1,"e":"Cations are positive, so they move to the negative electrode (cathode)."},
   {"q":"The gas given off at the anode during electrolysis of dilute H2SO4 is…","o":["hydrogen","oxygen","sulphur dioxide","water vapour"],"a":1,"e":"Hydroxide ions are discharged at the anode to give oxygen."}]],
 ["Metals & Their Extraction", ["metal","ore","smelting","blast furnace","reduction","reactivity"],
  "Metals are extracted from their ores; the method depends on reactivity. Unreactive metals such as gold occur native. Metals from zinc upwards are extracted by reduction with carbon or electrolysis: iron comes from haematite in the blast furnace and aluminium from bauxite by electrolysis. The reactivity series (K > Na > Ca > Mg > Al > C > Zn > Fe > H > Cu > Ag > Au) predicts displacement reactions.",
  [{"q":"Iron is extracted from haematite in the…","o":["open hearth","blast furnace","fractional column","flotation tank"],"a":1,"e":"The blast furnace reduces haematite with carbon monoxide."},
   {"q":"Which metal is extracted by electrolysis of its molten ore?","o":["iron","copper","aluminium","zinc"],"a":2,"e":"Aluminium is too reactive for carbon reduction, so electrolysis is used."}]],
 ["Organic Chemistry: Alkanes", ["alkane","hydrocarbon","saturated","methane","homologous","fractional distillation"],
  "Alkanes are saturated hydrocarbons of general formula CnH2n+2: methane CH4, ethane C2H6, propane C3H8. They are obtained from crude oil by fractional distillation and burn to give carbon dioxide and water. Their main reaction is substitution with halogens in sunlight; as members of a homologous series they differ by a CH2 unit.",
  [{"q":"Which of these is an alkane?","o":["C2H4","C2H6","C2H2","C6H6"],"a":1,"e":"C2H6 is ethane, an alkane with formula CnH2n+2 for n=2."}]],
 ["Rates of Reaction", ["rate","catalyst","concentration","temperature","surface area","collision"],
  "The rate of a reaction increases with higher concentration, higher temperature, smaller particle size (greater surface area) and the presence of a catalyst. Collision theory explains why: particles must collide with enough energy (activation energy) to react, and these factors increase the frequency or energy of effective collisions.",
  [{"q":"Which change increases the rate of a reaction most?","o":["lowering the temperature","adding a catalyst","diluting the reactants","using larger lumps"],"a":1,"e":"A catalyst lowers activation energy, speeding up the reaction without being used up."}]],
 ["Reversible Reactions & Equilibrium", ["equilibrium","reversible","Le Chatelier","limestone","entropy"],
  "Many reactions are reversible and shown with ⇌. At equilibrium the forward and backward rates are equal, so concentrations stay constant. Le Chatelier's principle: a system at equilibrium shifts to oppose a change — increasing concentration or pressure shifts it to the side with fewer molecules/less of the added substance; increasing temperature favours the endothermic direction.",
  [{"q":"Increasing the pressure of N2 + 3H2 ⇌ 2NH3 shifts the equilibrium…","o":["to the left","to the right","not at all","randomly"],"a":1,"e":"The forward side has fewer gas molecules (4 → 2), so higher pressure favours it."}]],
 ["Water & Solutions", ["water","solution","solute","solvent","concentration","hard water"],
  "Water is a universal solvent because it is polar. A solution is a solute dissolved in a solvent; concentration is the amount of solute per volume of solution. Hard water contains dissolved calcium and magnesium salts, which stop soap lathering; it can be softened by boiling (temporary hardness) or ion exchange. Water boils at 100°C at 1 atm.",
  [{"q":"Hardness of water that is removed by boiling is called…","o":["permanent","temporary","artificial","mineral"],"a":1,"e":"Boiling removes temporary hardness caused by hydrogencarbonates."}]]
],
"Physics": [
 ["Vectors & Scalars", ["vector","scalar","displacement","velocity","force","resultant"],
  "Quantities with only size are scalars (distance, speed, mass, time). Quantities with size and direction are vectors (displacement, velocity, acceleration, force). Vectors add by head-to-tail or by resolution: the resultant of two perpendicular vectors is found from R² = X² + Y² and tanθ = Y/X.",
  [{"q":"Which of these is a vector quantity?","o":["speed","distance","displacement","mass"],"a":2,"e":"Displacement has both magnitude and direction, so it is a vector."},
   {"q":"A force of 3 N east and 4 N north act together. The resultant is…","o":["5 N at 53° to the east","7 N","1 N","5 N due north"],"a":0,"e":"R = √(3²+4²) = 5 N, at tan⁻¹(4/3) ≈ 53° to the east."}]],
 ["Projectile Motion", ["projectile","trajectory","gravity","range","maximum height","parabola"],
  "A projectile is an object moving under gravity alone. Its horizontal motion is uniform (constant velocity) while vertical motion is uniform acceleration g = 9.8 m/s². The path is a parabola. Time of flight, maximum height and range follow from the initial velocity and angle of projection; at maximum height the vertical velocity is zero.",
  [{"q":"At the maximum height of a projectile, the vertical velocity is…","o":["maximum","zero","equal to horizontal velocity","negative"],"a":1,"e":"The projectile stops rising (v=0) at the top before falling."}]],
 ["Energy, Work & Power", ["work","energy","power","joule","watt","conservation"],
  "Work is done when a force moves a body: W = F × d (joules). Energy is the capacity to do work, in kinetic (½mv²), potential (mgh) and other forms; the principle of conservation states energy is neither created nor destroyed, only converted. Power is the rate of doing work: P = W/t (watts), and efficiency = useful output ÷ total input × 100%.",
  [{"q":"A force of 20 N moves a box 5 m. The work done is…","o":["4 J","25 J","100 J","15 J"],"a":2,"e":"W = 20 × 5 = 100 J."},
   {"q":"A machine uses 1000 J in 5 s. Its power is…","o":["200 W","5000 W","2000 W","5 W"],"a":0,"e":"P = 1000 ÷ 5 = 200 W."}]],
 ["Sound Waves", ["sound","frequency","pitch","loudness","echo","vibration"],
  "Sound is a longitudinal wave produced by vibration and needs a medium (it cannot travel in a vacuum). Its speed is about 340 m/s in air, faster in water and solids. Frequency determines pitch; amplitude determines loudness. An echo is a reflected sound; echo sounding uses the relation distance = (speed × time)/2.",
  [{"q":"Sound cannot travel through a…","o":["liquid","solid","vacuum","gas"],"a":2,"e":"Sound needs a material medium to travel; there is none in a vacuum."}]],
 ["Light: Lenses & Mirrors", ["convex","concave","focal length","image","refraction","magnification"],
  "Convex (converging) lenses and concave mirrors can form real images that can be captured on a screen; concave (diverging) lenses and convex mirrors form only virtual images. The lens/mirror equation 1/f = 1/u + 1/v links focal length f, object distance u and image distance v; magnification m = v/u = hi/ho.",
  [{"q":"Which lens always forms a virtual, upright and diminished image?","o":["convex","concave","converging","biconvex"],"a":1,"e":"A concave (diverging) lens always gives a virtual, upright, diminished image."}]],
 ["Electronics & Semiconductors", ["semiconductor","diode","transistor","doping","p-n junction","rectifier"],
  "Semiconductors (silicon, germanium) conduct better than insulators but worse than metals. Doping adds impurities to make n-type (extra electrons) or p-type (holes) material. A p-n junction diode allows current one way only and is used as a rectifier to change AC to DC; a transistor amplifies or switches signals.",
  [{"q":"A diode is used in a circuit mainly to…","o":["amplify signals","rectify alternating current","store charge","resist current"],"a":1,"e":"A diode conducts in one direction only, so it converts AC to DC."}]]
]
};
