,
"Agricultural Science": [
 ["Farm Tools & Machinery", ["tool","machinery","tractor","implement","cultivation","maintenance"],
  "Farm tools are hand implements such as cutlasses, hoes, rakes and watering cans, used for small-scale work. Machinery includes tractors and implements (plough, harrow, ridger) powered by engines and used for large-scale cultivation. Machinery increases output and speed but needs capital, fuel, skilled operators and regular maintenance.",
  [{"q":"Which of these is a farm machine?","o":["hoe","cutlass","tractor","rake"],"a":2,"e":"A tractor is powered machinery; the others are hand tools."},
   {"q":"The main advantage of farm machinery is…","o":["cheap initial cost","increased speed of work","no maintenance needed","works on any soil"],"a":1,"e":"Machinery covers land faster and more uniformly, raising output per labour-hour."}]],
 ["Pests & Diseases of Crops", ["pest","disease","control","insecticide","fungicide","infestation"],
  "Crop pests include insects (stem borers, grasshoppers), rodents, birds and nematodes; diseases are caused by fungi, bacteria and viruses. Damage appears as holes, wilting, rots and stunted growth. Control methods are cultural (crop rotation, clean seed), biological (natural enemies), chemical (insecticides and fungicides) and mechanical (traps, physical removal).",
  [{"q":"A chemical used to control fungal crop diseases is called a…","o":["insecticide","herbicide","fungicide","rodenticide"],"a":2,"e":"Fungicides target fungi; insecticides target insects."}]],
 ["Animal Nutrition & Feeds", ["feed","ration","nutrients","concentrate","roughage","supplement"],
  "Farm animals need carbohydrates, proteins, fats, minerals, vitamins and water. Feeds fall into roughages (grass, hay, silage — bulky, fibrous) and concentrates (grains, oilseed cakes — rich in energy or protein). A ration is the daily feed allowance; a balanced ration supplies all nutrients in the right proportions for production or growth.",
  [{"q":"Which of these is a concentrate feed?","o":["fresh grass","maize grain","silage","straw"],"a":1,"e":"Maize grain is an energy-rich concentrate; grass and silage are roughages."}]],
 ["Poultry & Livestock Production", ["poultry","broiler","layer","housing","vaccination","management"],
  "Poultry includes broilers (for meat) and layers (for eggs); deep litter and battery cage systems are both used in Nigeria. Good management requires proper housing, clean water, balanced feed, lighting and routine vaccination against Newcastle disease and fowl pox. Cattle and goats are kept for meat, milk and hides under extensive or intensive systems.",
  [{"q":"A layer is a bird kept for…","o":["meat","eggs","both eggs and meat","breeding only"],"a":1,"e":"Layers are managed for egg production; broilers for meat."}]],
 ["Fisheries & Fish Farming", ["fish","pond","aquaculture","fingerling","feeding","harvest"],
  "Fisheries include capture from rivers and the sea and aquaculture (fish farming). Ponds are stocked with fingerlings, fed with formulated feed, and must have good water quality (oxygen, pH, temperature). Common farmed species in Nigeria are tilapia and catfish. Harvesting is by netting or draining, and fish spoil quickly without preservation.",
  [{"q":"The young fish stocked into a pond are called…","o":["fingerlings","fry traps","cob","juveniles only"],"a":0,"e":"Fingerlings are the young fish of stocking size."}]],
 ["Farm Management & Records", ["management","record","labour","budget","planning","enterprise"],
  "Good farm management plans the use of land, labour, capital and equipment to maximise profit. Records are kept for production, sales, labour and finances, enabling the farmer to compare enterprises and make decisions. Records include farm diary, inventory, labour and cash books, and they support credit applications and taxes.",
  [{"q":"Which farm record shows the value of equipment, animals and produce?","o":["labour record","inventory","cash book","diary"],"a":1,"e":"An inventory lists assets and their values at a point in time."}]
],
"Economics": [
 ["Elasticity of Demand & Supply", ["elasticity","price","demand","supply","responsive","revenue"],
  "Price elasticity of demand measures how much quantity demanded responds to a price change: PED = %ΔQ ÷ %ΔP. Demand is elastic (PED > 1) when consumers switch easily, inelastic (PED < 1) for necessities. For a producer: if demand is elastic, a price cut raises total revenue; if inelastic, a price rise raises revenue. Elasticity of supply depends on time and production flexibility.",
  [{"q":"If a 10% price cut raises quantity demanded by 25%, demand is…","o":["inelastic","elastic","unitary","perfectly inelastic"],"a":1,"e":"PED = 25÷10 = 2.5 > 1, so demand is elastic."},
   {"q":"Taxing a good with inelastic demand shifts the burden mostly to…","o":["the producer","the consumer","the government","exporters"],"a":1,"e":"Consumers keep buying despite the price rise, so they bear most of the tax."}]],
 ["Inflation & Unemployment", ["inflation","unemployment","price level","CPI","full employment","deflation"],
  "Inflation is a persistent rise in the general price level, measured by the Consumer Price Index; it erodes the purchasing power of money. Demand-pull inflation follows excess demand, cost-push follows rising costs. Unemployment is the number of able-bodied people willing and able to work who cannot find jobs; types include frictional, structural and cyclical. High inflation and unemployment together are stagflation.",
  [{"q":"A persistent rise in the general price level is called…","o":["deflation","inflation","stagflation","recession"],"a":1,"e":"Inflation is the sustained upward movement of the general price level."},
   {"q":"Unemployment caused by changes in the structure of industry is…","o":["frictional","structural","cyclical","seasonal"],"a":1,"e":"Structural unemployment follows the decline of old industries and the rise of new skills."}]],
 ["Public Finance & Taxation", ["tax","fiscal","budget","direct","indirect","public debt"],
  "Public finance studies government revenue and expenditure. Revenue comes from taxes (direct — paid by the taxpayer, like income tax; indirect — levied on goods, like VAT), fees, fines and borrowing. A budget is the planned revenue and expenditure for a year; a deficit budget spends more than it earns. Progressive taxes take a larger share of higher incomes and reduce inequality.",
  [{"q":"Which of these is a direct tax?","o":["VAT","import duty","income tax","excise duty"],"a":2,"e":"Income tax is paid directly by the taxpayer to the government."},
   {"q":"A budget in which planned expenditure exceeds revenue is…","o":["surplus","balanced","deficit","supplementary"],"a":2,"e":"Expenditure greater than revenue is a deficit budget."}]],
 ["International Trade", ["export","import","balance of payment","terms of trade","comparative advantage","quota"],
  "International trade is the exchange of goods and services between countries, based on comparative advantage — each country produces goods it can make relatively cheaply. Exports earn foreign exchange; imports use it. The balance of trade is exports minus imports of goods; the balance of payments adds services, transfers and capital flows. Restrictions include tariffs, quotas and embargoes.",
  [{"q":"The value of exports less the value of imports of goods is the…","o":["balance of payments","balance of trade","terms of trade","current account"],"a":1,"e":"The balance of trade covers visible (goods) trade only."},
   {"q":"A government limit on the quantity of an import is a…","o":["tariff","quota","dumping","devaluation"],"a":1,"e":"A quota restricts quantity; a tariff is a tax on imports."}]],
 ["Money & Banking", ["money","currency","bank","credit","interest","liquidity"],
  "Money performs four functions: medium of exchange, measure of value, store of value and standard of deferred payment. Its qualities are acceptability, portability, durability, divisibility and relative scarcity. Commercial banks accept deposits, give loans and create credit; the central bank issues currency, controls credit, holds reserves and acts as banker to the government.",
  [{"q":"Which function of money allows comparing the worth of two goods?","o":["medium of exchange","measure of value","store of value","deferred payment"],"a":1,"e":"Money acts as a common yardstick for valuing goods."},
   {"q":"The bank that issues currency in Nigeria is the…","o":["First Bank of Nigeria","Central Bank of Nigeria","Commercial banks","Bank of Industry"],"a":1,"e":"Only the central bank issues legal tender."}]],
 ["National Income", ["GDP","GNP","gross domestic","per capita","output","net factor"],
  "National income is the total value of goods and services produced in a country in a year. GDP measures production within the country's borders; GNP adds net income earned abroad. Per capita income is national income ÷ population, and is used to compare living standards, though it hides inequality. Measurement uses the output, income and expenditure approaches, which should agree.",
  [{"q":"The total value of goods and services produced within a country's borders in a year is…","o":["GNP","GDP","NNP","per capita income"],"a":1,"e":"GDP is domestic production; GNP adds net factor income from abroad."},
   {"q":"Per capita income is obtained by dividing national income by…","o":["total imports","population","total savings","number of workers"],"a":1,"e":"Per capita income = national income ÷ population."}]
],
"Government": [
 ["The Executive", ["executive","president","implementation","cabinet","prerogative","appointment"],
  "The executive implements the laws and runs the government. In a presidential system, a directly elected president is both head of state and head of government and appoints ministers; in a parliamentary system, the prime minister is drawn from the legislature and is answerable to it. The executive's powers include appointment, pardon, foreign policy and command of the armed forces.",
  [{"q":"The organ of government that implements laws is the…","o":["legislature","judiciary","executive","civil service only"],"a":2,"e":"The executive implements and administers the laws made by the legislature."}]],
 ["The Legislature", ["legislature","parliament","bicameral","unicameral","bill","oversight"],
  "The legislature makes laws, approves budgets and checks the executive. Nigeria's National Assembly is bicameral: the Senate (108 members) and the House of Representatives (360 members). A bill is debated, passed by both chambers and assented to by the president before becoming law. Other functions include ratification of treaties and oversight of the executive via committees.",
  [{"q":"Nigeria's National Assembly is called bicameral because it has…","o":["one chamber","two chambers","three chambers","four chambers"],"a":1,"e":"The Senate and House of Representatives form two chambers."}]],
 ["The Judiciary", ["judiciary","court","judge","independence","appeal","review"],
  "The judiciary interprets the law, settles disputes and reviews the actions of the other arms. Its independence is protected by security of tenure, fixed salaries and the separation of powers. In Nigeria, the Supreme Court is the highest court, followed by the Court of Appeal, Federal High Courts and State High Courts. Judicial review declares acts of the executive or legislature unconstitutional.",
  [{"q":"The highest court in Nigeria is the…","o":["Court of Appeal","Federal High Court","Supreme Court","Sharia Court of Appeal"],"a":2,"e":"The Supreme Court is the final appellate court."}]],
 ["Federalism", ["federalism","states","delegated","residual","concurrent","secession"],
  "Federalism divides power between a central government and component units (states). The constitution lists exclusive powers (defence, currency, foreign affairs), concurrent powers (education, health) for both levels, and residual powers left to the states. Federalism suits a large, heterogeneous country like Nigeria, but it can breed duplication and friction.",
  [{"q":"Which of these is an exclusive power in a federation?","o":["education","defence","health","agriculture"],"a":1,"e":"Defence, currency and foreign affairs are exclusive to the centre."}]],
 ["The Constitution & Rule of Law", ["constitution","rule of law","entrenched","supreme","rights","legality"],
  "A constitution is the body of fundamental rules by which a state is governed; in a written constitution, it is supreme and entrenched (hard to amend). Rule of law means the supremacy of law over every person, equality before the law and the fair enforcement of fundamental human rights. Its limits include emergency powers and sovereign immunity.",
  [{"q":"A constitutional provision that cannot be easily amended is said to be…","o":["flexible","entrenched","unwritten","customary"],"a":1,"e":"Entrenched clauses need special majorities to change."}]],
 ["Local Government", ["local government","council","chairman","ward","rates","grassroots"],
  "Local government is the third tier of government, closest to the people. A local government council, headed by a chairman with councillors from wards, provides primary education support, health centres, roads, markets, sanitation and revenue collection (rates, licences). Section 7 of the 1999 Constitution guarantees democratically elected local governments; they are funded by statutory allocations, internally generated revenue and grants.",
  [{"q":"The head of a local government council is the…","o":["governor","chairman","president","senator"],"a":1,"e":"A democratically elected chairman heads the council."}]
],
"Literature in English": [
 ["Non-African Prose Study", ["novel","setting","character","theme","non-African","author"],
  "Non-African prose studied in Nigerian schools includes works by non-African novelists. Analysis follows the elements of fiction: plot, setting, characterisation, theme, point of view, language and style. Candidates should locate the background of the work, describe the major characters with evidence, discuss two or more themes and relate the work to human experience.",
  [{"q":"In studying a novel, the underlying message of the work is its…","o":["plot","theme","setting","style"],"a":1,"e":"The theme is the central idea or message the writer explores."}]],
 ["African Poetry Study", ["poem","African","imagery","tone","rhythm","oral tradition"],
  "African poetry draws on oral tradition — proverbs, songs, praise poetry and rhythm. Analysis covers speaker, tone, theme, imagery, diction and sound devices. Praise poetry celebrates heroes; protest poetry challenges oppression. When answering, quote briefly to support every claim about effect or meaning.",
  [{"q":"Praise poetry in African tradition primarily…","o":["mocks a ruler","celebrates heroes and achievements","teaches grammar","narrates wars only"],"a":1,"e":"Praise poetry honours persons, clans or achievements, often with hyperbole."}]],
 ["Unseen Poetry Analysis", ["unseen","comprehension","figure of speech","mood","appreciation","paraphrase"],
  "Unseen poetry tests appreciation without prior study. Steps: read twice, identify the speaker and situation, note the dominant mood, paraphrase the poem, then discuss the figures of speech and sound devices and their effect. Always answer in your own words and support points with short quotations.",
  [{"q":"The first thing to identify in an unseen poem is…","o":["the rhyme scheme only","the speaker and subject","the date of publication","the poet's biography"],"a":1,"e":"Understanding what the poem is about and who speaks comes before technique."}]],
 ["Literary Devices & Figures", ["metaphor","simile","irony","symbolism","allusion","imagery"],
  "Literary devices shape meaning: simile and metaphor compare; irony says one thing and means another; symbolism uses objects for abstract ideas; allusion refers to a known person or event; imagery appeals to the senses; and onomatopoeia imitates sounds. Naming the device is only half the answer — the examiner wants its effect in the passage.",
  [{"q":"My love is a red, red rose is an example of…","o":["simile","metaphor","allusion","hyperbole"],"a":1,"e":"The direct comparison without like or as makes it a metaphor."}]],
 ["Comparative Analysis", ["compare","contrast","similar","different","structure","both texts"],
  "Comparative questions demand parallel treatment: point by point, a similarity or difference, with evidence from both texts. Compare themes, characters, tone, techniques and structure; avoid treating the texts one after the other without linking. A conclusion should state the overall relationship between the works.",
  [{"q":"When answering a comparative question, the best structure is…","o":["a full summary of one text","point-by-point comparison with evidence","a list of titles","only personal opinion"],"a":1,"e":"Parallel points with evidence from both texts earn the marks."}]],
 ["Textual Evidence & Style", ["quotation","evidence","style","diction","prose","analysis"],
  "Marks in literature depend on evidence. Quote short phrases or line numbers and link each to the point being made. Style covers the writer's diction (word choice), sentence patterns, imagery and narrative techniques. A well-integrated quotation — not long copying — shows close reading and wins marks.",
  [{"q":"A short quotation is used in literary answers mainly to…","o":["fill the page","support the point being made","show memorisation","avoid thinking"],"a":1,"e":"Evidence from the text is the basis of every valid literary claim."}]
],
"Geography": [
 ["Map Reading & Interpretation", ["map","scale","contour","bearing","grid","relief"],
  "Map reading uses scale (ratio, statement or linear), grid reference, bearings and symbols. Contour lines show relief: close contours mean steep slopes, wide contours gentle slopes; their pattern identifies hills, valleys, spurs and passes. Local relief and drainage are read from contour form, and distances are measured along the route using the scale.",
  [{"q":"Contour lines that are very close together indicate…","o":["gentle slope","steep slope","flat land","a river"],"a":1,"e":"The closer the contours, the steeper the gradient."},
   {"q":"The vertical interval on a map is the…","o":["height of the highest point","difference between two adjacent contours","length of the map","number of grid squares"],"a":1,"e":"The vertical interval is the constant difference in height between successive contours."}]],
 ["Weather & Climate", ["weather","climate","rainfall","temperature","instruments","forecast"],
  "Weather is the day-to-day condition of the atmosphere; climate is the average weather over many years. Elements measured are temperature, rainfall, pressure, wind, humidity and sunshine, using the thermometer, rain gauge, barometer, anemometer, hygrometer and sunshine recorder. Weather instruments are kept in a Stevenson screen to give standard readings.",
  [{"q":"Rainfall is measured with a…","o":["barometer","rain gauge","anemometer","hygrometer"],"a":1,"e":"The rain gauge collects rain; the anemometer measures wind speed."}]],
 ["Population & Settlement", ["population","birth rate","density","migration","settlement","growth"],
  "Population study covers size, distribution, density and growth (births, deaths, migration). Nigeria's population is large and youthful, with rapid growth. Overpopulation, underpopulation and optimum population each compare population to resources. Settlements grow from villages to cities where functions (trade, administration, industry) concentrate; urbanisation brings pressure on housing and services.",
  [{"q":"Population density is…","o":["total births in a year","people per unit area","urban population only","migrants in a year"],"a":1,"e":"Density = population ÷ area, usually people per km²."}]],
 ["River Landforms & Delta", ["river","erosion","deposition","delta","meander","floodplain"],
  "Rivers erode, transport and deposit. Landforms include valleys, gorges, waterfalls, meanders, ox-bow lakes, levees and floodplains. A delta forms where a river deposits sediment on entering a slow or still water body (sea or lake), building up distributaries and swampy islands, as in the Niger Delta. Deltas are fertile but prone to flooding.",
  [{"q":"A delta is formed mainly by…","o":["erosion","deposition","volcanism","tectonic uplift"],"a":1,"e":"Deposition of sediment at a river mouth builds a delta."}]],
 ["Industrial & Economic Geography", ["industry","location","raw material","market","labour","agglomeration"],
  "Location factors for industry are raw materials, power, market, labour, transport and government policy. Primary industries extract (mining, farming); secondary industries manufacture; tertiary industries provide services. In Nigeria, industry is concentrated around Lagos, Port Harcourt, Kano and Kaduna, and faces problems of power, infrastructure and imported inputs.",
  [{"q":"Cement factories in Nigeria are located near limestone because of…","o":["market","raw materials","labour","capital"],"a":1,"e":"Limestone is the main raw material, so plants locate near deposits."}]],
 ["Environmental Hazards & Conservation", ["hazard","erosion","desertification","flood","pollution","conservation"],
  "Environmental hazards include soil erosion, desertification, flooding, drought and pollution. Desertification advances where vegetation is cleared, overgrazing occurs and the climate dries. Conservation practices are afforestation, controlled grazing, terracing, waste recycling and pollution control, which protect resources for future generations.",
  [{"q":"The major cause of desertification in the Sahel is…","o":["industrialisation","overgrazing and deforestation","tourism","ice melting"],"a":1,"e":"Removing vegetation cover exposes soil to wind and drought."}]
],
"Commerce": [
 ["Insurance", ["insurance","premium","policy","risk","underwriting","indemnity"],
  "Insurance protects against risk: many pay small premiums so the few who suffer loss are compensated. Key principles are insurable interest, utmost good faith, indemnity and subrogation. Types include fire, marine, life, motor, accident and burglary insurance. The insurer issues a policy; a claim must be supported by proof of loss.",
  [{"q":"The sum a policyholder pays for insurance cover is the…","o":["claim","premium","policy","commission"],"a":1,"e":"The premium is the fee paid for the insurance policy."},
   {"q":"Which principle requires the insured to have a real interest in the subject of the insurance?","o":["indemnity","utmost good faith","insurable interest","subrogation"],"a":2,"e":"You can only insure something whose loss would harm you."}]],
 ["Stock Exchange & Securities", ["stock","shares","securities","broker","dividend","capital market"],
  "The stock exchange is the market where shares, stocks and bonds are bought and sold, forming the capital market. Shares raise capital for companies; holders receive dividends. A broker deals on behalf of clients. Trading is regulated by the Securities and Exchange Commission (SEC) in Nigeria. Prices move with demand and supply.",
  [{"q":"The reward of a shareholder in a company is a…","o":["salary","dividend","interest","commission"],"a":1,"e":"Shareholders earn dividends from profits."}]],
 ["Transport & Communication", ["transport","communication","warehouse","freight","logistics","postal"],
  "Transport moves goods and people by road, rail, water, air and pipeline; communication carries information via post, telephone, internet and broadcasting. Efficient transport and communication lower costs, widen markets and speed business decisions. Warehouses store goods before distribution and are sited near markets or ports.",
  [{"q":"The cheapest means of transporting heavy bulky goods over long distances is usually…","o":["air","road","water","pipeline"],"a":2,"e":"Water transport carries heavy cargo cheapest, though it is slow."}]],
 ["International Trade & Finance", ["export","import","document","letter of credit","bill of lading","exchange"],
  "International trade brings in goods a country cannot produce cheaply and earns foreign exchange from exports. Documents include the proforma invoice, bill of lading, bill of exchange, certificate of origin and letter of credit, which assures exporters of payment. Balance of payments records all transactions with the rest of the world.",
  [{"q":"Which document is a written order of payment by the importer's bank?","o":["bill of lading","letter of credit","certificate of origin","proforma invoice"],"a":1,"e":"A letter of credit guarantees payment to the exporter through banks."}]],
 ["Business Units", ["sole proprietorship","partnership","limited liability","company","cooperative","public corporation"],
  "Business units are sole proprietorship (one owner, unlimited liability), partnership (2–20 owners sharing profit and liability), registered companies (limited liability, separate legal personality), cooperatives (member-owned) and public corporations (government-owned). Each differs in capital, control, continuity and liability, which is exactly what examiners test.",
  [{"q":"Which business unit has limited liability and a separate legal personality?","o":["sole proprietorship","partnership","registered company","informal trader"],"a":2,"e":"A registered company is a legal person distinct from its owners."}]],
 ["Business Finance & Accounting", ["capital","loan","overdraft","assets","liabilities","balance sheet"],
  "Business finance sources are personal savings, retained profit, loans, overdrafts, trade credit, hire purchase and shares. A balance sheet shows assets (what the business owns) and liabilities (what it owes); assets minus liabilities equals capital. Working capital is current assets minus current liabilities — the funds for day-to-day running.",
  [{"q":"Working capital equals…","o":["total assets","current assets minus current liabilities","fixed assets","capital plus loan"],"a":1,"e":"Working capital funds daily operations: current assets less current liabilities."}]
],
"Computer Studies": [
 ["Word Processing", ["word","document","format","font","spelling","print"],
  "Word processors (Microsoft Word, Google Docs) create, edit, format and print text documents. Features include fonts and sizes, alignment, bullet lists, tables, images, headers and footers, spell check, mail merge and print preview. Use Save As to keep older versions, and follow the file extension (.docx) conventions. Two Ss in processor: it processes words.",
  [{"q":"Which of these is word-processing software?","o":["Microsoft Excel","Microsoft Word","PowerPoint","Photoshop"],"a":1,"e":"Word is the classic word processor; Excel is a spreadsheet."}]],
 ["Spreadsheets", ["spreadsheet","cell","formula","function","chart","SUM"],
  "A spreadsheet is a grid of rows and columns; each cell holds a value or formula. Formulas begin with = and use cell references (=A2+B2); functions include SUM, AVERAGE, MAX, MIN and IF. Charts (bar, line, pie) visualise data, and absolute references ($A$1) keep a cell fixed when copying formulas.",
  [{"q":"A formula in a spreadsheet always begins with…","o":["a number","the = sign","a space","a letter"],"a":1,"e":"Formulas start with =, e.g. =SUM(A1:A5)."},
   {"q":"To add the values in cells A1 to A5, you use…","o":["=ADD(A1:A5)","=SUM(A1:A5)","=TOTAL(A1;A5)","A1:A5+"],"a":1,"e":"SUM is the function for adding a range of cells."}]],
 ["Database Concepts", ["database","table","record","field","query","primary key"],
  "A database is an organised collection of related data. Tables store records (rows) and fields (columns); a primary key uniquely identifies each record; a query selects and sorts records against conditions (WHERE). A Database Management System (DBMS) like Microsoft Access lets users create tables, forms and reports, and prevents redundancy and inconsistency.",
  [{"q":"A single row of data in a database table is called a…","o":["field","record","query","form"],"a":1,"e":"Each row is a record; each column is a field."}]],
 ["The Internet & Networks", ["internet","network","browser","URL","server","protocol"],
  "The Internet is a global network of networks; the World Wide Web is the interlinked document system on it, viewed in a browser. A URL addresses a resource; HTTP/HTTPS carry web pages; email, FTP and VoIP are other Internet services. Networks share resources using LAN (local area) and WAN (wide area) topologies — star, bus and ring.",
  [{"q":"The software used to view web pages is a…","o":["browser","server","protocol","router"],"a":0,"e":"Browsers (Chrome, Edge, Firefox) render pages from the Web."},
   {"q":"A network confined to one building is a…","o":["WAN","LAN","MAN","PAN only"],"a":1,"e":"LAN = Local Area Network, e.g. a school computer lab."}]],
 ["Programming Basics", ["programming","algorithm","flowchart","variable","loop","pseudo-code"],
  "Programming gives a computer instructions. An algorithm is a step-by-step solution; flowcharts use symbols (oval start/stop, rectangle process, diamond decision). Variables store values; loops repeat statements; conditions (IF) choose paths; and programs are written in languages such as Python and BASIC. Bugs are syntax or logic errors found by testing.",
  [{"q":"In a flowchart, a decision is represented by a…","o":["rectangle","diamond","oval","arrow"],"a":1,"e":"Decision diamonds branch to yes/no paths."},
   {"q":"Which of these is a programming language?","o":["HTML only","Python","HTTP","DOCX"],"a":1,"e":"Python is a high-level programming language."}]],
 ["Data Security & Ethics", ["security","password","virus","backup","encryption","ethics"],
  "Data security protects information from loss and theft: strong passwords, access rights, encryption and regular backups. Computer viruses and malware spread through files and downloads; antivirus software and updates defend systems. Ethics covers honest use of computers — respecting copyright, privacy and netiquette — and computer misuse laws punish hacking and fraud.",
  [{"q":"The best defence against losing important files is…","o":["deleting old files","regular backups","sharing passwords","disabling updates"],"a":1,"e":"Backups restore data after loss, damage or attack."}]
],
"Civic Education": [
 ["Citizenship & National Identity", ["citizen","rights","duty","nationalism","identity","patriotism"],
  "A citizen is a legally recognised member of a state — by birth, registration or naturalisation — with rights (life, freedom, education) and duties (obeying laws, paying taxes, defending the nation). National identity is built on shared symbols, history and values; patriotism means loyalty and service to the country, shown by lawful conduct and participation.",
  [{"q":"Citizenship acquired by a foreigner who qualifies after living in a country is by…","o":["birth","registration","naturalisation","inheritance"],"a":2,"e":"Naturalisation grants citizenship to qualified foreigners."}]],
 ["Rights, Duties & Obligations", ["rights","freedom","duty","responsibility","law","education"],
  "Fundamental human rights include the right to life, dignity, personal liberty, fair hearing, privacy and freedom of expression, movement and association. Duties and obligations are obeying laws, paying taxes, protecting public property, voting and defending the country. Rights and duties are two sides of citizenship: my rights impose duties on others and vice versa.",
  [{"q":"Which of these is a civic obligation?","o":["freedom of expression","paying taxes","right to life","freedom of movement"],"a":1,"e":"Paying taxes is a duty of citizens; the others are rights."}]],
 ["Drug Abuse & Substance Use", ["drug","abuse","substance","addiction","rehabilitation","consequence"],
  "Drug abuse is the harmful use of drugs without medical need: cocaine, heroin, tramadol, cannabis and even misuse of prescribed medicines. It harms health (organ damage, addiction, mental illness), family and society, and fuels crime, cultism and road accidents. Prevention includes education, counselling, hobbies and positive peer groups; treatment includes rehabilitation and support services.",
  [{"q":"Which of these is a social consequence of drug abuse?","o":["better concentration","involvement in crime","stronger health","higher income"],"a":1,"e":"Drug abuse links to crime, cultism and broken relationships."}]],
 ["Human Trafficking", ["trafficking","exploitation","forced labour","smuggling","victim","prosecution"],
  "Human trafficking is the recruitment, transport or harbouring of persons by force, deception or abuse of power for exploitation — forced labour, prostitution, begging or organ removal. It violates human dignity and is a crime under Nigerian law. Prevention requires awareness, education, strong enforcement and support for victims; report suspicious cases to NAPTIP.",
  [{"q":"The agency in Nigeria that fights human trafficking is…","o":["EFCC","NAPTIP","ICPC","NCDC"],"a":1,"e":"NAPTIP handles trafficking in persons."}]],
 ["Anti-Corruption Agencies", ["corruption","EFCC","ICPC","bribery","accountability","whistle"],
  "Corruption is the abuse of public office for private gain — bribery, embezzlement, fraud and nepotism. Nigeria's anti-corruption agencies include the EFCC (economic and financial crimes), the ICPC (public service corruption) and the Code of Conduct Bureau. Citizens fight corruption by refusing and reporting bribes, demanding accountability and practising integrity.",
  [{"q":"The EFCC investigates primarily…","o":["traffic offences","economic and financial crimes","examination fraud only","tax evasion only"],"a":1,"e":"EFCC tackles economic and financial crimes, including fraud and money laundering."}]],
 ["Responsible Citizenship & Leadership", ["leadership","integrity","followership","service","example","mentor"],
  "Leadership is the ability to influence others toward good goals; good leaders show integrity, accountability, empathy and self-control. Followership is also civic: supporting lawful leadership, giving constructive feedback and refusing to follow bad orders. Society improves when citizens lead by example at home, school and work — mentoring juniors and serving communities.",
  [{"q":"The most important quality of a good leader is…","o":["wealth","integrity","popularity","strength"],"a":1,"e":"Integrity — honesty and consistency — underpins trust and good leadership."}]
]
};
