# -*- coding: utf-8 -*-
"""Build quiz/mater_data.js (served, lazy, SW-cached) = MATER data + UI module.
Merges quiz/_mater_list.json (SS1/SS3, from mater_gen.py),
quiz/_mater_list_ss2.json (SS2, from the existing PDFs) and
quiz/_mater_list_t2.json (SS1/SS2/SS3 Second Term, from mater_gen2.py).
Idempotent."""
import os, json

HERE = os.path.dirname(os.path.abspath(__file__))


def load(p):
    return json.load(open(p, encoding="utf-8"))


a = load(os.path.join(HERE, "_mater_list.json"))
b = load(os.path.join(HERE, "_mater_list_ss2.json"))
c = load(os.path.join(HERE, "_mater_list_t2.json"))
entries = a + b + c
assert len(entries) == 60, "expected 60 entries, got %d" % len(entries)
assert sorted(e["cls"] for e in entries) == ["SS1"] * 20 + ["SS2"] * 20 + ["SS3"] * 20
t1 = sum(1 for e in entries if "First Term" in e["weeks"])
t2 = sum(1 for e in entries if "Second Term" in e["weeks"])
assert t1 == 30 and t2 == 30, (t1, t2)
for e in entries:
    assert e["file"] and e["subj"], e
    assert os.path.exists(os.path.join(HERE, "..", "mater-notes", e["file"])), e["file"]

order = {"SS1": 0, "SS2": 1, "SS3": 2}
entries.sort(key=lambda e: (order[e["cls"]], "Second Term" in e["weeks"], e["subj"]))
data = json.dumps(entries, ensure_ascii=False, separators=(",", ":"))

app = open(os.path.join(HERE, "_mater_app.js"), encoding="utf-8").read()
out = ("/* v22.0 — Mater Notes library data + UI (generated by quiz/_mater_build.py; "
       "MATER entries mirror the PDFs in mater-notes/) */\n"
       "var MATER=JSON.parse(" + json.dumps(data) + ");\n" + app)
open(os.path.join(HERE, "mater_data.js"), "w", encoding="utf-8").write(out)
print("mater_data.js written: %d entries (%d First, %d Second), %d bytes" % (len(entries), t1, t2, len(out)))
