# -*- coding: utf-8 -*-
"""Build quiz/mater_data.js (served, lazy, SW-cached) = MATER data + UI module.
Merges quiz/_mater_list.json (SS1/SS3, from mater_gen.py) with
quiz/_mater_list_ss2.json (SS2, from the existing PDFs). Idempotent."""
import os, json, glob

HERE = os.path.dirname(os.path.abspath(__file__))


def load(p):
    return json.load(open(p, encoding="utf-8"))


a = load(os.path.join(HERE, "_mater_list.json"))
b = load(os.path.join(HERE, "_mater_list_ss2.json"))
entries = a + b
assert len(entries) == 30, "expected 30 entries, got %d" % len(entries)
assert sorted(e["cls"] for e in entries) == ["SS1"] * 10 + ["SS2"] * 10 + ["SS3"] * 10
for e in entries:
    assert e["file"] and e["subj"], e
    assert os.path.exists(os.path.join(HERE, "..", "mater-notes", e["file"])), e["file"]

order = {"SS1": 0, "SS2": 1, "SS3": 2}
entries.sort(key=lambda e: (order[e["cls"]], e["subj"]))
data = json.dumps(entries, ensure_ascii=False, separators=(",", ":"))

app = open(os.path.join(HERE, "_mater_app.js"), encoding="utf-8").read()
out = ("/* v21.0 — Mater Notes library data + UI (generated by quiz/_mater_build.py; "
       "MATER entries mirror the PDFs in mater-notes/) */\n"
       "var MATER=JSON.parse(" + json.dumps(data) + ");\n" + app)
open(os.path.join(HERE, "mater_data.js"), "w", encoding="utf-8").write(out)
print("mater_data.js written: %d entries, %d bytes" % (len(entries), len(out)))
