# -*- coding: utf-8 -*-
"""Build quiz/notes_data.js (lazy, SW-cached, boot-safe) = NERDC lesson-notes
library data: PRIM (primary curriculum/scheme map) + NOTES (full 8-part lesson
notes, seeded for Basic 1 Mathematics across all three terms). Idempotent."""
import os, json, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from n_pri import PRIM
from n_b1m_t1 import B1M_T1
from n_b1m_t2 import B1M_T2
from n_b1m_t3 import B1M_T3

NOTES = []
for term, block in ((1, B1M_T1), (2, B1M_T2), (3, B1M_T3)):
    for i, n in enumerate(block):
        week = i + 1
        assert week <= 10, ("week", week)
        if week == 10:
            assert "Revis" in n["topic"] or "Test" in n["topic"], n["topic"]
        for f in ("obj", "prev", "mat", "content", "ex", "act", "eval", "assign"):
            assert n.get(f), (term, week, f)
        assert n["topic"] and n["obj"] and len(n["eval"]) >= 4
        NOTES.append({"lvl": "P", "cls": "B1", "subj": "Mathematics", "term": term,
                      "week": week, "topic": n["topic"], "obj": n["obj"], "prev": n["prev"],
                      "mat": n["mat"], "content": n["content"], "ex": n["ex"],
                      "act": n["act"], "eval": n["eval"], "assign": n["assign"]})
assert len(NOTES) == 30, len(NOTES)

# scheme cross-check: B1 Mathematics term x week 1-9 must equal note topics
def norm(t):
    import re as _re
    return _re.sub(r"[^a-z0-9]", "", t.lower().replace("\u2013", "-").replace("\u2014", "-"))

for term, block in ((0, B1M_T1), (1, B1M_T2), (2, B1M_T3)):
    scheme = PRIM["subjects"][0]["cls"]["B1"][term]
    for i, n in enumerate(block):
        first = norm(n["topic"].split(" ")[0])
        assert norm(scheme[i].split(" ")[0]) == first, (term, i, scheme[i], n["topic"])
        if i == 9:
            assert "revis" in norm(n["topic"]) or "test" in norm(n["topic"]), n["topic"]

primes = json.dumps(PRIM, ensure_ascii=False, separators=(",", ":"))
noted = json.dumps(NOTES, ensure_ascii=False, separators=(",", ":"))
out = ("/* v25.0 — NERDC lesson-notes library data (generated by quiz/_notes_build.py: "
       "PRIM curriculum/scheme map + NOTES full 8-part lesson notes) */\n"
       "var NOTES_META=" + json.dumps({"v": "v25.0", "seeded": len(NOTES),
                                        "label": "NERDC-aligned lesson notes",
                                        "primarySubjects": len(PRIM["subjects"]),
                                        "classes": PRIM["classes"]}, ensure_ascii=False) + ";\n"
       "var PRIM=JSON.parse(" + json.dumps(primes) + ");\n"
       "var NOTES=JSON.parse(" + json.dumps(noted) + ");\n")
open(os.path.join(HERE, "notes_data.js"), "w", encoding="utf-8").write(out)
print("notes_data.js written: %d notes, %d primary subjects, %d bytes" %
      (len(NOTES), len(PRIM["subjects"]), len(out)))
