# -*- coding: utf-8 -*-
"""Biology: 100 questions per level from a fact bank (4 forms per entry)."""
from engine import G

SUBJECT = "Biology"

FACTS = {
1: [
 ("cell", "the basic structural and functional unit of all living things", "cell biology"),
 ("nucleus", "the organelle that controls the activities of the cell and contains genetic material", "cell biology"),
 ("cytoplasm", "the jelly-like substance in which the organelles of a cell are suspended", "cell biology"),
 ("cell membrane", "the thin boundary that controls what enters and leaves a cell", "cell biology"),
 ("mitochondrion", "the organelle that releases energy during respiration", "cell biology"),
 ("chloroplast", "the organelle that contains chlorophyll and carries out photosynthesis", "cell biology"),
 ("vacuole", "a fluid-filled sac in a cell that stores substances", "cell biology"),
 ("cell wall", "the rigid outer layer of a plant cell that gives it support", "cell biology"),
 ("chlorophyll", "the green pigment that traps light energy for photosynthesis", "plant biology"),
 ("photosynthesis", "the process by which green plants make food using sunlight, carbon dioxide and water", "plant biology"),
 ("respiration", "the process by which living things release energy from food", "plant biology"),
 ("transpiration", "the loss of water vapour from the leaves of a plant", "plant biology"),
 ("osmosis", "the movement of water from a region of high water potential across a semi-permeable membrane", "plant biology"),
 ("diffusion", "the movement of molecules from a region of higher concentration to a region of lower concentration", "plant biology"),
 ("habitat", "the natural home of an organism", "ecology"),
 ("population", "all the members of one species living in a particular area", "ecology"),
 ("community", "all the populations of different species living together in a habitat", "ecology"),
 ("ecosystem", "a community of living organisms interacting with their non-living environment", "ecology"),
 ("biotic factor", "a living factor that affects an organism, such as a predator", "ecology"),
 ("abiotic factor", "a non-living factor that affects an organism, such as sunlight", "ecology"),
 ("producer", "a green plant that makes its own food by photosynthesis", "ecology"),
 ("consumer", "an organism that feeds on other organisms", "ecology"),
 ("decomposer", "an organism that breaks down dead organic matter", "ecology"),
 ("food chain", "the sequence of feeding relationships among organisms", "ecology"),
 ("food web", "the network of interconnected food chains in an ecosystem", "ecology"),
 ("mammal", "a warm-blooded animal that feeds its young on milk", "classification"),
 ("reptile", "a cold-blooded animal with a scaly skin that lays eggs on land", "classification"),
 ("amphibian", "a cold-blooded animal that lives both in water and on land", "classification"),
 ("predator", "an animal that hunts and kills other animals for food", "ecology"),
 ("prey", "an animal that is hunted and eaten by another animal", "ecology"),
 ("vertebrate", "an animal that has a backbone", "classification"),
 ("invertebrate", "an animal that has no backbone", "classification"),
],
2: [
 ("enzymes", "biological catalysts that speed up chemical reactions in living things", "biochemistry"),
 ("hormones", "chemical messengers secreted by endocrine glands into the blood", "physiology"),
 ("insulin", "the hormone that lowers the level of glucose in the blood", "physiology"),
 ("adrenaline", "the hormone that prepares the body for emergency action", "physiology"),
 ("haemoglobin", "the red pigment in red blood cells that carries oxygen", "physiology"),
 ("artery", "a blood vessel that carries blood away from the heart", "physiology"),
 ("vein", "a blood vessel that carries blood towards the heart", "physiology"),
 ("capillary", "the smallest blood vessel where exchange of materials takes place", "physiology"),
 ("alveolus", "one of the tiny air sacs in the lungs where gaseous exchange occurs", "physiology"),
 ("nephron", "the structural and functional unit of the kidney", "physiology"),
 ("neuron", "the structural and functional unit of the nervous system", "physiology"),
 ("diaphragm", "the muscular sheet below the lungs that aids breathing", "physiology"),
 ("red blood cell", "the blood cell that transports oxygen round the body", "physiology"),
 ("white blood cell", "the blood cell that defends the body against infection", "physiology"),
 ("platelets", "the blood cells that help the blood to clot", "physiology"),
 ("ovulation", "the release of a mature egg from the ovary", "reproduction"),
 ("fertilisation", "the fusion of the male gamete with the female gamete", "reproduction"),
 ("placenta", "the organ that nourishes the developing foetus in the womb", "reproduction"),
 ("gestation", "the period of development of a baby inside the womb", "reproduction"),
 ("menstruation", "the shedding of the lining of the uterus when fertilisation does not occur", "reproduction"),
 ("pollination", "the transfer of pollen grains from the anther to the stigma", "reproduction"),
 ("germination", "the growth of a seed into a young plant", "reproduction"),
 ("digestion", "the breaking down of large food molecules into absorbable forms", "physiology"),
 ("peristalsis", "the wave-like muscular contractions that push food along the alimentary canal", "physiology"),
 ("malaria", "a disease caused by Plasmodium and transmitted by the female Anopheles mosquito", "disease"),
 ("typhoid", "a disease caused by Salmonella typhi and transmitted through contaminated food and water", "disease"),
 ("vaccination", "the injection of a weakened or dead pathogen to stimulate immunity", "disease"),
 ("vector", "an organism that transmits a disease from one host to another", "disease"),
 ("antibody", "a protein produced by the body to neutralise a pathogen", "disease"),
 ("pathogen", "a micro-organism that causes disease", "disease"),
 ("immunity", "the resistance of the body to infection by a disease", "disease"),
 ("heredity", "the passing of characteristics from parents to offspring", "genetics"),
 ("variation", "the differences that exist between individuals of the same species", "genetics"),
 ("asexual reproduction", "reproduction that involves only one parent and produces identical offspring", "reproduction"),
 ("sexual reproduction", "reproduction that involves the fusion of male and female gametes", "reproduction"),
],
3: [
 ("mitosis", "cell division that produces two identical daughter cells for growth and repair", "genetics"),
 ("meiosis", "cell division that produces four haploid cells for sexual reproduction", "genetics"),
 ("chromosome", "the thread-like structure in the nucleus that carries genes", "genetics"),
 ("gene", "the unit of heredity that controls a particular characteristic", "genetics"),
 ("allele", "one of the alternative forms of a gene", "genetics"),
 ("dominant allele", "the allele that masks the effect of its partner in a heterozygous organism", "genetics"),
 ("recessive allele", "the allele whose effect is masked in the presence of a dominant allele", "genetics"),
 ("genotype", "the genetic make-up of an organism", "genetics"),
 ("phenotype", "the observable characteristics of an organism", "genetics"),
 ("homozygous", "having two identical alleles for a particular gene", "genetics"),
 ("heterozygous", "having two different alleles for a particular gene", "genetics"),
 ("mutation", "a sudden change in the structure of a gene or chromosome", "genetics"),
 ("natural selection", "the survival of organisms best adapted to their environment", "evolution"),
 ("adaptation", "a feature that enables an organism to survive in its environment", "evolution"),
 ("evolution", "the gradual change in living things over many generations", "evolution"),
 ("dihybrid cross", "a cross involving two pairs of contrasting characteristics", "genetics"),
 ("haploid", "a cell that contains a single set of chromosomes", "genetics"),
 ("diploid", "a cell that contains two sets of chromosomes", "genetics"),
 ("excretion", "the removal of metabolic waste products from the body", "physiology"),
 ("kidney", "the organ that filters waste products from the blood to form urine", "physiology"),
 ("liver", "the organ that produces bile and regulates blood sugar", "physiology"),
 ("homeostasis", "the maintenance of a constant internal environment in the body", "physiology"),
 ("osmoregulation", "the control of the water and salt content of the body", "physiology"),
 ("coordination", "the working together of the nervous and hormonal systems to control the body", "physiology"),
 ("cerebellum", "the part of the brain that controls balance and muscle coordination", "physiology"),
 ("medulla oblongata", "the part of the brain that controls breathing, heartbeat and other involuntary actions", "physiology"),
 ("reflex action", "a rapid, automatic, involuntary response to a stimulus", "physiology"),
 ("symbiosis", "a close, long-term relationship between two different species", "ecology"),
 ("parasitism", "a relationship in which one organism benefits at the expense of another", "ecology"),
 ("mutualism", "a relationship in which both organisms benefit", "ecology"),
 ("commensalism", "a relationship in which one organism benefits and the other is neither helped nor harmed", "ecology"),
 ("succession", "the gradual change in the species composition of a community over time", "ecology"),
 ("nitrogen cycle", "the circulation of nitrogen between living organisms and the environment", "ecology"),
 ("anaerobic respiration", "respiration that occurs without oxygen, producing lactic acid or ethanol", "biochemistry"),
],
}

def generate(level, seed=1, target=100, blocked=None):
    g = G(SUBJECT, seed, blocked)
    g.fill_facts(FACTS[level], target, use_cap=4)
    g.shuffle_qs()
    return g.qs
