# -*- coding: utf-8 -*-
"""Literature in English: 100 questions per level from a fact bank."""
from engine import G

SUBJECT = "Literature in English"

FACTS = {
1: [
 ("prose", "literary works written in ordinary language, such as novels and short stories", "genres"),
 ("poetry", "literature written in verse, often with rhyme and rhythm", "genres"),
 ("drama", "literature written to be performed by actors on a stage", "genres"),
 ("novel", "a long fictional prose story", "prose"),
 ("short story", "a brief fictional prose narrative", "prose"),
 ("plot", "the sequence of events in a literary work", "prose"),
 ("theme", "the central idea or message of a literary work", "prose"),
 ("character", "a person or animal that takes part in the events of a story", "prose"),
 ("protagonist", "the main character or hero of a literary work", "prose"),
 ("antagonist", "the character who opposes the main character", "prose"),
 ("narrator", "the person who tells the story", "prose"),
 ("setting", "the time and place in which the events of a story take place", "prose"),
 ("stanza", "a group of lines in a poem", "poetry"),
 ("verse", "a single line of poetry", "poetry"),
 ("rhyme", "the correspondence of sounds at the ends of lines of verse", "poetry"),
 ("rhythm", "the beat or flow of sounds in a poem", "poetry"),
 ("simile", "a comparison of two unlike things using 'like' or 'as'", "figures of speech"),
 ("metaphor", "a direct comparison of two unlike things without 'like' or 'as'", "figures of speech"),
 ("personification", "the giving of human qualities to non-human things", "figures of speech"),
 ("hyperbole", "deliberate exaggeration used for effect", "figures of speech"),
 ("irony", "the use of words to mean the opposite of what is literally said", "figures of speech"),
 ("satire", "the use of humour or ridicule to expose vices and folly", "figures of speech"),
 ("dialogue", "the conversation between characters in a work", "drama"),
 ("act", "a major division of a play", "drama"),
 ("scene", "a subdivision of an act in a play", "drama"),
 ("tragedy", "a serious play that ends in the downfall or death of the main character", "genres"),
 ("comedy", "a light play that amuses and usually ends happily", "genres"),
 ("fiction", "literary works created from the imagination", "genres"),
 ("biography", "the story of a person's life written by another person", "prose"),
 ("autobiography", "the story of a person's life written by that person", "prose"),
 ("folktale", "a traditional story handed down among a people", "prose"),
 ("subject matter", "what a literary work is about", "literary terms"),
],
2: [
 ("allusion", "an indirect reference to a well-known person, event or work", "figures of speech"),
 ("allegory", "a story in which characters and events have deeper symbolic meanings", "figures of speech"),
 ("euphemism", "a mild expression used in place of a harsh one", "figures of speech"),
 ("onomatopoeia", "the use of words that imitate the sounds they describe", "figures of speech"),
 ("alliteration", "the repetition of the same initial consonant sound in close words", "figures of speech"),
 ("assonance", "the repetition of vowel sounds in nearby words", "figures of speech"),
 ("imagery", "the use of vivid language that appeals to the senses", "figures of speech"),
 ("symbolism", "the use of symbols to represent deeper ideas", "figures of speech"),
 ("foreshadowing", "a hint of events that will occur later in a story", "prose"),
 ("flashback", "a scene that returns to an earlier time in the story", "prose"),
 ("climax", "the point of greatest tension in a story", "prose"),
 ("conflict", "the struggle between opposing forces in a story", "prose"),
 ("resolution", "the part of the story where the conflict is resolved", "prose"),
 ("exposition", "the part of a story that introduces the characters and setting", "prose"),
 ("point of view", "the perspective from which a story is told", "prose"),
 ("first-person narration", "a story told by a narrator who uses 'I'", "prose"),
 ("third-person narration", "a story told by a narrator who is not a character", "prose"),
 ("round character", "a fully developed character with a complex personality", "prose"),
 ("flat character", "a simple, one-dimensional character", "prose"),
 ("foil", "a character whose qualities contrast with those of another to highlight them", "prose"),
 ("sonnet", "a poem of fourteen lines", "poetry"),
 ("ode", "a lyric poem that praises a person or thing", "poetry"),
 ("ballad", "a narrative poem meant to be sung", "poetry"),
 ("elegy", "a poem written in mourning for the dead", "poetry"),
 ("refrain", "the repeated line or lines in a poem or song", "poetry"),
 ("rhyme scheme", "the pattern of rhymes at the ends of lines of a poem", "poetry"),
 ("monologue", "a long speech by one character", "drama"),
 ("soliloquy", "a speech in which a character reveals his thoughts while alone on stage", "drama"),
 ("aside", "a remark made by a character that the other characters do not hear", "drama"),
 ("dramatic irony", "a situation in which the audience knows more than the characters", "drama"),
 ("stage direction", "the author's instruction on how a play should be performed", "drama"),
 ("tragic hero", "a noble character whose downfall is caused by a fatal flaw", "drama"),
],
3: [
 ("Chinua Achebe", "the Nigerian novelist who wrote 'Things Fall Apart'", "authors and works"),
 ("Wole Soyinka", "the Nigerian Nobel laureate who wrote 'The Lion and the Jewel'", "authors and works"),
 ("Christopher Okigbo", "the Nigerian poet who wrote 'Heavensgate'", "authors and works"),
 ("J.P. Clark", "the Nigerian poet who wrote 'Casualties'", "authors and works"),
 ("Gabriel Okara", "the Nigerian poet who wrote 'Piano and Drums'", "authors and works"),
 ("Niyi Osundare", "the Nigerian poet who wrote 'The Leader and the Led'", "authors and works"),
 ("Flora Nwapa", "the Nigerian female novelist who wrote 'Efuru'", "authors and works"),
 ("Amos Tutuola", "the Nigerian novelist who wrote 'The Palm-Wine Drinkard'", "authors and works"),
 ("Cyprian Ekwensi", "the Nigerian novelist who wrote 'Jagua Nana'", "authors and works"),
 ("Elechi Amadi", "the Nigerian novelist who wrote 'The Concubine'", "authors and works"),
 ("Ngugi wa Thiong'o", "the Kenyan novelist who wrote 'A Grain of Wheat'", "authors and works"),
 ("George Orwell", "the English novelist who wrote 'Animal Farm'", "authors and works"),
 ("William Shakespeare", "the Elizabethan playwright who wrote 'Romeo and Juliet'", "authors and works"),
 ("Okonkwo", "the tragic hero of Achebe's 'Things Fall Apart'", "characters"),
 ("Baroka", "the crafty Bale of Ilujinle in Soyinka's 'The Lion and the Jewel'", "characters"),
 ("Lakunle", "the progressive schoolteacher in 'The Lion and the Jewel'", "characters"),
 ("Sidi", "the beautiful village maiden in 'The Lion and the Jewel'", "characters"),
 ("Umuofia", "the fictional Igbo village in which 'Things Fall Apart' is set", "settings"),
 ("Ilujinle", "the village in which 'The Lion and the Jewel' is set", "settings"),
 ("hamartia", "the fatal flaw that brings about the downfall of a tragic hero", "literary terms"),
 ("catharsis", "the purging of pity and fear experienced at the end of a tragedy", "literary terms"),
 ("motif", "a recurring image, idea or symbol in a work", "literary terms"),
 ("denouement", "the final outcome of the plot after the climax", "literary terms"),
 ("suspense", "the state of anxious uncertainty about what will happen next", "literary terms"),
 ("sarcasm", "bitter or cutting remarks used to mock", "figures of speech"),
 ("litotes", "understatement made by denying the opposite", "figures of speech"),
 ("oxymoron", "the combination of two contradictory terms", "figures of speech"),
 ("metonymy", "the substitution of one thing for another closely associated with it", "figures of speech"),
 ("paradox", "a statement that seems contradictory but contains truth", "figures of speech"),
 ("rhetorical question", "a question asked for effect with no answer expected", "figures of speech"),
 ("farce", "a light comedy with exaggerated, improbable situations", "drama"),
 ("melodrama", "a drama with exaggerated emotion and simple characters", "drama"),
 ("tragicomedy", "a drama that combines elements of both tragedy and comedy", "drama"),
 ("narrative poem", "a poem that tells a story", "poetry"),
 ("dialect", "the form of a language spoken in a particular region", "literary terms"),
],
}

def generate(level, seed=1, target=100, blocked=None):
    g = G(SUBJECT, seed, blocked)
    g.fill_facts(FACTS[level], target, use_cap=4)
    g.shuffle_qs()
    return g.qs
