# -*- coding: utf-8 -*-
"""Agricultural Science: 100 questions per level from a fact bank."""
from engine import G

SUBJECT = "Agricultural Science"

FACTS = {
1: [
 ("agriculture", "the science and art of cultivating the soil, growing crops and rearing animals", "agriculture basics"),
 ("crop", "a plant that is grown by farmers for food or other uses", "crops"),
 ("livestock", "animals kept on a farm for production purposes", "livestock"),
 ("soil", "the loose top layer of the earth's surface in which plants grow", "soil science"),
 ("loam", "the best soil for crop production, containing sand, silt and clay in balanced proportions", "soil science"),
 ("humus", "the dark, decayed organic matter in soil", "soil science"),
 ("fertiliser", "a substance added to soil to improve the supply of plant nutrients", "soil science"),
 ("manure", "the decayed animal waste or plant matter used to improve the soil", "soil science"),
 ("hoe", "a simple hand tool used for digging, weeding and loosening the soil", "farm tools"),
 ("cutlass", "a broad-bladed tool used for clearing bushes and cutting crops", "farm tools"),
 ("watering can", "a container used for watering seedlings and plants", "farm tools"),
 ("plough", "a farm implement used to turn and break up the soil before planting", "farm tools"),
 ("harrow", "a farm implement used to level and break clods after ploughing", "farm tools"),
 ("germination", "the process by which a seed begins to grow into a young plant", "crop production"),
 ("transplanting", "moving seedlings from the nursery bed to the main field", "crop production"),
 ("weeding", "the removal of unwanted plants from a cultivated area", "crop production"),
 ("harvesting", "the gathering of mature crops from the field", "crop production"),
 ("nursery", "a place where young plants (seedlings) are raised before transplanting", "crop production"),
 ("crop rotation", "the growing of different crops in succession on the same piece of land", "crop production"),
 ("maize", "a cereal crop used for food and livestock feed", "crops"),
 ("yam", "a tuber crop that is a staple food in West Africa", "crops"),
 ("cassava", "a root crop grown for its starchy tubers", "crops"),
 ("cowpea", "a leguminous crop grown for its edible seeds", "crops"),
 ("groundnut", "a leguminous crop whose seeds are rich in oil and protein", "crops"),
 ("cattle", "ruminant animals kept for meat, milk and hides", "livestock"),
 ("goat", "a small ruminant kept for meat and milk", "livestock"),
 ("sheep", "a ruminant kept for meat, milk and wool", "livestock"),
 ("poultry", "domestic birds such as chickens and turkeys kept for meat and eggs", "livestock"),
 ("ruminant", "an animal with a four-chambered stomach that chews the cud", "livestock"),
 ("piggery", "the place where pigs are reared", "livestock"),
 ("poultry house", "a building designed for keeping birds", "livestock"),
 ("weed", "an unwanted plant that grows where it is not wanted", "crop production"),
 ("mulch", "a layer of dry plant material spread on the soil surface to conserve moisture", "crop production"),
 ("fodder", "the food given to farm animals", "livestock"),
 ("hay", "dried grass preserved as animal feed", "livestock"),
],
2: [
 ("land tenure", "the system by which land is owned, held and used", "agricultural economics"),
 ("communal land tenure", "a system in which land is owned and used by the whole community", "agricultural economics"),
 ("leasehold", "a system in which land is rented for a fixed period", "agricultural economics"),
 ("land mortgage", "the use of land as security for a loan", "agricultural economics"),
 ("irrigation", "the artificial application of water to farmland", "soil and water management"),
 ("drainage", "the removal of excess water from farmland", "soil and water management"),
 ("soil erosion", "the washing or blowing away of the top soil by water or wind", "soil and water management"),
 ("leaching", "the washing of dissolved nutrients down the soil profile by water", "soil and water management"),
 ("soil conservation", "all the methods used to protect the soil from erosion and loss of fertility", "soil and water management"),
 ("contour ploughing", "ploughing across the slope of a hill to reduce erosion", "soil and water management"),
 ("terracing", "the cutting of steps into a slope to reduce erosion", "soil and water management"),
 ("cover cropping", "the growing of crops mainly to protect the soil from erosion", "soil and water management"),
 ("green manure", "crops that are ploughed into the soil to improve its fertility", "soil and water management"),
 ("mixing cropping", "the cultivation of two or more crops on the same piece of land at the same time", "crop production"),
 ("monoculture", "the cultivation of only one crop on a piece of land", "crop production"),
 ("intercropping", "the growing of two or more crops alternately in rows on the same land", "crop production"),
 ("mixed farming", "the combination of crop production and animal rearing on the same farm", "agricultural economics"),
 ("nursery bed", "a small plot where seeds are raised before transplanting", "crop production"),
 ("thinning", "the removal of excess seedlings to give room for the remaining ones", "crop production"),
 ("supplying", "the replacement of dead seedlings in a field", "crop production"),
 ("grafting", "the joining of a scion of one plant onto the rootstock of another", "crop production"),
 ("budding", "the insertion of a bud of one plant into the stem of another", "crop production"),
 ("planting", "the placing of seeds or seedlings into the soil to grow", "crop production"),
 ("incubation", "the keeping of fertile eggs under suitable conditions for hatching", "animal production"),
 ("brooding", "the keeping of young chicks under controlled warmth", "animal production"),
 ("culling", "the removal of old, weak or unproductive animals from a herd", "animal production"),
 ("castration", "the removal of the testicles of a male farm animal", "animal production"),
 ("deworming", "the administration of drugs to remove internal parasites from animals", "animal production"),
 ("quarantine", "the isolation of sick animals to prevent the spread of disease", "animal production"),
 ("gestation period", "the period of pregnancy in a farm animal", "animal production"),
 ("fattening", "the feeding of animals for meat production", "animal production"),
 ("salting", "a method of preserving fish or meat with salt", "farm produce"),
 ("smoking", "a method of preserving fish or meat by drying it with smoke", "farm produce"),
 ("pasteurisation", "the heating of milk to kill harmful bacteria", "farm produce"),
 ("milling", "the grinding of grains such as maize into flour", "farm produce"),
],
3: [
 ("farm budgeting", "the estimate of income and expenditure of a farm", "agricultural economics"),
 ("farm records", "the written accounts of farm activities and transactions", "agricultural economics"),
 ("gross income", "the total value of all the produce of a farm", "agricultural economics"),
 ("net income", "the difference between the gross income and the total cost of production", "agricultural economics"),
 ("land fragmentation", "the division of farmland into small scattered plots", "agricultural economics"),
 ("agricultural extension", "the teaching of improved farming methods to farmers", "agricultural economics"),
 ("cooperative society", "a voluntary association of farmers who pool resources for mutual benefit", "agricultural economics"),
 ("agricultural credit", "the loan granted to farmers for farm operations", "agricultural economics"),
 ("marketing board", "an organisation that buys and sells farmers' produce in bulk", "agricultural economics"),
 ("agroforestry", "the combination of trees with crops and animals on the same land", "soil and water management"),
 ("shifting cultivation", "a system in which land is abandoned after a few years of cropping", "soil and water management"),
 ("bush fallowing", "leaving land uncropped for some years to regain fertility", "soil and water management"),
 ("alley cropping", "the growing of arable crops between rows of trees", "soil and water management"),
 ("windbreak", "a row of trees planted to reduce the force of the wind", "soil and water management"),
 ("selective breeding", "the mating of selected animals to improve their qualities", "animal breeding"),
 ("artificial insemination", "the introduction of semen into the female reproductive tract by artificial means", "animal breeding"),
 ("cross breeding", "the mating of animals of two different breeds", "animal breeding"),
 ("inbreeding", "the mating of closely related animals of the same breed", "animal breeding"),
 ("hybridisation", "the crossing of two different varieties to combine desirable traits", "crop breeding"),
 ("weaning", "the gradual removal of a young animal from its mother's milk", "animal production"),
 ("debeaking", "the trimming of the beaks of birds to prevent cannibalism", "animal production"),
 ("dipping", "the immersion of animals in a chemical solution to control ticks", "animal production"),
 ("rotational grazing", "the moving of animals from one paddock to another to allow pasture to regrow", "animal production"),
 ("stocking rate", "the number of animals kept per unit area of pasture", "animal production"),
 ("extension officer", "the government officer who teaches farmers improved methods", "agricultural economics"),
 ("fertiliser requirement", "the amount of fertiliser needed to maintain soil fertility", "soil science"),
 ("organic farming", "farming without the use of synthetic chemicals", "agriculture concepts"),
 ("intensive farming", "the use of modern inputs to obtain high yields from small land", "agriculture concepts"),
 ("extensive farming", "farming over a large area with little input per unit area", "agriculture concepts"),
 ("commercial farm", "a farm run mainly to make profit", "agriculture concepts"),
 ("subsistence farming", "farming carried out mainly to feed the farmer's family", "agriculture concepts"),
 ("farm mechanisation", "the use of machines and implements in farm work", "agriculture concepts"),
 ("pest", "an animal that damages crops or stored produce", "plant protection"),
 ("herbicide", "a chemical used to kill weeds", "plant protection"),
 ("pesticide", "a chemical used to kill pests", "plant protection"),
 ("disease", "a disorder that interferes with the normal function of a plant or animal", "plant protection"),
],
}

def generate(level, seed=1, target=100, blocked=None):
    g = G(SUBJECT, seed, blocked)
    g.fill_facts(FACTS[level], target, use_cap=4)
    g.shuffle_qs()
    return g.qs
