# -*- coding: utf-8 -*-
"""Government: 100 questions per level from a fact bank."""
from engine import G

SUBJECT = "Government"

FACTS = {
1: [
 ("state", "a politically organised community of people occupying a defined territory with a government", "basic concepts"),
 ("nation", "a group of people with a common culture, language and territory", "basic concepts"),
 ("government", "the institution through which a state is ruled and its affairs are managed", "basic concepts"),
 ("sovereignty", "the supreme power of a state to govern itself without external control", "basic concepts"),
 ("legitimacy", "the acceptance of a government by the people as lawful", "basic concepts"),
 ("constitution", "the body of rules and principles by which a state is governed", "constitution"),
 ("democracy", "government of the people, by the people and for the people", "systems of government"),
 ("monarchy", "a system of government in which a king or queen rules", "systems of government"),
 ("aristocracy", "a system of government in which a small privileged class rules", "systems of government"),
 ("oligarchy", "a system of government in which a small group of people rules", "systems of government"),
 ("dictatorship", "a system of government in which one person rules with absolute power", "systems of government"),
 ("republic", "a state in which power is held by the people and their elected representatives", "systems of government"),
 ("federal system", "a system in which power is shared between a central government and component states", "systems of government"),
 ("unitary system", "a system in which all governmental powers are concentrated in the central government", "systems of government"),
 ("presidential system", "a system in which the executive is elected separately from the legislature", "systems of government"),
 ("executive", "the arm of government responsible for implementing laws", "arms of government"),
 ("legislature", "the arm of government responsible for making laws", "arms of government"),
 ("judiciary", "the arm of government responsible for interpreting laws and settling disputes", "arms of government"),
 ("rule of law", "the principle that all persons and authorities are subject to the law", "rule of law"),
 ("separation of powers", "the allocation of governmental powers to the three arms so that each checks the others", "rule of law"),
 ("checks and balances", "the powers that enable each arm of government to limit the others", "rule of law"),
 ("electorate", "the body of persons entitled to vote in an election", "citizenship"),
 ("suffrage", "the right of citizens to vote in elections", "citizenship"),
 ("franchise", "the right to vote in political elections", "citizenship"),
 ("election", "the process by which citizens choose their representatives", "elections"),
 ("political party", "an organised group that seeks to capture political power and control government", "parties and groups"),
 ("pressure group", "an organised group that influences government policy without seeking to govern", "parties and groups"),
 ("public opinion", "the collective views of the citizens on public issues", "parties and groups"),
 ("civil service", "the body of officials that implements government policies", "public administration"),
 ("local government", "the third tier of government that administers a local area", "public administration"),
 ("independence", "the state of being free from foreign control", "Nigerian government"),
 ("nationalism", "the strong devotion to and support for the interests of one's nation", "Nigerian government"),
 ("self-determination", "the right of a people to decide their own political future", "Nigerian government"),
 ("pan-africanism", "the movement for the unity and liberation of African peoples", "international relations"),
],
2: [
 ("bicameral legislature", "a legislature consisting of two chambers or houses", "legislature"),
 ("unicameral legislature", "a legislature consisting of only one chamber", "legislature"),
 ("impeachment", "the process of removing a public officer from office for misconduct", "legislature"),
 ("vote of no confidence", "a parliamentary vote showing that members no longer trust the executive", "legislature"),
 ("bill", "a proposed law presented to the legislature for consideration", "legislature"),
 ("act of parliament", "a bill that has been passed by the legislature and received assent", "legislature"),
 ("assent", "the approval of a bill by the head of state before it becomes law", "legislature"),
 ("subsidiary legislation", "laws made by the executive under powers delegated by the legislature", "legislature"),
 ("judicial review", "the power of the courts to examine the legality of the actions of government", "judiciary"),
 ("precedent", "a previous court decision that guides later cases of a similar nature", "judiciary"),
 ("nullification", "the power of a court to declare a law null and void", "judiciary"),
 ("hereditary succession", "the passing of power from a ruler to a relative, as in a monarchy", "systems of government"),
 ("electoral college", "an electoral body chosen to elect a candidate or a president", "elections"),
 ("manifesto", "the programme of action of a political party", "elections"),
 ("party whip", "the official of a party who ensures that members attend and vote as directed", "parties and groups"),
 ("swing voters", "voters who do not have a firm loyalty to any party", "elections"),
 ("electoral commission", "the independent body responsible for conducting elections", "elections"),
 ("electoral malpractice", "irregularities and cheating during elections", "elections"),
 ("gerrymandering", "the manipulation of constituency boundaries to favour one party", "elections"),
 ("compulsory voting", "a system that requires all eligible voters to vote", "elections"),
 ("public corporation", "a business organisation set up by an act of parliament to provide services", "public administration"),
 ("statutory corporation", "a body established by law to provide a public service", "public administration"),
 ("ombudsman", "an officer who investigates complaints of maladministration against public officers", "public administration"),
 ("civil servant", "an employee of the government who implements its policies", "public administration"),
 ("opacity", "the lack of openness in the conduct of government business", "governance"),
 ("transparency", "openness and accountability in the conduct of government", "governance"),
 ("accountability", "the obligation of public officers to answer for their actions", "governance"),
 ("political culture", "the attitudes, values and beliefs of citizens about politics", "basic concepts"),
 ("political socialisation", "the process by which citizens learn political values and attitudes", "basic concepts"),
 ("ideology", "a coherent set of political beliefs and ideas", "basic concepts"),
 ("totalitarianism", "a system in which the state controls almost every aspect of life", "systems of government"),
 ("autocracy", "a system of government in which one person has absolute power", "systems of government"),
 ("confederation", "a union of independent states with a weak central government", "systems of government"),
 ("devolution", "the transfer of powers from the central government to regional bodies", "systems of government"),
],
3: [
 ("federalism", "the system in which governmental powers are constitutionally shared between the centre and the units", "Nigerian government"),
 ("revenue allocation", "the sharing of national revenue among the tiers of government", "Nigerian government"),
 ("fiscal federalism", "the financial arrangement between the central and component governments", "Nigerian government"),
 ("states creation", "the formation of new states out of existing ones in a federation", "Nigerian government"),
 ("local government autonomy", "the freedom of local governments to administer their own affairs", "Nigerian government"),
 ("coups d'état", "the overthrow of a government by the military", "Nigerian government"),
 ("military regime", "a government controlled by the armed forces", "Nigerian government"),
 ("civilian rule", "government by elected civilians", "Nigerian government"),
 ("transition programme", "the planned process of returning a country to democratic rule", "Nigerian government"),
 ("amendment", "a formal change made to a constitution or law", "constition" if False else "constitution"),
 ("constituent assembly", "a body elected or appointed to draw up a constitution", "constitution"),
 ("military decree", "a law made by a military government", "constitution"),
 ("autochthonous constitution", "a constitution that is home-grown by a country's own people", "constitution"),
 ("written constitution", "a constitution whose rules are contained in a single document", "constitution"),
 ("unwritten constitution", "a constitution whose rules are found in customs and statutes rather than one document", "constitution"),
 ("rigid constitution", "a constitution that is difficult to amend", "constitution"),
 ("flexible constitution", "a constitution that can be amended easily", "constitution"),
 ("constitutional supremacy", "the principle that the constitution is the highest law of the land", "constitution"),
 ("political participation", "the involvement of citizens in the political process", "political behaviour"),
 ("alienation", "the feeling of being cut off from the political process", "political behaviour"),
 ("political apathy", "the lack of interest of citizens in political activities", "political behaviour"),
 ("political culture", "the pattern of attitudes and beliefs that shape political behaviour", "political behaviour"),
 ("cleavage", "a deep division in a society along religious, ethnic or class lines", "political behaviour"),
 ("non-alignment", "the foreign policy of a state that avoids attachment to power blocs", "international relations"),
 ("diplomacy", "the conduct of relations between states through peaceful means", "international relations"),
 ("treaty", "a formal written agreement between states", "international relations"),
 ("multilateralism", "the conduct of relations among several states together", "international relations"),
 ("United Nations", "the world organisation founded in 1945 to promote peace and security", "international relations"),
 ("African Union", "the continental organisation of African states", "international relations"),
 ("ECOWAS", "the regional organisation of West African states", "international relations"),
 ("Commonwealth", "the association of nations formerly under British rule", "international relations"),
 ("foreign policy", "the objectives and strategies of a state in its relations with other states", "international relations"),
 ("diplomatic immunity", "the exemption of diplomats from the laws of the host country", "international relations"),
 ("summit", "a meeting of heads of state or government of several countries", "international relations"),
],
}

def generate(level, seed=1, target=100, blocked=None):
    g = G(SUBJECT, seed, blocked)
    g.fill_facts(FACTS[level], target, use_cap=4)
    g.shuffle_qs()
    return g.qs
