# -*- coding: utf-8 -*-
"""Civic Education: 100 questions per level from a fact bank."""
from engine import G

SUBJECT = "Civic Education"

FACTS = {
1: [
 ("rights", "the entitlements that every citizen is entitled to enjoy", "rights and duties"),
 ("duties", "the obligations expected of a citizen by the state", "rights and duties"),
 ("fundamental human rights", "the basic rights of citizens that are protected by the constitution", "rights and duties"),
 ("right to life", "the fundamental right that protects every person's life", "rights and duties"),
 ("freedom of speech", "the right to express one's opinions without fear", "rights and duties"),
 ("freedom of movement", "the right to move freely within and out of a country", "rights and duties"),
 ("freedom of religion", "the right to practise any religion of one's choice", "rights and duties"),
 ("right to fair hearing", "the right of an accused person to be heard by an impartial court", "rights and duties"),
 ("right to dignity", "the right of every person to be treated with respect", "rights and duties"),
 ("citizen", "a person who is a legal member of a country", "citizenship"),
 ("citizenship", "the legal membership of a person in a country", "citizenship"),
 ("citizenship by birth", "citizenship acquired by being born in a country", "citizenship"),
 ("naturalisation", "the granting of citizenship to a foreigner after meeting legal conditions", "citizenship"),
 ("good citizenship", "the faithful performance of the duties of a citizen", "citizenship"),
 ("civic duties", "the obligations of citizens towards their country, such as paying tax", "citizenship"),
 ("voting", "the act of casting a ballot to choose a candidate", "democracy"),
 ("politician", "a person who seeks political office", "democracy"),
 ("leadership", "the ability to guide and direct a group towards a goal", "values"),
 ("followership", "the support given to a leader by those he leads", "values"),
 ("honesty", "the quality of being truthful and sincere", "values"),
 ("integrity", "the quality of being honest and morally upright", "values"),
 ("discipline", "the ability to obey rules and control one's behaviour", "values"),
 ("hard work", "the diligent and determined effort in carrying out a task", "values"),
 ("self-reliance", "the ability to depend on oneself and one's own efforts", "values"),
 ("tolerance", "the willingness to accept the views and ways of others", "values"),
 ("cooperation", "the working together of people towards a common goal", "values"),
 ("patriotism", "the love of one's country and the readiness to serve it", "nationalism"),
 ("national consciousness", "the awareness of belonging to a nation and sharing its ideals", "nationalism"),
 ("national flag", "the symbol of a nation's identity, green-white-green for Nigeria", "national symbols"),
 ("coat of arms", "the symbol of a country's authority, such as the Nigerian one", "national symbols"),
 ("national anthem", "the official song of a country", "national symbols"),
 ("national pledge", "the solemn promise made by citizens to serve their country", "national symbols"),
 ("respect for elders", "the polite treatment of older people in the society", "citizenship"),
 ("sanitation", "the removal of waste and dirt to keep the environment clean", "citizenship"),
 ("arrest", "the taking of a person into custody by law enforcement agents", "rights and duties"),
],
2: [
 ("rule of law", "the principle that all persons and authorities are equal before the law", "rule of law"),
 ("supremacy of the constitution", "the principle that the constitution is the highest law of the land", "rule of law"),
 ("equality before the law", "the principle that the law treats everyone alike", "rule of law"),
 ("human rights abuse", "the violation of the rights of a person by an individual or the state", "rights and duties"),
 ("trafficking in persons", "the recruitment of persons by force or fraud for exploitation", "social vices"),
 ("child labour", "the use of children in work that denies them education and a proper childhood", "social vices"),
 ("drug abuse", "the use of drugs without medical supervision in ways that harm health", "social vices"),
 ("drug trafficking", "the illegal trade in drugs such as cocaine and heroin", "social vices"),
 ("cultism", "the membership of secret societies that engage in violence and crime", "social vices"),
 ("examination malpractice", "any dishonest act committed during an examination", "social vices"),
 ("corruption", "the misuse of public office for private gain", "social vices"),
 ("bribery", "the giving or receiving of money to influence the decision of an official", "social vices"),
 ("embezzlement", "the fraudulent taking of money entrusted to one's care", "social vices"),
 ("nepotism", "the use of one's position to favour relatives", "social vices"),
 ("tribalism", "the placing of loyalty to one's ethnic group above loyalty to the nation", "social vices"),
 ("religious intolerance", "the refusal to tolerate the religious beliefs of others", "social vices"),
 ("human trafficking", "the trade in persons for exploitation", "social vices"),
 ("EFCC", "the agency that fights economic and financial crimes in Nigeria", "government agencies"),
 ("ICPC", "the agency that fights corruption in public life in Nigeria", "government agencies"),
 ("NDLEA", "the agency that fights drug trafficking and drug abuse in Nigeria", "government agencies"),
 ("NAFDAC", "the agency that regulates food and drugs in Nigeria", "government agencies"),
 ("FRSC", "the agency responsible for road safety in Nigeria", "government agencies"),
 ("NHRC", "the agency that protects and promotes human rights in Nigeria", "government agencies"),
 ("NYSC", "the scheme that mobilises graduates for national service", "government agencies"),
 ("voter education", "the teaching of citizens how to vote and why voting matters", "democracy"),
 ("free and fair elections", "elections conducted without violence, rigging or intimidation", "democracy"),
 ("ballot box", "the box into which voters drop their ballot papers during an election", "democracy"),
 ("sexual harassment", "unwanted sexual advances in the workplace or school", "social vices"),
 ("youth empowerment", "the training and support given to youths to make them self-reliant", "national development"),
 ("poverty alleviation", "programmes designed to reduce the suffering of the poor", "national development"),
 ("national development", "the improvement of the economic and social well-being of a country", "national development"),
 ("civic responsibility", "the duties that citizens owe to their country", "rights and duties"),
 ("environmental protection", "the protection of the natural environment from pollution and degradation", "national development"),
 ("public health", "the health of the whole population and the measures that protect it", "national development"),
 ("stakeholder", "a person or group that has an interest in an organisation or issue", "national development"),
],
3: [
 ("good governance", "the responsible and transparent use of power for the benefit of the people", "governance"),
 ("transparency", "openness in the conduct of government business", "governance"),
 ("accountability", "the obligation of public officers to answer for their actions", "governance"),
 ("due process", "the fair and lawful procedure followed in government decisions", "governance"),
 ("public service", "the service rendered to the public by government employees", "governance"),
 ("civil service", "the body of officials that implements government policies", "governance"),
 ("public servant", "a person employed in the service of the government", "governance"),
 ("checks and balances", "the powers that enable each arm of government to limit the others", "governance"),
 ("separation of powers", "the sharing of power among the executive, legislature and judiciary", "governance"),
 ("legislature", "the arm of government that makes laws", "governance"),
 ("executive", "the arm of government that implements laws", "governance"),
 ("judiciary", "the arm of government that interprets laws", "governance"),
 ("civil society", "the organisations that work independently of government to promote public interest", "civic engagement"),
 ("advocacy", "the public support for a cause or policy", "civic engagement"),
 ("civil disobedience", "the deliberate breaking of laws considered unjust, done peacefully", "civic engagement"),
 ("humanitarian service", "the voluntary work done to relieve the suffering of people", "civic engagement"),
 ("voter apathy", "the lack of interest of citizens in voting", "civic engagement"),
 ("public opinion", "the collective views of citizens on public issues", "civic engagement"),
 ("volunteering", "the giving of one's time to help others without payment", "civic engagement"),
 ("national unity", "the harmony of the different ethnic and religious groups of a nation", "nationalism"),
 ("ethnic prejudice", "the negative attitude held against people of another ethnic group", "nationalism"),
 ("inter-communal relationship", "the relationship between different communities in a nation", "nationalism"),
 ("globalisation", "the growing interconnection of countries in trade, communication and culture", "nationalism"),
 ("HIV/AIDS", "the disease that destroys the body's immune system", "health issues"),
 ("stigmatisation", "the unfair labelling of a person because of a disease or condition", "health issues"),
 ("peer pressure", "the influence of friends to behave in a certain way", "social vices"),
 ("restorative justice", "the approach that repairs the harm caused by an offence", "justice"),
 ("social justice", "the fair treatment of all members of society", "justice"),
 ("equity", "fairness in the distribution of resources and opportunities", "justice"),
 ("legal aid", "free legal assistance given to people who cannot afford lawyers", "justice"),
 ("independence of the judiciary", "the freedom of the courts from interference by other arms of government", "governance"),
 ("electoral system", "the method by which votes are converted into seats and offices", "democracy"),
 ("constitutional rights", "rights provided for and protected by the constitution", "rights and duties"),
 ("anti-corruption", "measures aimed at preventing and punishing corruption", "governance"),
 ("community development", "the improvement of living conditions in a community", "civic engagement"),
],
}

def generate(level, seed=1, target=100, blocked=None):
    g = G(SUBJECT, seed, blocked)
    g.fill_facts(FACTS[level], target, use_cap=4)
    g.shuffle_qs()
    return g.qs
