# -*- coding: utf-8 -*-
"""Mater Misericordiae Secondary School, Rumomasi — SS1 weekly lesson notes
(First Term, 2026/2027) · Part A: Biology, Chemistry, Economics, English, Geography.
Each week: (topic, [(heading, [paragraph|bullet…]), …], [evaluation questions])."""

SS1_A = {
"Biology": [
 ("Characteristics of Living Things",
  [("Introduction", ["Living things are organisms that carry out the activities of life — movement, respiration, sensitivity, growth, reproduction, excretion and nutrition. Biologists use the acronym MRS GREN to remember these life processes."]),
   ("Key life processes", ["<b>Movement</b> — living things change position or move parts of themselves (plants move towards light).", "<b>Respiration</b> — the breakdown of food to release energy (glucose + oxygen → carbon dioxide + water + energy).", "<b>Sensitivity (irritability)</b> — the ability to detect and respond to changes in the environment, e.g. a flower tracking the sun.", "<b>Growth</b> — a permanent increase in size and dry mass, brought about by cell division and enlargement.", "<b>Reproduction</b> — the production of new individuals so the species continues.", "<b>Excretion</b> — the removal of metabolic waste, e.g. carbon dioxide, urea and excess water.", "<b>Nutrition</b> — the taking in and use of food (plants make their own; animals feed on other organisms)."]),
   ("Dormancy and hibernation", ["Dormant seeds do not show visible life processes but resume activity when conditions (water, warmth, oxygen) return — they are still living. This is why 'is it alive?' cannot be answered by watching for a few minutes alone."]),
   ("Class evaluation", ["Name the seven life processes in the MRS GREN order.", "Distinguish between movement in a plant and movement in an animal.", "Why is excretion different from egestion?", "Give two reasons a dry seed is still described as a living thing."])]),

 ("Classification of Living Things",
  [("Introduction", ["Classification is the grouping of organisms on the basis of shared features. It makes the study of the millions of organisms on earth orderly and shows their relationships."]),
   ("The five kingdoms", ["<b>Monera</b> — bacteria: single-celled, no true nucleus (prokaryotic).", "<b>Protista</b> — amoeba, paramecium, euglena: single-celled with a true nucleus.", "<b>Fungi</b> — moulds, mushrooms, yeast: saprophytic, no chlorophyll, cell wall of chitin.", "<b>Plantae</b> — green plants: photosynthetic, cell walls of cellulose, mostly fixed to the ground.", "<b>Animalia</b> — animals: heterotrophic, move, no cell wall, store food as glycogen."]),
   ("Why classification matters", ["It reveals evolutionary relationships, allows scientists worldwide to use the same names (binomial nomenclature by Carolus Linnaeus), and helps identify harmful or useful species quickly. Every organism has a genus and a species name, e.g. <i>Homo sapiens</i>."]),
   ("Class evaluation", ["List the five kingdoms with one example each.", "Which kingdom has organisms without a true nucleus?", "Who developed the binomial naming system and what does it consist of?", "State two reasons for classifying organisms."])]),

 ("Cell Structure & Functions",
  [("Introduction", ["The cell is the basic unit of life. All living things are made of cells; new cells arise from existing cells. A cell consists of a membrane, cytoplasm and a nucleus (in eukaryotic cells)."]),
   ("Cell organelles", ["<b>Nucleus</b> — controls all cell activities and carries genetic material (DNA).", "<b>Cell membrane</b> — controls what enters and leaves the cell (semi-permeable).", "<b>Mitochondria</b> — site of respiration; the power house that releases energy.", "<b>Ribosomes</b> — protein synthesis.", "<b>Cytoplasm</b> — the jelly-like medium where chemical reactions take place.", "<b>Vacuole</b> — stores cell sap (large in plant cells).", "<b>Chloroplasts</b> — contain chlorophyll for photosynthesis (plant cells only).", "<b>Cell wall</b> — rigid cellulose wall that gives a plant cell its shape and protection."]),
   ("Plant vs animal cells", ["Plant cells have a cellulose cell wall, chloroplasts and one large central vacuole; animal cells have none of these (or only small temporary vacuoles). Both have a nucleus, membrane, cytoplasm, mitochondria and ribosomes."]),
   ("Class evaluation", ["Draw and label a typical plant cell.", "Which organelle is the site of respiration?", "State three differences between plant and animal cells.", "What is the function of the cell membrane?"])]),

 ("Cell Division (Mitosis)",
  [("Introduction", ["Mitosis is the division of a cell into two identical daughter cells with the same number of chromosomes. It produces growth, repair of worn-out tissues and asexual reproduction."]),
   ("Stages of mitosis", ["<b>Prophase</b> — chromosomes become visible, each made of two chromatids joined at the centromere; the nuclear membrane breaks down.", "<b>Metaphase</b> — chromosomes line up at the equator of the spindle.", "<b>Anaphase</b> — chromatids separate and move to opposite poles.", "<b>Telophase</b> — two new nuclei form and the cytoplasm divides (cytokinesis), giving two identical cells."]),
   ("Importance", ["It maintains the chromosome number (diploid → diploid), allows a single fertilised egg to become millions of cells, and heals wounds. Uncontrolled mitosis can produce tumours."]),
   ("Class evaluation", ["Define mitosis.", "Arrange the four stages of mitosis in order and describe one event of each.", "Why are the daughter cells identical?", "State two importance of mitosis in living organisms."])]),

 ("Plant Tissues",
  [("Introduction", ["A tissue is a group of similar cells working together to perform one function. In plants, tissues are grouped into meristematic (dividing) and permanent tissues."]),
   ("Meristematic tissues", ["Found at the tips of roots and shoots (apical meristems) and in the cambium; cells divide continuously by mitosis and are thin-walled with dense cytoplasm, giving the plant new growth."]),
   ("Permanent tissues", ["<b>Parenchyma</b> — thin-walled living cells for storage and photosynthesis.", "<b>Collenchyma</b> — thickened living cells giving young stems support.", "<b>Sclerenchyma</b> — thick, lignified dead cells for strong support.", "<b>Xylem</b> — transports water and mineral salts upward and supports the plant (tracheids and vessels).", "<b>Phloem</b> — transports food (sucrose) from leaves to all parts of the plant through sieve tubes and companion cells."]),
   ("Class evaluation", ["Define a tissue.", "Distinguish between xylem and phloem.", "Where are meristematic tissues found?", "Name the supporting tissues in plants and state how they differ."])]),

 ("Animal Tissues & Organisation",
  [("Introduction", ["In animals, four main tissue types build every organ: epithelial, connective, muscular and nervous tissues."]),
   ("The four tissue types", ["<b>Epithelial</b> — covers surfaces and lines organs (e.g. skin, lining of the mouth); protects, absorbs and secretes.", "<b>Connective</b> — supports and binds (blood, bone, cartilage, tendons and adipose tissue).", "<b>Muscular</b> — generates movement (voluntary/skeletal, involuntary/smooth and cardiac muscle).", "<b>Nervous</b> — receives and transmits impulses (neurons make up the brain, spinal cord and nerves)."]),
   ("Levels of organisation", ["Cells → tissues → organs (e.g. the heart) → systems (e.g. circulatory system) → organism. This hierarchy shows how the body of a mammal is organised from the simplest unit upwards."]),
   ("Class evaluation", ["Name the four animal tissue types with one function of each.", "Which tissue transmits nerve impulses?", "Give the correct order: organ → cell → system → tissue.", "What tissue types make up the heart?"])]),
],
"Chemistry": [
 ("Introduction to Chemistry",
  [("Introduction", ["Chemistry is the study of matter — its composition, structure, properties and the changes it undergoes. It is called the central science because it links physics, biology and every applied science."]),
   ("Why chemistry matters", ["It explains everyday life: cooking, rusting, burning, medicine, soap, fertiliser, food preservation and the treatment of water. Chemistry has produced drugs that cure diseases, improved farming yields and provided materials like plastics, glass and cement."]),
   ("Branches of chemistry", ["Physical chemistry — the energy, rates and states of matter (kinetics, thermodynamics).", "Organic chemistry — carbon compounds (fuels, plastics, drugs, food).", "Inorganic chemistry — metals, non-metals, acids, bases and salts.", "Analytical chemistry — identifying what substances are present and how much (testing water purity).", "Biochemistry — chemical processes in living things (enzymes, DNA, metabolism)."]),
   ("Class evaluation", ["Define chemistry and state the main branches.", "Mention three ways chemistry improves everyday life.", "Why is chemistry called the central science?"])]),

 ("Laboratory Safety & Apparatus",
  [("Introduction", ["A laboratory is a room set aside for practical chemistry. Safety rules and correct use of apparatus protect the learner and make experiments reliable."]),
   ("Safety rules", ["Always wear a lab coat and goggles; never taste or smell chemicals directly (waft).", "Handle acids and alkalis carefully; wash splashes with plenty of water.", "Never point a heated test tube at anyone; heat test tubes at an angle. Keep the bench tidy; tie back hair; report every accident at once."]),
   ("Common apparatus and uses", ["<b>Beaker</b> — holding and mixing liquids; <b>conical flask</b> — mixing and titration.", "<b>Measuring cylinder</b> — accurate volume of liquids; <b>burette and pipette</b> — precise volumes in titration.", "<b>Test tube and boiling tube</b> — small-scale reactions and heating; <b>funnel</b> — filtering and pouring.", "<b>Evaporating dish</b> — evaporating solutions to dryness; <b>crucible</b> — strong heating of solids.", "<b>Bunsen burner</b> — heating; <b>tripod stand, gauze and retort stand</b> — supporting apparatus.", "<b>Watch glass, spatula, glass rod, wash bottle</b> — covers, sampling and stirring."]),
   ("Class evaluation", ["List five safety rules in the laboratory.", "Which apparatus would you use to measure 25 cm³ of water accurately?", "State the use of a crucible and an evaporating dish.", "Why must chemicals never be tasted?"])]),

 ("Matter & Separation",
  [("Introduction", ["Matter is anything that has mass and occupies space. It exists in three physical states — solid, liquid and gas — which can change into one another by heating or cooling."]),
   ("States of matter", ["<b>Solid</b> — fixed shape and volume; particles closely packed, vibrating about fixed positions.", "<b>Liquid</b> — fixed volume but takes the shape of its container; particles close but able to slide.", "<b>Gas</b> — no fixed shape or volume; particles far apart and moving rapidly and randomly. Changes: melting, freezing, evaporation, condensation, sublimation."]),
   ("Separation techniques", ["<b>Filtration</b> — separates an insoluble solid from a liquid (sand from water).", "<b>Evaporation/crystallisation</b> — recovers a dissolved solid from a solution (salt from sea water).", "<b>Simple distillation</b> — separates a liquid from a solution (pure water from salt solution).", "<b>Fractional distillation</b> — separates miscible liquids of different boiling points (crude oil; ethanol–water).", "<b>Chromatography</b> — separates dyes in inks.", "<b>Decantation, centrifugation, sublimation and magnetic separation</b> — for other mixtures."]),
   ("Class evaluation", ["Define matter and name its three states with particle arrangements.", "Which technique separates a mixture of sand and salt?", "How would you separate coloured dyes in a pen?", "State the difference between a pure substance and a mixture."])]),

 ("Atomic Structure",
  [("Introduction", ["An atom is the smallest particle of an element that can take part in a chemical reaction. It consists of a nucleus surrounded by shells of electrons."]),
   ("Sub-atomic particles", ["<b>Protons</b> — positive, in the nucleus; their number defines the element (atomic number).", "<b>Neutrons</b> — neutral, in the nucleus; their number adds mass without changing the element.", "<b>Electrons</b> — negative, arranged in shells outside the nucleus; in a neutral atom the number of electrons equals the number of protons."]),
   ("Key definitions", ["Atomic number (Z) = number of protons; mass number (A) = protons + neutrons. Isotopes are atoms of the same element with the same number of protons but different numbers of neutrons (e.g. Cl-35 and Cl-37). Electron configuration shows the arrangement of electrons in shells (e.g. sodium 2,8,1), which explains the chemical behaviour of the element."]),
   ("Class evaluation", ["State the charge and location of each sub-atomic particle.", "Calculate the number of protons, neutrons and electrons in ²³Na₁₁.", "Define isotopes with an example.", "Write the electron configuration of oxygen (Z = 8) and predict its group."])]),

 ("Elements, Compounds & Mixtures",
  [("Introduction", ["Matter is classified into elements, compounds and mixtures. An element is a substance that cannot be split into simpler substances by chemical means; a compound is formed when two or more elements combine chemically in fixed proportions."]),
   ("Distinguishing features", ["Elements have one type of atom (e.g. oxygen, iron, gold). Compounds have properties completely different from their elements (e.g. hydrogen + oxygen → water) and can only be separated by chemical means. Mixtures are formed by physical combination (air, salt + sand) with each component keeping its properties, and are separated by physical methods."]),
   ("Common examples", ["Elements: metals (iron, copper, sodium), non-metals (oxygen, carbon, sulphur). Compounds: water (H₂O), carbon dioxide (CO₂), common salt (NaCl), lime (CaO). Mixtures: air, sea water, brass, petroleum."]),
   ("Class evaluation", ["Distinguish between an element and a compound with examples.", "Is air a compound or a mixture? Give reasons.", "Name two methods of separating mixtures.", "Why do compounds differ in properties from their constituent elements?"])]),

 ("Separation Challenges & Laboratory Skills",
  [("Introduction", ["This week consolidates the practical skill of choosing the right separation technique and recording observations accurately in a laboratory report."]),
   ("Choosing a technique", ["Ask: is the mixture solid + solid, solid + liquid, or liquid + liquid? Are the components soluble? Do the boiling points differ? The answers decide whether to filter, evaporate, distil or use a separating funnel (oil and water)."]),
   ("Laboratory report format", ["<b>Title, aim, apparatus, method, observation, conclusion</b>. Observations must be factual (colour change, gas evolved, precipitate formed), never interpretations. Accuracy: read the meniscus at eye level, rinse apparatus, record results to the correct number of decimal places."]),
   ("Class evaluation", ["Describe how you would obtain pure water from a salt solution.", "Why is a separating funnel suitable for oil and water?", "What is the difference between an observation and a conclusion?", "State three good laboratory habits that improve accuracy."])]),
],
"Economics": [
 ("Basic Concepts: Wants & Scarcity",
  [("Introduction", ["Economics is the study of how man allocates scarce resources among competing wants to satisfy them. Wants are unlimited desires for goods and services, but resources are limited — this is scarcity."]),
   ("Wants and scarcity", ["Human wants are insatiable — when one want is satisfied another appears. Scarcity means resources used to satisfy wants are limited relative to the demand for them (land, labour, capital and entrepreneur are all limited). Scarcity is the fundamental problem of economics and it forces choice."]),
   ("Goods and services", ["<b>Free goods</b> — abundant gifts of nature with no price (air, sunshine).", "<b>Economic goods</b> — scarce, command a price (food, clothing, petrol).", "<b>Consumer goods</b> — satisfy wants directly (bread, shoes); <b>producer goods</b> — used to produce other goods (machines)."]),
   ("Class evaluation", ["Define scarcity and explain why it gives rise to the study of economics.", "Distinguish between free goods and economic goods with examples.", "Why are human wants described as insatiable?", "Classify the following as consumer or producer goods: sewing machine, bread, lathe, school bag."])]),

 ("Factors of Production",
  [("Introduction", ["Factors of production are the resources used to produce goods and services. They are land, labour, capital and the entrepreneur, each earning a reward."]),
   ("The four factors and their rewards", ["<b>Land</b> — natural resources on, above and below the earth's surface (rent).", "<b>Labour</b> — all human effort, physical and mental (wages/salary).", "<b>Capital</b> — man-made wealth used in production, e.g. machinery, tools, money (interest).", "<b>Entrepreneur/Organiser</b> — combines the other factors, takes risks and makes decisions (profit)."]),
   ("Characteristics", ["Land is fixed in supply and immobile; labour is mobile, perishable and cannot be separated from the labourer; capital is man-made and depreciates; the entrepreneur bears the risk of loss but enjoys profit. Mobility of factors (occupational and geographical) determines how easily they move between uses."]),
   ("Class evaluation", ["List the four factors of production and their rewards.", "Explain what is meant by mobility of labour.", "Why is the entrepreneur considered the most important factor?", "Give three characteristics of capital."])]),

 ("Opportunity Cost",
  [("Introduction", ["Because resources are scarce, choosing one thing means giving up the next best alternative. Opportunity cost is the value of the next best alternative forgone — the real cost of any decision."]),
   ("Examples", ["A student who uses ₦2,000 to buy a textbook instead of a film ticket: the ticket is the opportunity cost. A farmer who plants maize on his land instead of yam forgoes the yam harvest. A government that spends on roads instead of hospitals forgoes the hospitals."]),
   ("Scarcity, choice and scale of preference", ["Choice follows from scarcity. A scale of preference is a list of wants arranged in order of importance, drawn up because income is limited. The want at the top is satisfied first; the one just below it shows the opportunity cost of the first choice."]),
   ("Class evaluation", ["Define opportunity cost and give a personal example.", "What is a scale of preference and why is it drawn up?", "Explain how opportunity cost applies to a government budget.", "Distinguish between money cost and opportunity cost."])]),

 ("Basic Economic Problems",
  [("Introduction", ["Every society faces three basic economic problems: WHAT to produce, HOW to produce and FOR WHOM to produce — all caused by scarcity of resources."]),
   ("The three problems", ["<b>What to produce</b> — which goods and services, and how much, given limited resources (choose between guns and butter).", "<b>How to produce</b> — the combination of techniques (labour-intensive vs capital-intensive), considering cost and availability of factors.", "<b>For whom to produce</b> — how the national income is distributed among the people (rich vs poor, cities vs villages)."]),
   ("Economic systems as solutions", ["In a capitalist/free-enterprise economy the price mechanism decides; in a socialist/command economy the state decides; in a mixed economy both the state and the market decide (as in Nigeria)."]),
   ("Class evaluation", ["State the three basic economic problems of society.", "Explain 'how to produce' with a labour-intensive example.", "Compare how capitalism and socialism answer 'for whom to produce'.", "Why is Nigeria described as a mixed economy?"])]),

 ("Production & The Production Possibility Curve",
  [("Introduction", ["Production is the creation of utility — wealth in goods and services. The Production Possibility Curve (PPC) shows the various combinations of two goods an economy can produce with its limited resources and given technology."]),
   ("The PPC explained", ["Points on the curve are attainable and efficient; points inside are attainable but inefficient (unemployment of resources); points outside are unattainable with current resources. A shift of the curve outward shows economic growth (more resources or better technology)."]),
   ("Forms of production", ["<b>Primary</b> — extraction from nature (farming, fishing, mining).", "<b>Secondary</b> — manufacturing and processing (bakeries, refineries).", "<b>Tertiary</b> — services (banking, transport, teaching, trade)."]),
   ("Class evaluation", ["Define production and state its forms.", "Draw a PPC and label the efficient, inefficient and unattainable points.", "What causes the PPC to shift outward?", "Classify the following: palm oil milling, banking, cocoa farming, shoe making."])]),

 ("Demand & Supply: The Market",
  [("Introduction", ["The market brings buyers and sellers together. Demand is the quantity of a commodity buyers are willing and able to buy at a given price over a period; supply is the quantity sellers are willing and able to offer for sale."]),
   ("The law of demand and supply", ["The law of demand: the higher the price, the lower the quantity demanded, other things being equal. The law of supply: the higher the price, the higher the quantity supplied. The point where the demand and supply curves intersect is the equilibrium price and quantity."]),
   ("Market terminology", ["<b>Market demand</b> — the total demand of all buyers; <b>effective demand</b> — desire backed by ability to pay. <b>Excess demand</b> (shortage) pushes price up; <b>excess supply</b> (surplus) pushes it down. Demand and supply together determine prices in a free market."]),
   ("Class evaluation", ["Define demand and state the law of demand.", "What is equilibrium price?", "Explain the effect of excess supply on price.", "Distinguish between market demand and individual demand."])]),
],
"English Language": [
 ("Parts of Speech",
  [("Introduction", ["Words in English are grouped into eight parts of speech: noun, pronoun, verb, adjective, adverb, preposition, conjunction and interjection. Knowing them helps you build and analyse sentences correctly."]),
   ("The eight parts with examples", ["<b>Noun</b> — names a person, place, thing or idea (teacher, Abuja, honesty).", "<b>Pronoun</b> — replaces a noun (he, she, it, they, who).", "<b>Verb</b> — expresses action or state (run, is, think).", "<b>Adjective</b> — describes a noun (tall, blue, three).", "<b>Adverb</b> — modifies a verb, adjective or another adverb (quickly, very, here).", "<b>Preposition</b> — shows relationship (in, on, under, between).", "<b>Conjunction</b> — joins words or clauses (and, but, because, although).", "<b>Interjection</b> — expresses emotion (Oh!, Hurray!, Alas!)."]),
   ("Identifying parts of speech", ["Ask what job the word does in its sentence: a word can change its part of speech by position — <i>fast</i> is an adjective in 'a fast car' but an adverb in 'he runs fast'."]),
   ("Class evaluation", ["List the eight parts of speech with one example each.", "Identify the parts of speech in: 'The young boy quickly opened his new book.'", "How can the same word be two different parts of speech? Illustrate."])]),

 ("Tenses & Verb Forms",
  [("Introduction", ["Tense shows the time of an action: past, present or future. It is formed by the verb in combination with auxiliaries (be, have, do, will)."]),
   ("Simple tenses", ["<b>Present</b> — habits and general truths (She <i>writes</i> every day).", "<b>Past</b> — completed actions (We <i>visited</i> Lagos last week).", "<b>Future</b> — actions that will happen (They <i>will travel</i> tomorrow)."]),
   ("Continuous and perfect forms", ["<b>Present continuous</b> — action in progress (He <i>is reading</i> now). <b>Past continuous</b> — was/were + -ing (We <i>were sleeping</i> when it rained). <b>Present perfect</b> — have/has + past participle, for actions with present relevance (She <i>has finished</i> her assignment). <b>Past perfect</b> — had + past participle (The bus <i>had left</i> before we arrived). <b>Future perfect</b> — will have + past participle (By June, I <i>will have completed</i> SS1)."]),
   ("Agreement", ["The verb must agree with its subject in number: 'The boy <i>is</i> here' but 'The boys <i>are</i> here'. Irregular verbs change form: go/went/gone, see/saw/seen, eat/ate/eaten."]),
   ("Class evaluation", ["Change 'She writes letters' into past, future, present continuous and present perfect.", "What is the past participle of: break, choose, bring?", "Correct: 'The students is in the hall.'", "State the use of the present perfect tense."])]),

 ("Sentence Types",
  [("Introduction", ["Sentences are classified by structure (simple, compound, complex, compound-complex) and by purpose (declarative, interrogative, imperative, exclamatory)."]),
   ("By structure", ["<b>Simple</b> — one independent clause (The girl sang).", "<b>Compound</b> — two or more independent clauses joined by a coordinating conjunction (The girl sang <i>and</i> the boy danced).", "<b>Complex</b> — one independent clause + one or more subordinate clauses (Because it rained, the match was postponed).", "<b>Compound-complex</b> — combination, e.g. two main clauses and a subordinate clause."]),
   ("By purpose", ["<b>Declarative</b> — makes a statement. <b>Interrogative</b> — asks a question. <b>Imperative</b> — gives a command or request. <b>Exclamatory</b> — expresses strong feeling."]),
   ("Clause recognition skills", ["A clause has a subject and a verb. Main clauses can stand alone; subordinate clauses begin with subordinators (because, although, when, if, that, who) and cannot stand alone."]),
   ("Class evaluation", ["Classify these sentences as simple/compound/complex: 'I slept late; I missed the bus.'", "Write one sentence of each purpose type about your school.", "Identify the main and subordinate clauses in: 'Although she was tired, she kept working.'", "What makes a clause independent?"])]),

 ("Vocabulary in Context",
  [("Introduction", ["Vocabulary development means learning words in the company of their contexts so their meanings are clear. Context clues — definitions, examples, contrast and cause — reveal the meaning of unfamiliar words."]),
   ("Types of context clues", ["<b>Definition clue</b> — 'A <i>pedestrian</i>, that is, a person walking, crossed the road.'", "<b>Example clue</b> — 'She liked <i>cereals</i> such as maize, rice and millet.'", "<b>Contrast clue</b> — 'He was <i>temperate</i>, unlike his brother who drank excessively.'", "<b>Cause/effect clue</b> — 'The drought was so severe that <i>famine</i> spread through the region.'"]),
   ("Word families and collocations", ["Learn words with their families (decide, decision, decisive, indecisive) and their partners — collocations: <i>make</i> a decision, <i>commit</i> a crime, <i>heavy</i> rain, <i>strong</i> coffee. Register: formal (commence, purchase) vs informal (start, buy)."]),
   ("Class evaluation", ["Define the word 'famine' using its context clue in the example above.", "Give two collocations for: decision, crime.", "What is register? Give a formal and informal pair.", "Use 'temperate' in a sentence of your own."])]),

 ("Comprehension: Main Idea & Supporting Details",
  [("Introduction", ["Comprehension is understanding what you read. The main idea is what the whole passage is about; supporting details are the facts, examples and reasons that develop it."]),
   ("Finding the main idea", ["Read the passage once quickly (skimming) for the gist. Look for the topic sentence — usually the first or last sentence of the paragraph. Ask: 'What is the writer saying about the topic?' Express it in one sentence: that is the main idea."]),
   ("Identifying details", ["Supporting details answer who, what, when, where, why and how. Distinguish facts (verifiable) from opinions (personal views). Inference goes beyond what is stated — what the writer suggests but does not say directly."]),
   ("Summary skills", ["State the main idea in your own words; join related details into one or two sentences; never copy the passage word for word; keep to the instruction (e.g. one sentence, four points)."]),
   ("Class evaluation", ["Read a short passage and state its main idea in one sentence.", "What is the difference between a fact and an opinion?", "Explain what is meant by inference.", "List three steps for summarising a passage."])]),

 ("Composition: Narrative Writing",
  [("Introduction", ["A narrative is a story. Effective narratives follow a sequence: introduction (setting and characters), rising action, climax, falling action and resolution — told in the first person (I) or third person (he/she)."]),
   ("Planning a narrative", ["Choose a clear topic (e.g. 'The day I will never forget'); brainstorm events in order; write an outline of 4–5 paragraphs with a strong opening sentence that catches the reader's attention."]),
   ("Language and mechanics", ["Use past tenses consistently; vivid verbs (stumbled, dashed, whispered) instead of weak ones (went, said); descriptive details for the five senses; correct punctuation of dialogue, and paragraphs that signal a new event. Conclude with a reflection that rounds off the story."]),
   ("Class evaluation", ["Outline a narrative on 'My first day in secondary school' in five sentences.", "Why is a story told in the past tense?", "Give three vivid verbs to replace: walk, said, look.", "What should the opening paragraph of a narrative achieve?"])]),
],
"Geography": [
 ("The Earth & Solar System",
  [("Introduction", ["Geography is the study of the earth — its physical features, people and the relationships between them. It is divided into physical geography (landforms, climate, vegetation) and human geography (population, settlement, economic activities)."]),
   ("The solar system", ["The solar system has eight planets — Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus and Neptune — orbiting the sun, along with moons, asteroids and comets. The earth is the third planet from the sun, at an average distance of about 150 million km (1 astronomical unit)."]),
   ("The earth's structure", ["The earth is a slightly flattened sphere. It has three zones: the crust (thin outer layer of rocks), the mantle (hot, semi-molten) and the core (inner core solid, outer core liquid). The lithosphere (crust + upper mantle) floats on the asthenosphere."]), 
   ("Importance of geography", ["It explains the distribution of resources, weather and population; it builds map-reading skills and an understanding of environmental problems like desertification, flooding and erosion."]),
   ("Class evaluation", ["List the eight planets in order from the sun.", "Name the three zones of the earth's interior.", "State two branches of geography.", "What is the astronomical unit?"])]),

 ("Latitude & Longitude",
  [("Introduction", ["Latitude and longitude form the grid system used to fix the position of places on the earth's surface. They are measured in degrees (°) and minutes (')."]),
   ("Latitude", ["Latitude is the angular distance of a place north or south of the equator (0°). Important lines: the equator (0°), Tropic of Cancer (23½°N), Tropic of Capricorn (23½°S), Arctic Circle (66½°N), Antarctic Circle (66½°S) and the poles (90°N/S). Latitudes are also called parallels."]),
   ("Longitude", ["Longitude is the angular distance east or west of the Prime Meridian (0°), which passes through Greenwich, London. The 180° meridian is the International Date Line. Places east of Greenwich see the sun earlier; the world is divided into 24 time zones, each 15° of longitude = 1 hour."]),
   ("Calculating time and distance", ["Time: every 15° = 1 hour (add for east, subtract for west). Distance: 1° of latitude ≈ 111 km. Example: Lagos (3°E) and London (0°) differ by 3° = 12 minutes; when it is 12:00 in London it is 12:12 in Lagos."]),
   ("Class evaluation", ["Define latitude and longitude.", "Calculate the time difference between two places 30° of longitude apart.", "Name the five important lines of latitude.", "Why are latitudes are called parallels?"])]),

 ("Earth Movements",
  [("Introduction", ["The earth rotates on its axis once every 24 hours and revolves round the sun once every 365¼ days. These two movements produce most of the rhythms of life."]),
   ("Rotation (daily)", ["Rotation is the spinning of the earth from west to east, causing day and night, the apparent rising and setting of the sun, deflection of winds (Coriolis effect) and tidal movements. Places east of the Greenwich meridian experience sunrise first."]),
   ("Revolution (annual)", ["Revolution is the earth's journey round the sun along its elliptical orbit, with its axis tilted at 23½°. It causes the changing seasons, the unequal lengths of day and night, and the migration of the overhead sun between the Tropics of Cancer and Capricorn."]),
   ("Equinoxes and solstices", ["<b>Equinoxes</b> — 21 March and 23 September: the sun is overhead the equator; day and night are equal everywhere. <b>Solstices</b> — 21 June (sun overhead the Tropic of Cancer, longest day in the north) and 22 December (sun overhead the Tropic of Capricorn)."]),
   ("Class evaluation", ["Distinguish between rotation and revolution.", "What causes the seasons?", "Explain an equinox.", "State three effects of the earth's rotation."])]),

 ("Rocks & Minerals",
  [("Introduction", ["A rock is a natural solid mass of minerals; a mineral is a naturally occurring inorganic substance with a definite composition and structure. The study of rocks is petrology."]),
   ("The three rock classes", ["<b>Igneous</b> — formed by cooling and solidification of magma/lava (granite, basalt).", "<b>Sedimentary</b> — formed from weathered particles or remains of organisms deposited in layers (sandstone, limestone, coal). Fossils are found here. They may be mechanical, organic or chemical.", "<b>Metamorphic</b> — formed when existing rocks are changed by heat and/or pressure (marble from limestone, gneiss from granite, slate from shale)."]),
   ("The rock cycle", ["Rocks are continually transformed: weathering breaks igneous and metamorphic rocks into sediments; sediments compact into sedimentary rocks; heat and pressure change them to metamorphic; melting returns them to magma. There is no beginning or end to the cycle."]),
   ("Uses of rocks and minerals", ["Granite — building; limestone — cement, agriculture; coal — fuel; marble — sculpture, buildings; salt — food; gold, tin, columbite — jewellery, industry and foreign exchange."]),
   ("Class evaluation", ["Name the three classes of rocks with two examples each.", "How is marble formed?", "Why are fossils found mainly in sedimentary rocks?", "State two uses of limestone."])]),

 ("Weathering & Mass Movement",
  [("Introduction", ["Weathering is the breaking down of rocks in place by physical, chemical and biological agents, without removal. It is the first stage of denudation."]),
   ("Types of weathering", ["<b>Physical/mechanical</b> — temperature changes (expansion and contraction), frost action, pressure release and abrasion; rocks crack into fragments.", "<b>Chemical</b> — oxidation, hydration, carbonation (rainwater + CO₂ dissolves limestone), solution and hydrolysis; the rock's minerals are changed.", "<b>Biological</b> — plant roots widening cracks, burrowing animals, and humic acids from decay."]),
   ("Mass movement", ["Mass movement is the downslope movement of weathered material under gravity: <b>slow</b> — soil creep, solifluction; <b>fast</b> — landslides, mudflows, rockfalls. It is aided by water saturation, steep slopes, earthquakes and the removal of vegetation."]),
   ("Class evaluation", ["Distinguish between weathering and erosion.", "Explain how carbonation weathers limestone.", "What factors accelerate mass movement?", "Give two agents of biological weathering."])]),

 ("Denudation & The Work of Rivers",
  [("Introduction", ["Denudation is the wearing away of the land (weathering, mass movement, erosion, transportation and deposition). Running water — rivers — is the most important agent of erosion on land."]),
   ("Work of a river", ["Rivers erode by hydraulic action, corrosion/abrasion, solution and attrition; they transport material as solution, suspension, saltation and traction; they deposit when the load exceeds the capacity (slower water)."]),
   ("Landforms along the course", ["<b>Youthful (upper) course</b> — V-shaped valleys, interlocking spurs, waterfalls, rapids, potholes.", "<b>Mature (middle) course</b> — meanders, river cliffs and slip-off slopes, ox-bow lakes, braided channels.", "<b>Old (lower) course</b> — levees, flood plains, deltas, estuaries."]),
   ("Class evaluation", ["Define denudation and name its processes.", "List four ways a river erodes.", "Name two landforms of the youthful course.", "How is an ox-bow lake formed?"])]),
],
}
