# -*- coding: utf-8 -*-
"""NERDC-aligned lesson notes — Basic 1 Mathematics, First Term (weeks 1-10).
Each note: {topic, obj, prev, mat, content, ex, act, eval, assign}."""

B1M_T1 = [
 {"topic":"Whole Numbers 1-5 (Counting, Reading and Writing)",
  "obj":["Count objects from 1 to 5 correctly.","Read and write numbers 1 to 5 in figures and words.","Match a number to the correct group of objects."],
  "prev":"Pupils can sing number rhymes and point to objects when asked 'how many?'.",
  "mat":"Counting objects (bottle tops, crayons, beans), number cards 1-5, flash cards with number words, a number chart, the class board.",
  "content":["Numbers tell us how many. We count by pointing to each object once and saying the numbers in order: one, two, three, four, five. After counting, the last number we say is the answer — it tells us how many objects there are in the group.",
   "Each number has a figure (1, 2, 3, 4, 5) and a word (one, two, three, four, five). We can show numbers with our fingers and match a group of three objects to the card that says 3."],
  "ex":["Count the bottle tops: 1, 2, 3 — there are 3 bottle tops. So 3 matches 'three'.","Draw 4 circles in the air as you count: one, two, three, four. The figure is 4.","The teacher shows 5 beans; pupils say 'five' and pick the card that reads 5."],
  "act":["Pupils count their pencils and show the matching number card.","Pairs play 'Show me': one pupil drops 1-5 beans on the table and the partner writes the figure."],
  "eval":["Count aloud from 1 to 5.","Write the figures for: three, one, five, two, four.","How many fingers are on one hand?","Draw 2 apples and write the number."],
  "assign":"Count the chairs, books and windows in your classroom and write the numbers 1 to 5 in your notebook."},

 {"topic":"Whole Numbers 6-10 (Counting, Reading and Writing)",
  "obj":["Count and write numbers 6 to 10.","Order numbers 6 to 10.","Say which group has more objects."],
  "prev":"Pupils can count and write numbers 1 to 5.",
  "mat":"Sticks and beans (10), number cards 6-10, the number chart, a counting string of 10 beads.",
  "content":["After 5 comes 6, then 7, 8, 9 and 10. Ten sticks can be counted one by one; when we have ten objects we can also say we have 'a full set of fingers'. The figures 6, 7, 8, 9 and 10 stand for these amounts.",
   "We compare groups by counting: a group of 8 has more objects than a group of 6, because 8 comes after 6 when we count. Arranging the cards 5, 6, 7, 8, 9, 10 in order is called ordering numbers."],
  "ex":["Count 10 beans: one, two, three, four, five, six, seven, eight, nine, ten.","Which is more: 7 beans or 9 beans? Answer: 9 beans — because 9 is after 7.","Order these numbers: 9, 6, 8 → 6, 8, 9."],
  "act":["Pupils arrange the number cards 6-10 in order on their desks.","The teacher claps 8 times; pupils write 8 and show the card."],
  "eval":["Count and write the numbers from 6 to 10.","Which is bigger: 6 or 10?","Arrange in order: 7, 10, 8, 9.","Write the figure for 'eight'."],
  "assign":"Count 10 objects at home (spoons, cups or stones) and paste or draw them in your notebook with the number 10."},

 {"topic":"Ordering and Comparing Numbers 1-10",
  "obj":["Order numbers from smallest to biggest.","Use the words 'more than', 'less than' and 'equal'.","Identify the biggest and smallest number in a group."],
  "prev":"Pupils can count and write numbers 1 to 10.",
  "mat":"Number cards 1-10, objects for counting, two hoops or trays for sorting, the class board.",
  "content":["When we count, numbers come in a fixed order: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10. The smallest number starts the line and the biggest ends it. A number is 'more than' another if it comes later in the count, and 'less than' if it comes earlier.",
   "Two groups are 'equal' when they have the same number of objects, even if the objects look different. We can compare by matching one object from each group side by side."],
  "ex":["Order: 3, 1, 5 → 1, 3, 5. The smallest is 1 and the biggest is 5.","Compare: 6 and 4 → 6 is more than 4; 4 is less than 6.","Are 8 pencils and 8 erasers equal? Yes — 8 = 8."],
  "act":["Pupils put the number cards in order and point to the smallest and biggest.","Group work: sort mixed objects into two trays and say which tray has more."],
  "eval":["Write 1 to 10 in order.","Circle the smallest: 4, 9, 2.","Circle the biggest: 7, 3, 10.","Write 'more' or 'less': 5 is … than 8."],
  "assign":"Ask a family member for two groups of objects at home. Draw them and write which group has more."},

 {"topic":"Addition of Whole Numbers 1-10 (Putting Together)",
  "obj":["Join two groups and count the total.","Write and read the + (plus) and = (equals) signs.","Add numbers with totals up to 10."],
  "prev":"Pupils can count objects up to 10 and say 'how many?'.",
  "mat":"Objects for counting, number cards, flashcards with + and =, a number line drawn on the board.",
  "content":["Addition means putting two groups together. We join the objects and count all of them; the answer is the total. The plus sign (+) tells us to add, and the equals sign (=) sits before the answer: 2 + 3 = 5 means '2 and 3 put together give 5'.",
   "We can add by counting on: to find 4 + 3, start at 4 and count three more — 5, 6, 7. The total is 7. Any two numbers can be added in any order and the total stays the same: 2 + 3 = 3 + 2."],
  "ex":["2 + 3 = 5: join 2 counters and 3 counters, count all — 5.","Count on: 4 + 3 → 4, 5, 6, 7 → 4 + 3 = 7.","Draw 5 circles and 2 circles; the total is 7 circles: 5 + 2 = 7."],
  "act":["Pupils use beans to show 3 + 4 and say the total.","On the number line, pupils jump from 3 two steps forward to find 3 + 2."],
  "eval":["What does + mean?","Find the total: 4 + 1.","Find the total: 3 + 3.","Draw and add: 5 circles and 4 circles — how many in all?"],
  "assign":"Add these and draw objects to check: 2 + 2, 3 + 5, 6 + 1."},

 {"topic":"Addition 1-10 (More Practice and the Number Line)",
  "obj":["Add numbers using objects and the number line.","Complete simple addition sentences.","Solve simple 'put together' word problems."],
  "prev":"Pupils can add two numbers with totals up to 10.",
  "mat":"Number line, beans and bottle tops, addition flashcards, picture cards of objects.",
  "content":["Practice makes addition quick. Using a number line: start at the first number and jump forward the second number of steps. For 5 + 4, start at 5 and make four jumps — 6, 7, 8, 9 — so the answer is 9.",
   "Word problems tell a story: 'Ada has 2 oranges and Bola has 3 oranges. How many oranges are there altogether?' We look for the joining words — altogether, in all, both — and add."],
  "ex":["Number line: 3 + 2 → start at 3, jump 2 → 5.","6 + 3 = 9 (count on from 6: 7, 8, 9).","'Tunde has 4 balls and gets 2 more. Altogether he has 4 + 2 = 6 balls.'"],
  "act":["Pupils take turns making jumps on the class number line.","Mental addition race: teacher shows a flashcard, pupils say the total."],
  "eval":["Use the number line: 4 + 3.","Complete: 7 + 2 = …","Complete: 5 + 5 = …","A basket has 6 mangoes and 3 more are added. How many mangoes in all?"],
  "assign":"Make your own number line at home and use it to solve 2 + 6 and 4 + 4."},

 {"topic":"Subtraction 1-10 (Taking Away)",
  "obj":["Take away objects and count what remains.","Read and write the − (minus) sign.","Subtract numbers within 10."],
  "prev":"Pupils can count and add numbers up to 10.",
  "mat":"Objects to remove, number cards, flashcards with −, the number line, story pictures.",
  "content":["Subtraction means taking away. When some objects are removed, what is left is the answer. The minus sign (−) tells us to take away: 7 − 3 = 4 means 'start with 7, take away 3, and 4 remain'.",
   "We can subtract by counting back: to find 8 − 2, start at 8 and count backward two steps — 7, 6 — so 8 − 2 = 6. The words 'left', 'remaining', 'gone' and 'how many are left' tell us to subtract."],
  "ex":["Take 2 beans from 5 beans: 1, 2 are removed; 3 remain → 5 − 2 = 3.","Count back: 6 − 4 → 6, 5, 4, 3, 2 → 6 − 4 = 2.","'There are 9 sweets and 5 are eaten. How many are left?' 9 − 5 = 4 sweets."],
  "act":["Pupils remove objects from a group and say the subtraction sentence.","Pairs play 'take away': one pupil removes objects and the partner writes the number sentence."],
  "eval":["What does − mean?","Find: 9 − 4.","Find: 6 − 3.","There are 8 birds; 2 fly away. How many are left?"],
  "assign":"Subtract using beans or stones: 5 − 1, 7 − 4, 10 − 3."},

 {"topic":"Addition and Subtraction Together (1-10)",
  "obj":["Tell addition from subtraction in a sentence.","Solve mixed addition and subtraction within 10.","Use the correct sign (+ or −)."],
  "prev":"Pupils can add and subtract numbers up to 10 separately.",
  "mat":"Counters, number cards, mixed-operation flashcards, the number line.",
  "content":["Sometimes one sum has both addition and subtraction. We work from left to right, one step at a time: first add, then subtract. Example: 5 + 3 − 2 — first 5 + 3 = 8, then 8 − 2 = 6.",
   "Reading the sign carefully is important: + means put together, − means take away. Before answering, pupils should say the sign aloud and decide whether the answer will be bigger or smaller than the first number."],
  "ex":["7 + 2 − 3 → 7 + 2 = 9, then 9 − 3 = 6.","10 − 4 + 1 → 10 − 4 = 6, then 6 + 1 = 7.","Which is bigger: 4 + 4 or 4 − 4? 4 + 4 = 8; 4 − 4 = 0; so 4 + 4 is bigger."],
  "act":["Pupils build each step with counters and say the working aloud.","Sign hunt: the teacher shows a card; pupils say '+' or '−' and solve."],
  "eval":["Solve: 6 + 2 − 1.","Solve: 9 − 3 + 2.","Write the correct sign: 5 … 3 = 8.","A jar has 6 toffees; 2 are given away, then 3 more are added. How many toffees now?"],
  "assign":"Solve with objects: 4 + 4 − 2, 8 − 5 + 3, 3 + 7 − 5."},

 {"topic":"Fractions — Half of a Whole Object",
  "obj":["Share an object into two equal parts.","Identify one half of a shape or object.","Say and write 'half' (1/2)."],
  "prev":"Pupils can count up to 10 and share objects fairly in pairs.",
  "mat":"Oranges, bread or paper shapes, a knife (teacher only) or scissors, half-cards, play dough.",
  "content":["A fraction is a part of a whole. When we divide one whole object into two equal parts, each part is called one half, written 1/2. The parts must be equal — the same size — before we can call them halves.",
   "We see halves everywhere: half an orange, half a loaf of bread, half a sheet of paper folded in two. If we share a sweet between two friends fairly, each friend gets one half."],
  "ex":["A loaf cut into two equal pieces: each piece is one half (1/2).","A paper circle folded in two: each half is 1/2 of the circle.","Two friends share one orange equally → each gets 1/2."],
  "act":["Pupils fold paper shapes into two equal parts and colour one half.","Sharing activity: pupils share a play-dough ball equally in pairs and say 'each of us has one half'."],
  "eval":["What is one half of a whole?","Fold your paper into two equal parts and show one half.","I share one bread between two pupils equally — how much does each get?","Draw a circle and shade one half of it."],
  "assign":"Find two things at home that show one half (e.g., half an orange, a folded paper) and draw them in your notebook."},

 {"topic":"Ordinal Numbers (1st to 10th)",
  "obj":["Say and write the ordinal numbers first to tenth.","Identify positions in a line or race.","Use ordinal numbers to describe order."],
  "prev":"Pupils can count 1 to 10 and know 'first' from everyday use.",
  "mat":"A row of pupils or objects, ordinal cards (1st-10th), pictures of a race, the number chart.",
  "content":["Ordinal numbers tell us the position or order of things: first (1st), second (2nd), third (3rd), fourth (4th), fifth (5th), sixth (6th), seventh (7th), eighth (8th), ninth (9th), tenth (10th).",
   "In a race, the pupil who finishes before all others is first; the next is second, and so on. Ordinal numbers answer the question 'which position?' while counting numbers answer 'how many?'."],
  "ex":["A line of pupils: Ada is 1st, Bola is 2nd, Chidi is 3rd.","In a race: Tunde came 4th — four pupils finished before him? No: three pupils finished before him.","Say the 7th day position in 'Monday to Sunday': Sunday is 7th."],
  "act":["Pupils line up and say their own position: 'I am 5th.'","Ordinal match: pupils match 'third' to the card 3rd and point to the third pupil."],
  "eval":["Say the ordinals from 1st to 5th.","Who is 2nd in your line today?","Write the ordinal for 10.","If you are 8th in a queue, how many pupils are before you?"],
  "assign":"Write the names of five family members in the order of their ages using 1st, 2nd, 3rd, 4th, 5th."},

 {"topic":"Revision and Term Test (First Term)",
  "obj":["Revise counting, writing and ordering of numbers 1-10.","Practise addition and subtraction within 10.","Recall halves and ordinal numbers."],
  "prev":"All topics taught in the first term.",
  "mat":"Number cards, counters, the number line, the class board, a question paper.",
  "content":["This week we revise everything learned in the first term: counting and writing numbers 1-10, ordering and comparing them, adding and subtracting within 10, halves of whole objects, and ordinal numbers 1st-10th.",
   "Pupils should answer quickly and correctly, and check their work: count again before writing a number, read the sign before adding or subtracting, and always ask 'are the parts equal?' when talking about halves."],
  "ex":["Write in figures: nine → 9.","Solve: 6 + 4 = 10 and 10 − 4 = 6.","Which is more: 3 or 8? 8.","Shade one half of a square."],
  "act":["Mixed drills on the board in groups.","Pair quiz: each pair asks two questions and checks the answers with counters."],
  "eval":["Count from 1 to 10 and write them.","Order: 8, 2, 5, 10.","Solve: 4 + 5 and 9 − 3.","What is the 6th ordinal word?"],
  "assign":"Revise all the first-term exercises at home and practise counting objects from 1 to 10."},
]
