# -*- coding: utf-8 -*-
"""NERDC-aligned lesson notes — Basic 1 Mathematics, Second Term (weeks 1-10).

Each note: {topic, obj, prev, mat, content, ex, act, eval, assign}."""

B1M_T2 = [
 {"topic":"Whole Numbers 11-20 (Counting, Reading and Writing)",
  "obj":["Count and write numbers 11 to 20.","Read numbers 11 to 20 in figures and words.","Order numbers 11 to 20."],
  "prev":"Pupils can count, read and write numbers 1 to 10.",
  "mat":"A bead string or sticks grouped in tens, number cards 11-20, the number chart, counting objects (20).",
  "content":["After 10 comes 11, 12, 13, 14, 15, 16, 17, 18, 19 and 20. A group of 10 objects can be tied together as one 'ten', and 11 means 'one ten and one more'; 20 means 'two tens'.",
   "The teens are tricky to spell: eleven, twelve, thirteen, fourteen, fifteen, sixteen, seventeen, eighteen, nineteen, twenty. Pupils should practise writing them in order and matching each word with its figure."],
  "ex":["Count 15 sticks: ten sticks tied together plus five loose ones → 15.","Write in words: 17 → seventeen.","Order: 19, 12, 15 → 12, 15, 19."],
  "act":["Pupils make groups of ten and count on to 20.","Number-card ordering race: pupils arrange 11-20 cards fastest in pairs."],
  "eval":["Count from 11 to 20.","Write the figures for eleven, fifteen, twenty.","Which is bigger: 13 or 18?","Arrange: 14, 11, 20, 16."],
  "assign":"Collect 20 bottle tops at home, count them and write the numbers 11 to 20 in words."},

 {"topic":"Addition of Numbers 11-20",
  "obj":["Add numbers with totals up to 20.","Use counting on to add within 20.","Solve simple addition word problems up to 20."],
  "prev":"Pupils can count and write numbers 11 to 20.",
  "mat":"Counters, a bead string, the number line 0-20, addition flashcards.",
  "content":["Adding up to 20 works the same way as adding up to 10: join the groups and count all, or count on from the bigger number. For 8 + 6, start at 8 and count six more: 9, 10, 11, 12, 13, 14 — so 8 + 6 = 14.",
   "For numbers like 12 + 5, keep the ten and add the ones: 12 is '1 ten and 2 ones'; adding 5 ones gives '1 ten and 7 ones' — 17. This 'split the ten' way makes adding quicker."],
  "ex":["Count on: 8 + 6 = 14.","12 + 5 = 17 (2 + 5 = 7 ones, plus the ten, gives 17).","There are 9 boys and 7 girls in a class — how many pupils? 9 + 7 = 16 pupils."],
  "act":["Pupils add with the bead string, sliding beads to show the total.","Pair flashcard race: who can say the total first?"],
  "eval":["Solve: 7 + 5.","Solve: 13 + 4.","Count on from 9 to find 9 + 8.","A farmer has 11 yams and harvests 6 more. How many yams altogether?"],
  "assign":"Use stones or beans to find: 6 + 9, 15 + 3, 12 + 6."},

 {"topic":"Subtraction of Numbers 11-20",
  "obj":["Subtract numbers within 20.","Use counting back to subtract.","Solve subtraction word problems up to 20."],
  "prev":"Pupils can add within 20 and subtract within 10.",
  "mat":"Counters, the number line 0-20, subtraction flashcards, story pictures.",
  "content":["Subtracting within 20 means taking away from groups bigger than 10. Counting back works: for 15 − 6, start at 15 and count six steps back — 14, 13, 12, 11, 10, 9 — so 15 − 6 = 9.",
   "Another way: split the number. 15 − 5 = 10, then take away 1 more → 9. Knowing our 'take away from ten' facts (10 − 1 = 9, 10 − 2 = 8…) makes bigger subtractions easy."],
  "ex":["Count back: 14 − 5 → 13, 12, 11, 10, 9 → 14 − 5 = 9.","Split: 16 − 7 → 16 − 6 = 10, then 10 − 1 = 9.","There are 18 pupils; 5 have gone to the library. How many remain? 18 − 5 = 13."],
  "act":["Pupils act the story with counters: 'start with 17, take away 8.'","Number-line jumps in pairs — one jumps, one records."],
  "eval":["Solve: 13 − 4.","Solve: 20 − 7.","Count back from 17 to find 17 − 8.","Bola has 15 sweets and gives away 6. How many sweets are left?"],
  "assign":"Find with objects: 11 − 3, 18 − 9, 16 − 7."},

 {"topic":"Money — Identification of Coins and Notes",
  "obj":["Identify Nigerian coins and notes.","Know the value of common coins and notes.","Match coins and notes to their values."],
  "prev":"Pupils have seen money at home and in the market.",
  "mat":"Real or play coins and notes (50k, ₦1, ₦2, ₦5, ₦10, ₦20, ₦50, ₦100), pictures of money, a market picture.",
  "content":["Money is what we use to buy things. In Nigeria we use naira and kobo; 100 kobo (k) make 1 naira (₦1). Coins include 50k, ₦1, ₦2; notes include ₦5, ₦10, ₦20, ₦50, ₦100 and more.",
   "Every coin and note has its value written on it. We must look carefully at the number and the colour so we do not confuse ₦100 with ₦10. Money is kept clean, and we count it carefully before we spend it."],
  "ex":["A 50k coin is worth half of ₦1 — two of them make ₦1.","A ₦100 note has '100' printed on it; five of them make ₦500.","Which is worth more: a ₦10 note or a ₦20 note? The ₦20 note."],
  "act":["Show-and-tell: pupils name each coin or note and say its value.","Money shop: pupils sort mixed play money into piles of the same value."],
  "eval":["How many kobo make ₦1?","Name the coins you know.","Which note is bigger: ₦50 or ₦100?","Draw a ₦20 note and write its value."],
  "assign":"Look at the money used in your home and draw three different notes or coins with their values."},

 {"topic":"Money — Shopping and Change (Simple)",
  "obj":["Add small amounts of money.","Pay with coins and receive change.","Solve simple money problems in the classroom shop."],
  "prev":"Pupils can identify coins and notes and add within 20.",
  "mat":"Play money, price tags (₦2, ₦5, ₦10, ₦20), a classroom shop corner, small items with price cards.",
  "content":["Buying and selling uses addition and subtraction of money. If an item costs ₦5 and we pay ₦10, the change is ₦10 − ₦5 = ₦5. Change is the money returned after we pay more than the price.",
   "In our classroom shop, every item has a price tag. We choose an item, count out the money, and work out the change together: price + change = money paid."],
  "ex":["A pencil costs ₦5; you pay ₦10 → change ₦5.","A sweet costs ₦2 and a biscuit costs ₦3 → ₦2 + ₦3 = ₦5 altogether.","You have ₦20 and buy a book for ₦12 → ₦20 − ₦12 = ₦8 change."],
  "act":["Pupils take turns to be shopkeeper and buyer in the classroom shop.","Change challenge: teacher shows the price and the money paid; pupils say the change."],
  "eval":["A bag costs ₦10. You pay ₦20. What is your change?","Add: ₦3 + ₦4.","You have ₦15 and buy a drink for ₦10. How much is left?","Why do we count our change carefully?"],
  "assign":"With play or real coins, show: ₦6 + ₦4 and the change from ₦20 for a ₦13 item."},

 {"topic":"Length — Comparing Objects (Long, Short, Tall, Big, Small)",
  "obj":["Compare objects by length.","Use 'longer/shorter' and 'taller/shorter' correctly.","Arrange objects from the longest to the shortest."],
  "prev":"Pupils can sort objects by size (big/small).",
  "mat":"Pencils, sticks, ropes of different lengths, pupils themselves, pictures of tall and short things.",
  "content":["Length tells us how long something is. To compare, we place the objects side by side, starting from the same line, and look which one ends further. The one that ends further is longer or taller.",
   "Words to use: longer, shorter, taller, longest, shortest. 'Tall' is for things that stand up (a tree, a pupil); 'long' is for things that lie flat (a rope, a pencil). A child is taller than a baby but shorter than an adult."],
  "ex":["Two ropes: place them together — rope A ends further; A is longer.","Order three pencils from the longest to the shortest.","Ada is taller than Bola but shorter than Chidi."],
  "act":["Pupils stand in pairs and say who is taller and who is shorter.","Station work: pupils arrange sticks, ropes and pencils from longest to shortest."],
  "eval":["Which is longer — a pencil or a ruler?","Use 'taller' in a sentence.","Arrange: rope B (long), rope A (short), rope C (longer).","How do we compare two ropes fairly?"],
  "assign":"Find three objects at home. Arrange them from the longest to the shortest and draw them."},

 {"topic":"Capacity — Full, Empty, More and Less",
  "obj":["Use the words full, empty, half-full, more and less.","Compare containers by how much they hold.","Say which container holds more liquid."],
  "prev":"Pupils can compare objects by size and length.",
  "mat":"Cups, bowls, bottles, buckets, a water trough or sand tray, jugs and funnels.",
  "content":["Capacity is how much a container can hold. A container is 'full' when nothing more can be added, 'empty' when it holds nothing, and 'half-full' in between. The words 'more' and 'less' compare how much two containers hold.",
   "To compare, we pour from one container into the other, or count how many small cups fill each big container: a bucket holds more cups of water than a cup does — the bucket has a bigger capacity."],
  "ex":["A bottle is filled to the top — it is full.","Fill a cup with sand: the cup holds one cup of sand; the bowl holds five cups → the bowl holds more.","Which holds less: a bucket or a cup? A cup."],
  "act":["Pouring station: pupils fill and empty containers and say 'full', 'empty' or 'half-full'.","How many cups fill it? — pupils count cupfuls to fill two different containers and compare."],
  "eval":["What does 'full' mean?","Which holds more: a spoon or a jug?","Fill a cup with sand — is it full or empty?","Name a container at home that is bigger than a cup."],
  "assign":"At home, fill a small cup and a big bowl with water (with an adult beside you). Count the cupfuls and tell which holds more."},

 {"topic":"Weight — Heavy and Light",
  "obj":["Use the words heavy and light.","Compare two objects by weight using hands or a balance.","Order objects from the lightest to the heaviest."],
  "prev":"Pupils can compare by size, length and capacity.",
  "mat":"Objects of different weights (stone, sponge, book, feather, pencil), a simple balance or seesaw, a bucket of sand.",
  "content":["Weight tells us how heavy something is. 'Heavy' and 'light' describe weight, not size — a big sponge is light, a small stone is heavy. We can feel weight in our hands by holding one object in each palm.",
   "A balance compares two objects: the side that goes down holds the heavier object, and the side that rises holds the lighter one. When both sides stay level, the objects weigh the same."],
  "ex":["Hold a stone in one hand and a sponge in the other: the stone feels heavier.","On the balance, the book side goes down → the book is heavier than the eraser.","Order: feather (lightest), pencil, stone (heaviest)."],
  "act":["Feely bags: pupils pick two objects and say which is heavier.","Balance work in groups: pupils test pairs of objects and record 'heavier' or 'lighter'."],
  "eval":["Which is heavier: a book or a pencil?","Which is lighter: a stone or a feather?","What does a balance show when one side goes down?","Can something big be light? Give one example."],
  "assign":"Find five objects at home. Hold them in your hands and write 'heavy' or 'light' for each."},

 {"topic":"Time — Days of the Week and Months of the Year",
  "obj":["Name the days of the week in order.","Name the months of the year in order.","Say what we do in the morning, afternoon and night."],
  "prev":"Pupils know morning, afternoon and night from home routines.",
  "mat":"A class calendar, day and month cards, a chart of the week, pictures of daily activities.",
  "content":["The seven days of the week are: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday. Days follow one another in the same order; the days we come to school are Monday to Friday.",
   "The twelve months of the year are: January, February, March, April, May, June, July, August, September, October, November, December. Each month has its name and its place in the year; our birthdays and school holidays fall in particular months."],
  "ex":["The first day of the school week is Monday; the week ends on Sunday.","The month after January is February; December is the last month.","We sleep at night, we learn in the morning, and we play in the afternoon."],
  "act":["Pupils arrange the day cards in order and chant the days.","Month train: pupils hold month cards and line up from January to December."],
  "eval":["Name the days of the week in order.","Which day comes after Wednesday?","Name the first and last months of the year.","When do you go to school?"],
  "assign":"Write the seven days of the week and circle the day of your birthday this month."},

 {"topic":"Revision and Term Test (Second Term)",
  "obj":["Revise numbers 11-20, addition and subtraction within 20.","Revise money, length, capacity, weight and time.","Sit and complete the end-of-term test correctly."],
  "prev":"All topics taught in the second term.",
  "mat":"Number cards 11-20, play money, a balance, containers, a question paper.",
  "content":["This week we revise the whole second term: numbers 11-20, adding and subtracting within 20, money (coins, notes and change), length, capacity, weight and time. Every topic ended with the same question — 'how many?' or 'which is more?' — and pupils should look for the clue words.",
   "In the test, read each question twice, work carefully, and check your answers before you hand in your paper. Show your working with drawings where the question asks you to."],
  "ex":["Order: 20, 13, 17 → 13, 17, 20.","Solve: 15 + 4 = 19 and 19 − 9 = 10.","A ₦20 note and a ₦5 note → ₦25 altogether.","Which holds more — a cup or a bucket? A bucket."],
  "act":["Mixed drills around the room in stations (number, money, measures).","Pair revision quiz — each pair asks two questions from any topic."],
  "eval":["Write in figures: sixteen, twelve, twenty.","Solve: 9 + 8 and 17 − 6.","An apple costs ₦6; you pay ₦10 — what is your change?","Say one thing heavier than a book and one day after Friday."],
  "assign":"Revise all second-term exercises at home and share one new thing you learned with your family."},
]
