# -*- coding: utf-8 -*-
"""NERDC-aligned lesson notes — Basic 1 Mathematics, Third Term (weeks 1-10).

Each note: {topic, obj, prev, mat, content, ex, act, eval, assign}."""

B1M_T3 = [
 {"topic":"Whole Numbers 1-50 (Counting, Reading and Writing)",
  "obj":["Count objects up to 50.","Read and write numbers to 50 in figures.","Say what comes before and after a number."],
  "prev":"Pupils can count, read and write numbers 11 to 20.",
  "mat":"Beans, counters, a 1-50 number chart, number cards, bundles of ten sticks.",
  "content":["We can count past 20 to 30, 40 and 50. Numbers are grouped in tens: 20, 21, 22… 30, 31, 32… up to 50. Counting on from any number — 'twenty-three, twenty-four, twenty-five' — follows a steady pattern.",
   "The number chart helps us see the pattern: each row adds one ten. Pupils should practise finding 'what comes before' and 'what comes after' any number up to 50, and reading the numbers aloud."],
  "ex":["Count beans: 20, 21, 22, 23, 24, 25 → 25 beans.","What comes after 39? 40. What comes before 50? 49.","34 is 'three tens and four ones'."],
  "act":["Pupils count and bundle sticks in tens, then count on.","Number chart hunt: teacher calls '46'; pupils point to and circle it."],
  "eval":["Count from 20 to 30.","Write the figures for thirty-five and forty-two.","What comes after 29? Before 31?","Show 27 with your sticks."],
  "assign":"Count 50 objects at home (beans, stones or bottle tops) and write the numbers from 30 to 50."},

 {"topic":"Counting in Twos, Fives and Tens",
  "obj":["Count in twos up to 20.","Count in fives up to 50.","Count in tens up to 100."],
  "prev":"Pupils can count and write numbers up to 50.",
  "mat":"Objects in groups of 2, 5 and 10, number charts, hundreds chart, counting sticks.",
  "content":["Skip counting means counting in steps instead of one by one. Counting in twos: 2, 4, 6, 8, 10… We say every second number. Counting in fives: 5, 10, 15, 20… Counting in tens: 10, 20, 30, 40… to 100.",
   "Skip counting is faster, and it prepares us for multiplication: two shoes, five fingers on one hand, ten fingers on two hands. Pupils should chant the patterns aloud and point to the numbers on the chart."],
  "ex":["Count in twos: 2, 4, 6, 8, 10, 12, 14.","Count in fives: 5, 10, 15, 20, 25, 30.","Count in tens: 10, 20, 30, 40, 50, 60, 70, 80, 90, 100."],
  "act":["Clap and count: pupils clap twice, four times, six times and say the pattern.","Group work: pupils make groups of 5 beans and count in fives."],
  "eval":["Count in twos to 20.","Count in fives to 30.","Count in tens to 100.","How many fingers on 2 hands? Count in fives."],
  "assign":"Count in twos the shoes in your home and in fives the fingers of five people."},

 {"topic":"Addition and Subtraction of Money",
  "obj":["Add small amounts of naira.","Subtract to find change.","Solve shop problems with naira up to ₦20."],
  "prev":"Pupils can identify money, add within 20 and count in fives and tens.",
  "mat":"Play money, price tags, a classroom shop, addition and subtraction cards with ₦.",
  "content":["Money problems use the same addition and subtraction we already know — we simply write the naira sign (₦) in the answer. Prices and payments are added, and change is found by subtracting the price from the money paid.",
   "In the classroom shop, pupils practise realistic buying: two items together cost the sum of their prices, and paying with a bigger note means counting out the change."],
  "ex":["A pen costs ₦7 and a book costs ₦8 → ₦7 + ₦8 = ₦15.","You pay ₦20 for a ₦13 toy → ₦20 − ₦13 = ₦7 change.","₦10 + ₦5 = ₦15; ₦20 − ₦5 = ₦15."],
  "act":["Shop play: buyers add two prices and work out change.","Price flash: teacher shows two price cards; pupils add them quickly."],
  "eval":["Add: ₦6 + ₦9.","A sweet costs ₦4; you pay ₦10. What is your change?","You have ₦20 and spend ₦15. How much is left?","Why is the ₦ sign important in a money answer?"],
  "assign":"Draw a small shop corner and price three items; then write one addition and one change sum for them."},

 {"topic":"Multiplication as Repeated Addition (2s, 5s and 10s)",
  "obj":["Show multiplication as repeated addition.","Write and read the × (times) sign.","Find totals for the 2, 5 and 10 times tables."],
  "prev":"Pupils can count in twos, fives and tens.",
  "mat":"Objects in equal groups, number charts, flashcards with ×, the hundreds chart.",
  "content":["Multiplication is fast repeated addition of equal groups. '3 groups of 2' is 2 + 2 + 2 = 6, and we write it 3 × 2 = 6. The × sign means 'groups of'. Equal groups are important — each group must hold the same number.",
   "The 2, 5 and 10 tables come straight from our skip counting: 2, 4, 6… is the 2-times table; 5, 10, 15… is the 5-times; 10, 20, 30… is the 10-times. Drawing the groups helps us check the answer."],
  "ex":["4 groups of 2: 2 + 2 + 2 + 2 = 8 → 4 × 2 = 8.","3 groups of 5: 5 + 5 + 5 = 15 → 3 × 5 = 15.","2 groups of 10: 10 + 10 = 20 → 2 × 10 = 20."],
  "act":["Pupils form equal groups with beans and write both the addition and the multiplication.","Times-table chant with claps for the 2s, 5s and 10s."],
  "eval":["Write 3 × 2 as repeated addition.","Find: 4 × 5.","Find: 2 × 10.","How many fingers do 3 pupils have? Write it as multiplication."],
  "assign":"Draw 4 groups of 5 oranges and write the addition and the multiplication sentence."},

 {"topic":"Fractions — Halves and Quarters",
  "obj":["Identify one half and one quarter of a whole.","Share objects into two and four equal parts.","Say and write 1/2 and 1/4."],
  "prev":"Pupils know one half of a whole object from the first term.",
  "mat":"Oranges, bread, paper shapes, play dough, scissors (teacher only), fraction cards.",
  "content":["When a whole is divided into two equal parts, each part is one half (1/2). When it is divided into four equal parts, each part is one quarter (1/4). Two halves make a whole; four quarters make a whole.",
   "Sharing fairly in groups shows fractions: sharing one orange between two friends gives each a half; sharing it among four friends gives each a quarter. The parts must always be equal."],
  "ex":["A bread cut into 2 equal parts → each part is 1/2.","A square folded into 4 equal parts → each part is 1/4.","2 quarters = 1 half; 4 quarters = 1 whole."],
  "act":["Pupils fold paper shapes into halves and quarters and label them.","Fair-sharing: pupils share play dough among 2 and then 4 members of their group."],
  "eval":["How many equal parts make a half? A quarter?","Fold your paper to show one quarter and shade it.","Share one orange among 4 pupils fairly — what does each get?","Which is bigger: 1/2 or 1/4 of the same bread?"],
  "assign":"Ask an adult to cut one bread into 4 equal parts. Draw the bread and label each part 1/4."},

 {"topic":"Length — Measuring with Paces and Cubes",
  "obj":["Measure length with paces.","Measure length with cubes or matchsticks.","Say which object is longer from the measurements."],
  "prev":"Pupils can compare objects by length.",
  "mat":"The classroom floor, chalk, cubes, matchsticks, pencils, a measuring tape (teacher).",
  "content":["We can measure length with things around us before we learn the ruler. Walking heel-to-toe across the room counts paces; laying cubes end to end counts cubes. The answer is a number plus the unit: 'the table is 8 paces long' or 'the pencil is 6 cubes long'.",
   "We must measure fairly: start from the same end, lay the cubes touching without gaps, and count each one once. The same unit must be used for both objects before we compare them."],
  "ex":["The door is 4 paces wide; the window is 3 paces wide → the door is wider.","A pencil is 6 cubes long; a crayon is 4 cubes long → the pencil is longer.","A table is 10 cubes long; count: 1, 2, 3… 10 cubes."],
  "act":["Pupils pace the length of the classroom and the corridor.","Measuring stations: pupils measure pencils, books and the table with cubes and record the counts."],
  "eval":["What unit did we use to measure the door?","Measure your desk with cubes and say the length.","Which is longer: 8-cube rope or 5-cube rope?","Why must cubes touch end to end?"],
  "assign":"Measure three things at home with your foot or with matchsticks and write the lengths."},

 {"topic":"Data — Sorting, Counting and Simple Tables",
  "obj":["Sort objects into groups.","Count each group and record the numbers.","Read and complete a simple table."],
  "prev":"Pupils can count up to 50 and sort objects by size and colour.",
  "mat":"Mixed objects (colour crayons, shapes, toy cars), hoops, a simple table drawn on the board, tally cards.",
  "content":["Data means information we collect. We collect it by sorting things into groups — by colour, shape or type — and counting each group. Each count is a piece of data.",
   "A table arranges the data neatly: one column names the group and the other shows how many. Reading the table tells us at a glance which group has the most and which has the fewest."],
  "ex":["Sort crayons: red (3), blue (5), green (2) → blue is the most.","Table: Cars 6, Balls 4, Dolls 5 → cars are the most.","Which group has the fewest? Balls, with 4."],
  "act":["Sorting lab: pupils sort mixed objects into hoops and count each group.","Table builders: pupils fill the class table for 'our favourite fruit'."],
  "eval":["What is data?","Sort the crayons in your box and count each colour.","In the car/ball/doll table, which group has the most?","Why is a table helpful?"],
  "assign":"At home, sort the shoes in your family by colour and draw a table of the counts."},

 {"topic":"Shapes and Patterns (Circle, Square, Triangle, Rectangle)",
  "obj":["Name and recognise circle, square, triangle and rectangle.","Sort shapes by their look.","Copy and continue simple patterns of shapes."],
  "prev":"Pupils can sort objects by colour and size.",
  "mat":"Shape cut-outs, objects that are round or square in the class, shape cards, coloured beads.",
  "content":["Shapes are all around us. A circle is round with no corners (a clock, a coin); a square has four equal sides and four corners; a triangle has three sides and three corners; a rectangle has four sides — two long and two short (a book, a door, a window).",
   "A pattern is a repeated order: circle, square, circle, square… After we see the repeating part, we can continue the pattern and say what comes next."],
  "ex":["A coin is a circle; the window frame is a rectangle; a slice of bread may be a square.","Sort: ⬤▲⬤▲ — what comes next? A circle? No — the pattern repeats circle, triangle, so next is circle.","A door is a rectangle — it has 4 corners."],
  "act":["Shape hunt: pupils find and name shapes in the classroom.","Pattern beads: pupils copy and continue a bead pattern, then make their own."],
  "eval":["Name a shape with 3 sides.","Name a shape with no corners.","What shape is a book cover?","Continue the pattern: ⬤ ▲ ⬤ ▲ ⬤ …"],
  "assign":"Draw a circle, a square, a triangle and a rectangle, and find one object at home that matches each."},

 {"topic":"Review and Word Problems (One-Step)",
  "obj":["Read and understand simple word problems.","Choose the right operation (add or subtract).","Solve one-step problems and show the working."],
  "prev":"Pupils can add, subtract and count in groups.",
  "mat":"Word-problem cards, counters, the number line, the class board.",
  "content":["A word problem tells a story with a question. The clue words help us choose the operation: 'altogether', 'in all' and 'more' point to addition; 'left', 'remain' and 'given away' point to subtraction.",
   "To solve: 1) read the story twice, 2) find the numbers and the question, 3) choose the operation, 4) work it out, 5) write the answer with its unit — 'Ada has 4 sweets and gets 3 more: altogether she has 7 sweets.'"],
  "ex":["Ada has 4 sweets and gets 3 more → 4 + 3 = 7 sweets.","There are 9 pupils; 2 are absent → 9 − 2 = 7 pupils present.","A tray holds 5 rows of 2 biscuits → 5 × 2 = 10 biscuits (count in twos)."],
  "act":["Story cards in pairs: read, solve, and exchange cards.","Pupils act the problem with counters while the class solves it."],
  "eval":["What word tells us to add?","What word tells us to subtract?","Bola has 6 books and buys 4 more. How many books?","There are 10 eggs; 3 break. How many are left?"],
  "assign":"Write one addition and one subtraction story from your home and solve them."},

 {"topic":"Revision and Term Test (Third Term)",
  "obj":["Revise numbers to 50, skip counting and multiplication.","Revise money, fractions, length, data, shapes and word problems.","Sit and complete the third-term test correctly."],
  "prev":"All topics taught in the third term.",
  "mat":"Number chart to 50, play money, shape cards, counting objects, a question paper.",
  "content":["This week we revise the whole third term: numbers to 50, counting in twos, fives and tens, multiplication as repeated addition, halves and quarters, measuring length, data tables, shapes and patterns, and one-step word problems.",
   "For the test: read every question twice, do the easy ones first, and always show your working. Check your answers — count your objects again and re-read the question before you finish."],
  "ex":["What comes after 49? 50.","Count in fives: 5, 10, 15, 20, 25.","3 × 5 = 15 (5 + 5 + 5).","One quarter of a bread shared among 4 pupils: each gets 1/4."],
  "act":["Revision stations: number, shop, shapes and measure.","Whole-class rapid quiz on the term's key facts."],
  "eval":["Write 37 in words.","Find: 6 × 2.","You pay ₦20 for a ₦12 book — what is your change?","Draw a rectangle and shade one quarter."],
  "assign":"Revise all the third-term exercises and bring one question of your own to the next lesson."},
]
