# -*- coding: utf-8 -*-
"""Revision notes ("formula & fact cards") — compact per-topic cards keyed by
the app's own TOPICS topic names (validated against template.html at build).
Each card is one terse line: the facts and formulas examiners reward."""

NOTES = {
"Mathematics": {
 "Number & Algebra": "Quadratic: x = (-b ± √(b²-4ac))/2a. AP: a+(n-1)d. GP: ar^(n-1). Laws: a^m×a^n = a^(m+n); a^m÷a^n = a^(m-n); (a^m)^n = a^mn; a^0 = 1. Sets: n(A∪B) = n(A)+n(B)-n(A∩B).",
 "Geometry & Trigonometry": "Angles of a triangle sum 180°. Pythagoras: a²+b² = c². SOH-CAH-TOA: sin = opp/hyp, cos = adj/hyp, tan = opp/adj. Sine rule: a/sinA = b/sinB. Angle in a semicircle = 90°.",
 "Mensuration": "Circle: A = πr², C = 2πr. Triangle ½bh, trapezium ½(a+b)h. Prism V = base × height. Cylinder V = πr²h. Cone V = ⅓πr²h. Sphere V = 4/3πr³, SA = 4πr². 1 m³ = 1000 L.",
 "Statistics & Probability": "Mean = sum ÷ n. Median = middle (ordered). Mode = most frequent. Range = max − min. P = favourable ÷ total; 0 ≤ P ≤ 1. Mutually exclusive: add. Independent: multiply.",
 "Functions & Graphs": "y = mx + c: m = gradient, c = intercept. Parallel: equal m. Perpendicular: m₁m₂ = −1. Substitute into f(x). Distance = speed × time.",
 "Word Problems": "% change = (change ÷ original) × 100. Simple interest = PRT/100. Compound: A = P(1 + r/100)^n. Ratio: divide by total parts. Speed = distance ÷ time.",
},
"English Language": {
 "Grammar": "8 parts of speech: noun, pronoun, verb, adjective, adverb, preposition, conjunction, interjection. Subject–verb agreement. Perfect tense: have/has + past participle.",
 "Vocabulary & Spelling": "Synonym = same; antonym = opposite. Homophones sound alike, differ in spelling. 'i before e except after c'. Double the final consonant (run → running).",
 "Sentence Structure": "Simple = 1 clause; compound = 2 main clauses; complex = main + subordinate. Comma separates; semicolon joins related clauses; colon introduces a list.",
 "Oral & Phonetics": "Vowel and consonant sounds; diphthong = two vowels gliding (boy, how). Word stress: REcord / reCORD. Rising intonation = question; falling = statement.",
 "Expression & Usage": "Idioms are figurative ('break the ice' = start talking). Phrasal verb = verb + particle (give up = quit). Collocations: 'make a decision'. Register = formal/informal.",
 "Reading & Comprehension": "Main idea = whole passage. Inference = implied conclusion. Tone = writer's attitude. Skim for gist; scan for details.",
},
"Biology": {
 "Cells & Organisation": "All life is made of cells. Nucleus = DNA; mitochondria = respiration; ribosomes = protein. Diffusion: down a concentration gradient. Osmosis: water across a membrane. Mitosis → 2 identical cells.",
 "Ecology & Environment": "Ecosystem = biotic + abiotic. Food chain: producer → consumers. ~10% of energy passes per level. Nitrogen cycle: nitrogen-fixing bacteria + legumes. Pollution: air, water, land, noise.",
 "Genetics & Evolution": "DNA = double helix. Gene = one characteristic; allele = its form. Monohybrid cross ratio 3:1. Punnett square predicts offspring. Mutation = change in DNA; natural selection favours the adapted.",
 "Plant Biology": "6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂ (light, chlorophyll). Transpiration pulls water up xylem. Root hairs absorb. Stomata take in CO₂. Germination: water, air, warmth.",
 "Human & Animal Physiology": "Enzymes: amylase → sugar; protease → amino acids; lipase → fatty acids. Blood: plasma, RBC (oxygen), WBC (immunity), platelets (clotting). Double circulation. Insulin controls sugar.",
 "Health & Diseases": "Malaria: Plasmodium, female Anopheles mosquito. HIV: blood/body fluids, not casual contact. Balanced diet: carbs, protein, fat, vitamins, minerals, fibre, water. Vaccines build immunity.",
},
"Chemistry": {
 "Atomic Structure & Bonding": "Proton (+) and neutron (0) in the nucleus; electrons in shells. Atomic number = protons; mass number = p + n. Isotopes: same p, different n. Ionic = electron transfer; covalent = sharing.",
 "Acids, Bases & Salts": "Acid pH < 7, alkali > 7, neutral 7. Acid + base → salt + water. Acid + metal → salt + H₂. Litmus: red acid, blue alkali. Salts: NaCl, CuSO₄, CaCO₃.",
 "Chemical Reactions & Equations": "Mass conserved — balance equations. OIL RIG: oxidation loses electrons, reduction gains. Catalyst speeds a reaction, unchanged. Exothermic releases heat; endothermic absorbs.",
 "Separation & Mixtures": "Filtration: insoluble solids. Distillation: boiling points. Chromatography: dyes in a solvent. Evaporation recovers a dissolved solid. Decantation: pour off the liquid.",
 "Organic Chemistry": "Hydrocarbons: C and H only. Alkanes CnH2n+2 (saturated); alkenes CnH2n, C=C (decolourise bromine water). Alcohols: −OH. Combustion → CO₂ + H₂O. Polymers from monomers.",
 "Physical Chemistry": "P₁V₁ = P₂V₂ (fixed T, mass). Solubility of solids rises with temperature. n = mass ÷ molar mass. Electrolysis uses current. Rate ↑ with temperature, concentration, surface area, catalyst.",
},
"Physics": {
 "Mechanics & Motion": "v = u + at; F = ma; W = mg (g ≈ 10); p = mv; W = Fd; KE = ½mv²; PE = mgh; P = W/t. MA = load ÷ effort; efficiency = (output ÷ input) × 100%.",
 "Heat & Thermodynamics": "Q = mcΔθ; Q = mL at a state change. Conduction (solids), convection (fluids), radiation (vacuum). Solids expand when heated. Thermometers: mercury/alcohol in a capillary tube.",
 "Electricity & Magnetism": "V = IR. Series: R = R₁ + R₂. Parallel: 1/R = 1/R₁ + 1/R₂. P = IV; E = Pt. Like poles repel, unlike attract; field lines N → S. Electromagnet: coil + core + current.",
 "Waves & Optics": "v = fλ. Reflection: angle in = angle out. Refraction: light bends on changing speed. Convex converges; concave diverges. Sound (longitudinal) ≈ 330 m/s; light (transverse) = 3 × 10⁸ m/s.",
 "Pressure & Fluids": "P = F/A (Pa). Liquid pressure = hρg. ρ = mass ÷ volume. Upthrust = weight of displaced fluid (Archimedes). Float if less dense than the fluid.",
 "Modern Physics & Measurement": "Alpha: heavy, +, stopped by paper. Beta: light, −, stopped by aluminium. Gamma: waves, needs lead. Half-life = time for half to decay. SI: m, kg, s, A, K, mol, cd.",
},
"Agricultural Science": {
 "Soil & Crop Production": "Sandy (drains), clay (holds water), loam (best). NPK: nitrogen = leaves, phosphorus = roots, potassium = fruit. Manure improves soil; fertiliser feeds it. Tillage prepares a seedbed; rotation keeps fertility.",
 "Animal Production": "Cattle, goats, sheep, poultry, pigs. Feeds: concentrate (energy/protein) + roughage (fibre). Housing: ventilation, drainage, space. Ruminants have a 4-chambered stomach.",
 "Farm Management & Economics": "Factors: land, labour, capital, management. Records: income, expenditure, inventory, production. Costs: fixed and variable. Break-even covers cost.",
 "Technology & Processing": "Mechanisation: tractors speed work. Irrigation: surface, sprinkler, drip. Storage: drying, silos, cribs. Preservation: canning, salting, smoking, drying.",
 "Ecology & Environment": "Rotational grazing protects pasture. Forest reserves conserve water and wildlife. Erosion control: cover crops, mulch, contour ploughing. Sustainable use of land and water.",
 "Genetics & Improvement": "Selection keeps the best breeders. Hybridisation → hybrid vigour. Cross-breeding combines traits (disease resistance, yield). Improved varieties grow faster, produce more.",
},
"Economics": {
 "Basic Concepts & Theory": "Scarcity → choice; opportunity cost = next best alternative forgone. Demand falls as price rises; supply rises. Equilibrium: demand = supply.",
 "Market Structures & Price": "Perfect competition: many small sellers. Monopoly: one seller, price maker. Oligopoly: few large sellers. Surplus pushes price down; shortage pushes it up.",
 "Money & Banking": "Money: medium of exchange, store of value, unit of account. Barter needs a double coincidence of wants. Central bank issues currency; commercial banks take deposits, give loans.",
 "National Income & Trade": "GDP = output at home; GNP = GDP + net foreign income. Exports earn, imports spend. Balance of payments = trade + transfers. Circular flow: households ↔ firms.",
 "Public Finance & Development": "Direct tax: income, company. Indirect: VAT, customs. Budget surplus: revenue > spending; deficit: spending > revenue. Development: income, health, education, infrastructure.",
 "Production & Business": "Factors: land, labour, capital, entrepreneur. Division of labour raises output. Total cost = fixed + variable. Profit = revenue − total cost.",
},
"Government": {
 "Concepts & Principles": "Sovereignty = supreme state power. Constitution: the rules of government. Separation of powers: executive, legislature, judiciary. Rule of law: everyone is under the law.",
 "Democracy & Elections": "Democracy: government by the people. Elections: peaceful choice of leaders; universal adult suffrage. Free and fair: independent commission, secret ballot. Parties contest on manifestos.",
 "Nigerian Government & History": "Amalgamation 1914; independence 1960; republic 1963; civilian rule 1999. Federalism divides power centre ↔ states. States and local governments created over time.",
 "Public Administration": "Civil service implements policy. Ministers (political) + permanent secretaries (career). Public corporations: power, rail, water. Bureaucracy: hierarchy, rules, records.",
 "Political Parties & Pressure Groups": "Parties seek power; pressure groups influence policy (unions, bodies). Mass, cadre, one-party, multi-party. Opposition checks the ruling party.",
 "International Relations": "UN 1945: peace and security; Security Council: 5 permanent members. AU 2002 (OAU 1963). ECOWAS 1975: West African integration. Diplomacy and treaties.",
},
"Literature in English": {
 "Poetry": "Stanza = group of lines. Rhyme: end sounds. Metre: rhythm. Imagery = word pictures. Simile (like/as); metaphor (is). Ballad = narrative poem in short stanzas.",
 "Prose & Fiction": "Novel = long prose fiction. Plot: exposition → rising action → climax → resolution. Protagonist/antagonist; round vs flat characters. Narrator: first or third person. Setting = time + place.",
 "Drama": "Play: written for performance; acts → scenes. Tragedy: serious, hero's downfall. Comedy: light, happy. Dialogue + stage directions. Playwright writes; actors perform.",
 "Literary Terms & Devices": "Metaphor (A is B), simile (A like B), personification, irony, symbolism, foreshadowing, onomatopoeia. Theme = central idea.",
 "African Literature": "Oral tradition: folktales, proverbs, riddles, songs, myths. The griot preserves history and culture. Modern African writing: colonialism, identity, tradition vs change.",
 "Comprehension & Analysis": "Identify theme, tone, purpose (inform, persuade, entertain), point of view. Support every claim with evidence. Use context clues for unfamiliar words.",
},
"Geography": {
 "Physical Geography": "Landforms: mountains, plains, plateaus. Erosion by water, wind, ice. Plate tectonics: volcanoes and earthquakes at boundaries. Rivers: erosion → transport → deposition (deltas).",
 "Climate & Weather": "Climate = average weather; weather = day to day. Convectional (afternoon storms), orographic (hills), cyclonic (fronts) rainfall. Equatorial: hot, wet all year. Desert: hot, dry.",
 "Human & Economic Geography": "Density = people ÷ area. Growth = births − deaths ± migration. Push (war, poverty) and pull (jobs, safety). Nucleated, linear, dispersed settlements.",
 "Cartography & Maps": "Latitude: parallels (N/S). Longitude: meridians (E/W). Scale 1:50 000 → 1 cm = 500 m. Contours: close = steep. Bearings clockwise from north.",
 "Regional Geography": "Nigeria: West Africa, Gulf of Guinea; Niger and Benue rivers. Sahel in the north, forest in the south. Farming, mining, fishing, trade.",
 "Environmental Issues": "Desertification: the Sahel's great threat. Deforestation → erosion, flooding. Pollution: air, water, land. Conservation: replanting, protected areas.",
},
"Commerce": {
 "Trade & Commerce": "Commerce = trade + aids to trade (banking, transport, insurance, warehousing, advertising). Wholesaler → retailer → consumer. Import/export.",
 "Business Organisation": "Sole proprietorship: one owner, unlimited liability. Partnership: 2–20 partners. Limited company: separate person, limited liability. Cooperative: member-owned.",
 "Money, Banking & Finance": "Central vs commercial banks. Credit: overdraft, loans, hire purchase. Cheque = written order to pay. Insurance: premium; insurable interest, good faith.",
 "Marketing & Sales": "Marketing mix: product, price, place, promotion. Advertising informs and persuades. Market research finds demand. Consumer rights: safety, information, choice, redress.",
 "Services & Infrastructure": "Warehousing stores goods; transport moves them; communication carries information. Storage links production and demand. Services make trade possible.",
 "Business Finance & Accounting": "Capital = money invested. Profit = revenue − expenses. Assets = liabilities + equity. Bookkeeping records; the ledger groups accounts. Turnover = total sales.",
},
"Computer Studies": {
 "Hardware & Systems": "CPU: fetch-decode-execute. Input: keyboard, mouse, scanner; output: monitor, printer. RAM = volatile working memory; ROM = permanent. Storage: HDD, SSD, flash.",
 "Software & Applications": "System software: operating system (Windows, Linux, Android). Application: word processor, spreadsheet, presentation, browser. Software = programs + data.",
 "Internet & Networks": "LAN = local; WAN = wide. Internet = network of networks. Email, browser, URL. Protocols: HTTP/HTTPS, FTP, TCP/IP. WWW: pages linked by hyperlinks.",
 "Programming & Algorithms": "Algorithm = step-by-step solution. Flowchart: oval start/stop, rectangle process, parallelogram I/O, diamond decision. Loops repeat; conditions branch. Python: print(), if/else, for, while.",
 "Data & Security": "Database: tables of records and fields. Virus (self-replicates), worm (network), trojan (hidden), spyware. Protect: antivirus, firewall, backup, passwords, encryption.",
 "Fundamentals & Ethics": "ICT = information and communication technology. Data (raw) vs information (processed). Ethics: privacy, accuracy, property, access. Digital divide: unequal access.",
},
"Civic Education": {
 "Values & Citizenship": "Values: honesty, integrity, discipline, hard work, selflessness. Citizenship: legal membership with rights and duties. Good citizen: obeys law, pays taxes, protects public property.",
 "Rights & Duties": "Human rights: life, dignity, fair hearing, expression, movement, religion, non-discrimination. Duties: obey the law, respect others' rights, defend the nation, vote.",
 "National Consciousness": "Nationalism: love of nation. Patriotism: active support. Symbols: flag, anthem, coat of arms, currency. Unity: living together despite differences.",
 "Democracy & Governance": "Democracy: government of, by, for the people. Rule of law: all equal under the law. Good governance: transparency, accountability, responsiveness. Participation: voting, service.",
 "Social & Community Issues": "Cultism destroys lives — avoid it, report it. Corruption: bribery, embezzlement, nepotism. Drug abuse harms health and society. Youth empowerment: skills + education.",
 "Health & Environment": "Sanitation: clean water, waste disposal, hygiene. HIV: prevent through safe behaviour; stigma harms. Avoid drugs and alcohol. A clean environment is a healthy environment.",
},
}
