# v30 Scholar Toolkit — Formula Vault data (WAEC/NECO/JAMB-aligned)
# (subject, category, name, formula, note)
FORMULAS = [
  # ---------- MATHEMATICS ----------
  ("Maths","Algebra","Indices — product rule","aᵐ × aⁿ = aᵐ⁺ⁿ","a = base; m, n = indices. Same base? Add the indices."),
  ("Maths","Algebra","Indices — quotient rule","aᵐ ÷ aⁿ = aᵐ⁻ⁿ","Same base? Subtract the indices."),
  ("Maths","Algebra","Indices — power rule","(aᵐ)ⁿ = aᵐⁿ","Multiply the indices."),
  ("Maths","Algebra","Indices — negative index","a⁻ⁿ = 1/aⁿ","Move the base across the fraction bar."),
  ("Maths","Algebra","Indices — fractional index","a^(m/n) = ⁿ√(aᵐ)","The denominator is the root, the numerator the power."),
  ("Maths","Algebra","Zero index","a⁰ = 1  (a ≠ 0)","Any non-zero base to the power 0 is 1."),
  ("Maths","Algebra","Quadratic formula","x = (−b ± √(b² − 4ac)) / 2a","Solves ax² + bx + c = 0. State the ± two roots."),
  ("Maths","Algebra","Discriminant","Δ = b² − 4ac","Δ > 0 two roots; Δ = 0 repeated; Δ < 0 no real roots."),
  ("Maths","Algebra","Difference of two squares","a² − b² = (a + b)(a − b)","Factorise pattern — spot it before expanding."),
  ("Maths","Algebra","Perfect square","(a ± b)² = a² ± 2ab + b²","Middle term is twice the product of a and b."),
  ("Maths","Algebra","Sum & product of roots","α + β = −b/a ; αβ = c/a","For ax² + bx + c = 0 with roots α, β."),
  ("Maths","Algebra","Logarithms — product","log(xy) = log x + log y","Multiplication becomes addition of logs."),
  ("Maths","Algebra","Logarithms — quotient","log(x/y) = log x − log y","Division becomes subtraction of logs."),
  ("Maths","Algebra","Logarithms — power","log xⁿ = n log x","Powers become multipliers."),
  ("Maths","Algebra","Change of base","logₐx = log x / log a","Useful when calculator has only log₁₀."),
  ("Maths","Algebra","Surd — rationalising","1/√a = √a/a","Multiply top and bottom by √a."),
  ("Maths","Sequences","Arithmetic — nth term","Tₙ = a + (n − 1)d","a = first term, d = common difference."),
  ("Maths","Sequences","Arithmetic — sum","Sₙ = n/2 [2a + (n − 1)d]","Also Sₙ = n/2 (a + L), L = last term."),
  ("Maths","Sequences","Geometric — nth term","Tₙ = arⁿ⁻¹","r = common ratio, a = first term."),
  ("Maths","Sequences","Geometric — sum","Sₙ = a(rⁿ − 1)/(r − 1) , r ≠ 1","Last term form: a(1 − rⁿ)/(1 − r)."),
  ("Maths","Sequences","Infinite GP sum","S∞ = a/(1 − r) , |r| < 1","Only when the ratio is between −1 and 1."),
  ("Maths","Commercial","Simple interest","I = PRT/100","P = principal, R = rate %, T = time (years)."),
  ("Maths","Commercial","Compound interest","A = P(1 + R/100)ⁿ","A = amount; interest = A − P; n = periods."),
  ("Maths","Commercial","Profit & loss","% profit = (profit/cost price) × 100","Profit = selling price − cost price."),
  ("Maths","Commercial","Simple discount","Selling price = marked price − discount","Discount is usually a % of the marked price."),
  ("Maths","Trigonometry","SOHCAHTOA","sin θ = opp/hyp ; cos θ = adj/hyp ; tan θ = opp/adj","Right-angled triangles only."),
  ("Maths","Trigonometry","Pythagorean identity","sin²θ + cos²θ = 1","Also 1 + tan²θ = sec²θ."),
  ("Maths","Trigonometry","Tangent identity","tan θ = sin θ / cos θ","Links sine and cosine to tangent."),
  ("Maths","Trigonometry","Sine rule","a/sin A = b/sin B = c/sin C","Any triangle: side over sine of opposite angle."),
  ("Maths","Trigonometry","Cosine rule","a² = b² + c² − 2bc cos A","Find a third side, or cos A = (b² + c² − a²)/2bc."),
  ("Maths","Trigonometry","Area of triangle","Area = ½ab sin C","Two sides and the included angle."),
  ("Maths","Trigonometry","Double angle — sine","sin 2θ = 2 sin θ cos θ","Also sin 2θ = 2tanθ/(1 + tan²θ)."),
  ("Maths","Trigonometry","Double angle — cosine","cos 2θ = cos²θ − sin²θ = 2cos²θ − 1","Choose the form that matches the question."),
  ("Maths","Mensuration","Pythagoras' theorem","c² = a² + b²","Hypotenuse squared = sum of other two squares."),
  ("Maths","Mensuration","Circumference","C = 2πr = πd","r = radius, d = diameter."),
  ("Maths","Mensuration","Area of circle","A = πr²","Remember to square the radius, not the diameter."),
  ("Maths","Mensuration","Arc length","L = (θ/360) × 2πr","θ in degrees, not radians."),
  ("Maths","Mensuration","Sector area","A = (θ/360) × πr²","A sector is a fraction of the circle."),
  ("Maths","Mensuration","Rectangle","A = length × breadth","Perimeter = 2(l + b)."),
  ("Maths","Mensuration","Triangle area","A = ½ × base × height","Any triangle, base and perpendicular height."),
  ("Maths","Mensuration","Trapezium","A = ½(a + b)h","a, b = parallel sides; h = perpendicular height."),
  ("Maths","Mensuration","Cuboid","V = lwh ; surface area = 2(lw + lh + wh)","Length × width × height."),
  ("Maths","Mensuration","Cylinder","V = πr²h ; curved area = 2πrh","Total surface area = 2πrh + 2πr²."),
  ("Maths","Mensuration","Cone","V = ⅓πr²h ; slant l = √(r² + h²)","Curved surface area = πrl."),
  ("Maths","Mensuration","Sphere","V = 4/3πr³ ; A = 4πr²","Volume and surface area — don't mix them up."),
  ("Maths","Mensuration","Polygon interior angles","Sum = (n − 2) × 180°","n = number of sides."),
  ("Maths","Mensuration","Similar shapes","Length × k ; Area × k² ; Volume × k³","k = scale factor between lengths."),
  ("Maths","Statistics","Mean (ungrouped)","x̄ = Σx / n","Add all values, divide by how many."),
  ("Maths","Statistics","Mean (grouped)","x̄ = Σfx / Σf","f = frequency, x = class midpoint."),
  ("Maths","Statistics","Variance","σ² = Σ(x − x̄)² / n","Also σ² = Σx²/n − (x̄)²."),
  ("Maths","Statistics","Standard deviation","σ = √σ²","The spread of data around the mean."),
  ("Maths","Statistics","Median (grouped)","Median = L + ((n/2 − F)/f) × c","L = lower class boundary, F = cumulative before, c = class width."),
  ("Maths","Statistics","Probability","P(A) = n(A)/n(Ω)","Favourable outcomes ÷ total outcomes."),
  ("Maths","Statistics","Addition rule","P(A∪B) = P(A) + P(B) − P(A∩B)","Mutually exclusive: P(A∪B) = P(A) + P(B)."),
  ("Maths","Statistics","Multiplication rule","P(A∩B) = P(A) × P(B)","For independent events."),
  ("Maths","Statistics","Conditional probability","P(A|B) = P(A∩B)/P(B)","Probability of A given B has happened."),
  ("Maths","Statistics","Expected value","E(X) = Σ x·P(x)","Weighted average of all outcomes."),

  # ---------- PHYSICS ----------
  ("Physics","Mechanics","First equation of motion","v = u + at","u = initial velocity, v = final, a = acceleration, t = time."),
  ("Physics","Mechanics","Second equation of motion","s = ut + ½at²","s = displacement."),
  ("Physics","Mechanics","Third equation of motion","v² = u² + 2as","Time-free — perfect when t is unknown."),
  ("Physics","Mechanics","Newton's 2nd law","F = ma","Force = mass × acceleration (net force)."),
  ("Physics","Mechanics","Weight","W = mg","g ≈ 9.8 m/s² (or 10 m/s² when told)."),
  ("Physics","Mechanics","Momentum","p = mv","Momentum is conserved in collisions."),
  ("Physics","Mechanics","Impulse","Ft = mv − mu","Force × time = change in momentum."),
  ("Physics","Mechanics","Kinetic energy","KE = ½mv²","Energy of motion — speed is squared."),
  ("Physics","Mechanics","Potential energy","PE = mgh","Energy of height — h measured from the reference."),
  ("Physics","Mechanics","Work","W = Fs cos θ","Force × displacement × cosine of the angle between."),
  ("Physics","Mechanics","Power","P = W/t = Fv","Rate of doing work."),
  ("Physics","Mechanics","Efficiency","η = (useful output/input) × 100%","Machines never give more than 100%."),
  ("Physics","Mechanics","Density","ρ = m/V","Mass per unit volume (kg/m³)."),
  ("Physics","Mechanics","Pressure","P = F/A","Force per unit area (Pa = N/m²)."),
  ("Physics","Mechanics","Pressure in a liquid","P = hρg","h = depth, ρ = density of the liquid."),
  ("Physics","Mechanics","Hooke's law","F = ke","Extension e is proportional to force; k = spring constant."),
  ("Physics","Mechanics","Moment of a force","τ = Fd","Turning effect; d = perpendicular distance from pivot."),
  ("Physics","Mechanics","Upthrust","U = ρVg","= weight of fluid displaced (Archimedes)."),
  ("Physics","Mechanics","Friction","F = μR","μ = coefficient of friction, R = normal reaction."),
  ("Physics","Mechanics","Universal gravitation","F = Gm₁m₂/r²","G = 6.67 × 10⁻¹¹ N m²/kg²."),
  ("Physics","Electricity","Ohm's law","V = IR","Voltage = current × resistance."),
  ("Physics","Electricity","Electrical power","P = VI","Also P = I²R and P = V²/R."),
  ("Physics","Electricity","Electrical energy","E = Pt","kWh = (kW × h) — the unit on electricity bills."),
  ("Physics","Electricity","Charge","Q = It","Current is the rate of flow of charge (coulombs)."),
  ("Physics","Electricity","Resistors in series","R = R₁ + R₂ + R₃ + …","Same current; resistances add."),
  ("Physics","Electricity","Resistors in parallel","1/R = 1/R₁ + 1/R₂ + …","Same voltage; total R is smaller than the smallest."),
  ("Physics","Electricity","Potential divider","V₁ = (R₁/(R₁ + R₂)) × V","Splits supply voltage in the ratio of the resistances."),
  ("Physics","Waves & Light","Wave speed","v = fλ","Speed = frequency × wavelength."),
  ("Physics","Waves & Light","Period","T = 1/f","Time for one complete cycle."),
  ("Physics","Waves & Light","Refractive index","n = sin i / sin r = c/v","Also the ratio of speeds in air and the medium."),
  ("Physics","Waves & Light","Critical angle","sin c = 1/n","Total internal reflection when angle > c."),
  ("Physics","Waves & Light","Lens / mirror formula","1/f = 1/u + 1/v","u = object distance, v = image distance, f = focal length."),
  ("Physics","Waves & Light","Magnification","m = v/u = hᵢ/ho","Image height ÷ object height."),
  ("Physics","Waves & Light","Echo distance","d = vt/2","Sound travels there AND back — halve it."),
  ("Physics","Thermal","Heat energy","Q = mcΔθ","c = specific heat capacity; Δθ = temperature change."),
  ("Physics","Thermal","Latent heat","Q = mL","L = specific latent heat (no temperature change)."),
  ("Physics","Thermal","Heat capacity","C = Q/Δθ","Heat capacity of the whole body."),
  ("Physics","Thermal","Linear expansion","L = L₀(1 + αΔθ)","α = coefficient of linear expansion."),
  ("Physics","Thermal","Boyle's law","P₁V₁ = P₂V₂ (T constant)","Pressure inversely proportional to volume."),
  ("Physics","Thermal","Charles' law","V₁/T₁ = V₂/T₂ (P constant)","Volume directly proportional to temperature (K)."),
  ("Physics","Thermal","Pressure law","P₁/T₁ = P₂/T₂ (V constant)","Use Kelvin temperatures, always."),
  ("Physics","Thermal","Combined gas law","P₁V₁/T₁ = P₂V₂/T₂","All quantities change at once."),
  ("Physics","Thermal","Ideal gas equation","PV = nRT","R = 8.31 J/(mol·K)."),

  # ---------- CHEMISTRY ----------
  ("Chemistry","Mole Concept","Moles from mass","n = m/M","m = mass (g), M = molar mass (g/mol)."),
  ("Chemistry","Mole Concept","Moles from particles","n = N/Nₐ","Nₐ = 6.02 × 10²³ mol⁻¹ (Avogadro's number)."),
  ("Chemistry","Mole Concept","Moles from gas volume","n = V/22.4 dm³ (s.t.p.) ; n = V/24 dm³ (r.t.p.)","Molar volume of any gas at the same conditions."),
  ("Chemistry","Mole Concept","Concentration","C = n/V (mol/dm³)","Amount of solute per volume of solution."),
  ("Chemistry","Mole Concept","Dilution","C₁V₁ = C₂V₂","Moles stay constant when you dilute."),
  ("Chemistry","Mole Concept","Percentage yield","% yield = (actual/theoretical) × 100","Theoretical from the balanced equation."),
  ("Chemistry","Mole Concept","Percentage purity","% purity = (mass of pure/sample mass) × 100","Impure samples give less product than expected."),
  ("Chemistry","Mole Concept","Empirical formula","Divide each % by atomic mass, then by the smallest","Gives the simplest whole-number ratio of atoms."),
  ("Chemistry","Mole Concept","Molecular formula","MF = (empirical formula) × n, n = Mᵣ/empirical Mᵣ","Whole-number multiple of the empirical formula."),
  ("Chemistry","Acids & Bases","pH","pH = −log₁₀[H⁺]","Below 7 acidic, above 7 alkaline."),
  ("Chemistry","Acids & Bases","Ionic product of water","Kw = [H⁺][OH⁻] = 1.0 × 10⁻¹⁴ at 25 °C","Also pH + pOH = 14."),
  ("Chemistry","Acids & Bases","Strong acid pH","[H⁺] = C  (monobasic acid)","Assume complete dissociation."),
  ("Chemistry","Electrochemistry","Faraday's law","m = (MIt)/(nF) ; Q = It ; F = 96500 C/mol","m = mass deposited; n = charge on the ion."),
  ("Chemistry","Electrochemistry","Electrolyte mass","m = zQ with z = M/(nF)","z = electrochemical equivalent."),
  ("Chemistry","Electrochemistry","Cell EMF","E°cell = E°cathode − E°anode","More positive reduction potential is the cathode."),
  ("Chemistry","Chemical Equations","Combustion of hydrocarbon","CₓHᵧ + (x + y/4)O₂ → xCO₂ + (y/2)H₂O","Balance, then use mole ratios for volumes."),
  ("Chemistry","Chemical Equations","Reacting volumes","V₁/V₂ = n₁/n₂ (same T and P)","Gay-Lussac: volumes react in mole ratio."),
  ("Chemistry","Chemical Equations","Percentage composition","% element = (mass of element/molar mass) × 100","From the formula, per mole."),
  ("Chemistry","Rates & Equilibrium","Rate of reaction","Rate = change in concentration / time","Slope of a concentration–time graph."),
  ("Chemistry","Rates & Equilibrium","Equilibrium constant","Kc = [C]ᶜ[D]ᵈ / [A]ᵃ[B]ᵇ","For aA + bB ⇌ cC + dD."),
  ("Chemistry","Energetics","Enthalpy change","ΔH = H(products) − H(reactants)","Negative = exothermic; positive = endothermic."),
  ("Chemistry","Organic","General alkane","CₙH₂ₙ₊₂","Saturated hydrocarbons."),
  ("Chemistry","Organic","General alkene","CₙH₂ₙ","Contain one C=C double bond."),
  ("Chemistry","Organic","General alkyne","CₙH₂ₙ₋₂","Contain one C≡C triple bond."),
]
